using System;
using System.Text;
using System.Collections.Generic;
using VinaLib;
namespace VinaERP
{
    #region ICDepartments
    //-----------------------------------------------------------
    //Generated By:VinaERP Studio
    //Class:ICDepartmentsInfo
    //Created Date:Saturday, November 10, 2018
    //-----------------------------------------------------------

    public class ICDepartmentsInfo : BusinessObject
    {
        public ICDepartmentsInfo()
        {
        }
        #region Variables
        protected int _iCDepartmentID;
        protected String _aAStatus = DefaultAAStatus;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected String _aACreatedUser = String.Empty;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected String _aAUpdatedUser = String.Empty;
        protected String _iCDepartmentNo = String.Empty;
        protected String _iCDepartmentName = String.Empty;
        protected String _iCDepartmentDesc = String.Empty;
        protected bool _iCDepartmentActiveCheck = true;
        #endregion

        #region Public properties
        public int ICDepartmentID
        {
            get { return _iCDepartmentID; }
            set
            {
                if (value != this._iCDepartmentID)
                {
                    _iCDepartmentID = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                }
            }
        }
        public String ICDepartmentNo
        {
            get { return _iCDepartmentNo; }
            set
            {
                if (value != this._iCDepartmentNo)
                {
                    _iCDepartmentNo = value;
                }
            }
        }
        public String ICDepartmentName
        {
            get { return _iCDepartmentName; }
            set
            {
                if (value != this._iCDepartmentName)
                {
                    _iCDepartmentName = value;
                }
            }
        }
        public String ICDepartmentDesc
        {
            get { return _iCDepartmentDesc; }
            set
            {
                if (value != this._iCDepartmentDesc)
                {
                    _iCDepartmentDesc = value;
                }
            }
        }
        public bool ICDepartmentActiveCheck
        {
            get { return _iCDepartmentActiveCheck; }
            set
            {
                if (value != this._iCDepartmentActiveCheck)
                {
                    _iCDepartmentActiveCheck = value;
                }
            }
        }
        #endregion
    }
    #endregion
}