using System;
using System.Text;
using System.Collections.Generic;
using VinaLib;
namespace VinaERP
{
    #region ICReceipts
    //-----------------------------------------------------------
    //Generated By:VinaERP Studio
    //Class:ICReceiptsInfo
    //Created Date:Tuesday, April 30, 2019
    //-----------------------------------------------------------

    public class ICReceiptsInfo : BusinessObject
    {
        public ICReceiptsInfo()
        {
        }
        #region Variables
        protected int _iCReceiptID;
        protected String _aAStatus = DefaultAAStatus;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected String _aACreatedUser = String.Empty;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected String _aAUpdatedUser = String.Empty;
        protected String _iCReceiptNo = String.Empty;
        protected String _iCReceiptName = String.Empty;
        protected String _iCReceiptDesc = String.Empty;
        protected DateTime _iCReceiptDate = DateTime.MaxValue;
        protected String _iCReceiptStatus = DefaultStatus;
        protected DateTime _iCReceiptDeliveryDate = DateTime.MaxValue;
        protected int _fK_HREmployeeID;
        protected int _fK_APSupplierID;
        protected String _iCReceiptPostedStatus = DefaultStatus;
        protected decimal _iCReceiptSubTotalAmount;
        protected decimal _iCReceiptDiscountPercent;
        protected decimal _iCReceiptDiscountAmount;
        protected decimal _iCReceiptTaxPercent;
        protected decimal _iCReceiptTaxAmount;
        protected decimal _iCReceiptTotalAmount;
        protected int _fK_ICStockID;
        protected String _iCReceiptProductLotNo = String.Empty;
        protected int _fK_GECurrencyID;
        protected decimal _iCReceiptExchangeRate;
        #endregion

        #region Public properties
        public int ICReceiptID
        {
            get { return _iCReceiptID; }
            set
            {
                if (value != this._iCReceiptID)
                {
                    _iCReceiptID = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                }
            }
        }
        public String ICReceiptNo
        {
            get { return _iCReceiptNo; }
            set
            {
                if (value != this._iCReceiptNo)
                {
                    _iCReceiptNo = value;
                }
            }
        }
        public String ICReceiptName
        {
            get { return _iCReceiptName; }
            set
            {
                if (value != this._iCReceiptName)
                {
                    _iCReceiptName = value;
                }
            }
        }
        public String ICReceiptDesc
        {
            get { return _iCReceiptDesc; }
            set
            {
                if (value != this._iCReceiptDesc)
                {
                    _iCReceiptDesc = value;
                }
            }
        }
        public DateTime ICReceiptDate
        {
            get { return _iCReceiptDate; }
            set
            {
                if (value != this._iCReceiptDate)
                {
                    _iCReceiptDate = value;
                }
            }
        }
        public String ICReceiptStatus
        {
            get { return _iCReceiptStatus; }
            set
            {
                if (value != this._iCReceiptStatus)
                {
                    _iCReceiptStatus = value;
                }
            }
        }
        public DateTime ICReceiptDeliveryDate
        {
            get { return _iCReceiptDeliveryDate; }
            set
            {
                if (value != this._iCReceiptDeliveryDate)
                {
                    _iCReceiptDeliveryDate = value;
                }
            }
        }
        public int FK_HREmployeeID
        {
            get { return _fK_HREmployeeID; }
            set
            {
                if (value != this._fK_HREmployeeID)
                {
                    _fK_HREmployeeID = value;
                }
            }
        }
        public int FK_APSupplierID
        {
            get { return _fK_APSupplierID; }
            set
            {
                if (value != this._fK_APSupplierID)
                {
                    _fK_APSupplierID = value;
                }
            }
        }
        public String ICReceiptPostedStatus
        {
            get { return _iCReceiptPostedStatus; }
            set
            {
                if (value != this._iCReceiptPostedStatus)
                {
                    _iCReceiptPostedStatus = value;
                }
            }
        }
        public decimal ICReceiptSubTotalAmount
        {
            get { return _iCReceiptSubTotalAmount; }
            set
            {
                if (value != this._iCReceiptSubTotalAmount)
                {
                    _iCReceiptSubTotalAmount = value;
                }
            }
        }
        public decimal ICReceiptDiscountPercent
        {
            get { return _iCReceiptDiscountPercent; }
            set
            {
                if (value != this._iCReceiptDiscountPercent)
                {
                    _iCReceiptDiscountPercent = value;
                }
            }
        }
        public decimal ICReceiptDiscountAmount
        {
            get { return _iCReceiptDiscountAmount; }
            set
            {
                if (value != this._iCReceiptDiscountAmount)
                {
                    _iCReceiptDiscountAmount = value;
                }
            }
        }
        public decimal ICReceiptTaxPercent
        {
            get { return _iCReceiptTaxPercent; }
            set
            {
                if (value != this._iCReceiptTaxPercent)
                {
                    _iCReceiptTaxPercent = value;
                }
            }
        }
        public decimal ICReceiptTaxAmount
        {
            get { return _iCReceiptTaxAmount; }
            set
            {
                if (value != this._iCReceiptTaxAmount)
                {
                    _iCReceiptTaxAmount = value;
                }
            }
        }
        public decimal ICReceiptTotalAmount
        {
            get { return _iCReceiptTotalAmount; }
            set
            {
                if (value != this._iCReceiptTotalAmount)
                {
                    _iCReceiptTotalAmount = value;
                }
            }
        }
        public int FK_ICStockID
        {
            get { return _fK_ICStockID; }
            set
            {
                if (value != this._fK_ICStockID)
                {
                    _fK_ICStockID = value;
                }
            }
        }
        public String ICReceiptProductLotNo
        {
            get { return _iCReceiptProductLotNo; }
            set
            {
                if (value != this._iCReceiptProductLotNo)
                {
                    _iCReceiptProductLotNo = value;
                }
            }
        }
        public int FK_GECurrencyID
        {
            get { return _fK_GECurrencyID; }
            set
            {
                if (value != this._fK_GECurrencyID)
                {
                    _fK_GECurrencyID = value;
                }
            }
        }
        public decimal ICReceiptExchangeRate
        {
            get { return _iCReceiptExchangeRate; }
            set
            {
                if (value != this._iCReceiptExchangeRate)
                {
                    _iCReceiptExchangeRate = value;
                }
            }
        }
        #endregion

        #region Extra Properties

        public byte[] ICReceiptEmployeePicture { get; set; }

        #endregion
    }
    #endregion
}