using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using VinaLib;


namespace VinaERP
{
    #region GECurrencies
    //-----------------------------------------------------------
    //Generated By:VinaERP Studio
    //Class:GECurrenciesController
    //Created Date:Wednesday, November 28, 2018
    //-----------------------------------------------------------

    public class GECurrenciesController : BaseBusinessController
    {
        public GECurrenciesController()
        {
            dal = new DALBaseProvider("GECurrencies", typeof(GECurrenciesInfo));
        }
    }
    #endregion
}