using System;
using System.Text;
using System.Collections.Generic;
using VinaLib;
namespace VinaERP
{
    #region ADWorkingShifts
    //-----------------------------------------------------------
    //Generated By: Vina Studio
    //Class:ADWorkingShiftsInfo
    //Created Date:Friday, August 10, 2018
    //-----------------------------------------------------------

    public class ADWorkingShiftsInfo : BusinessObject
    {
        public ADWorkingShiftsInfo()
        {
            ADWorkingShiftNight = false;
        }
        #region Variables
        protected int _aDWorkingShiftID;
        protected String _aAStatus = DefaultAAStatus;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected String _aACreatedUser = String.Empty;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected String _aAUpdatedUser = String.Empty;
        protected String _aDWorkingShiftNo = String.Empty;
        protected String _aDWorkingShiftName = String.Empty;
        protected String _aDWorkingShiftDesc = String.Empty;
        protected DateTime _aDWorkingShiftFromTime = DateTime.MaxValue;
        protected DateTime _aDWorkingShiftToTime = DateTime.MaxValue;
        protected int _aDWorkingShiftTimeBreak;
        protected bool _aDWorkingShiftNight = true;
        protected String _aDWorkingShiftDayOffWeek = String.Empty;
        protected int _fK_HRTimeSheetParamID;
        protected decimal _aDWorkingShiftWorkingTime;
        protected bool _aDWorkingShiftIsDefault = true;
        protected DateTime _aDWorkingShiftBreakTimeBetweenFrom = DateTime.MaxValue;
        protected DateTime _aDWorkingShiftBreakTimeBetweenTo = DateTime.MaxValue;
        protected DateTime _aDWorkingShiftTimeKeepInFrom = DateTime.MaxValue;
        protected DateTime _aDWorkingShiftTimeKeepInTo = DateTime.MaxValue;
        protected DateTime _aDWorkingShiftTimeKeepOutFrom = DateTime.MaxValue;
        protected DateTime _aDWorkingShiftTimeKeepOutTo = DateTime.MaxValue;
        protected int _fK_HRTimeSheetParamFactorID;
        protected int _fK_ADWorkingShiftGroupID;
        protected decimal _aDWorkingShiftAllowance;

        #endregion

        #region Public properties
        public int ADWorkingShiftID
        {
            get { return _aDWorkingShiftID; }
            set
            {
                if (value != this._aDWorkingShiftID)
                {
                    _aDWorkingShiftID = value;
                    NotifyChanged("ADWorkingShiftID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                    NotifyChanged("AACreatedDate");
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                    NotifyChanged("AACreatedUser");
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                    NotifyChanged("AAUpdatedDate");
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                    NotifyChanged("AAUpdatedUser");
                }
            }
        }
        public String ADWorkingShiftNo
        {
            get { return _aDWorkingShiftNo; }
            set
            {
                if (value != this._aDWorkingShiftNo)
                {
                    _aDWorkingShiftNo = value;
                    NotifyChanged("ADWorkingShiftNo");
                }
            }
        }
        public String ADWorkingShiftName
        {
            get { return _aDWorkingShiftName; }
            set
            {
                if (value != this._aDWorkingShiftName)
                {
                    _aDWorkingShiftName = value;
                    NotifyChanged("ADWorkingShiftName");
                }
            }
        }
        public String ADWorkingShiftDesc
        {
            get { return _aDWorkingShiftDesc; }
            set
            {
                if (value != this._aDWorkingShiftDesc)
                {
                    _aDWorkingShiftDesc = value;
                    NotifyChanged("ADWorkingShiftDesc");
                }
            }
        }
        public DateTime ADWorkingShiftFromTime
        {
            get { return _aDWorkingShiftFromTime; }
            set
            {
                if (value != this._aDWorkingShiftFromTime)
                {
                    _aDWorkingShiftFromTime = value;
                    NotifyChanged("ADWorkingShiftFromTime");
                }
            }
        }
        public DateTime ADWorkingShiftToTime
        {
            get { return _aDWorkingShiftToTime; }
            set
            {
                if (value != this._aDWorkingShiftToTime)
                {
                    _aDWorkingShiftToTime = value;
                    NotifyChanged("ADWorkingShiftToTime");
                }
            }
        }
        public int ADWorkingShiftTimeBreak
        {
            get { return _aDWorkingShiftTimeBreak; }
            set
            {
                if (value != this._aDWorkingShiftTimeBreak)
                {
                    _aDWorkingShiftTimeBreak = value;
                    NotifyChanged("ADWorkingShiftTimeBreak");
                }
            }
        }
        public bool ADWorkingShiftNight
        {
            get { return _aDWorkingShiftNight; }
            set
            {
                if (value != this._aDWorkingShiftNight)
                {
                    _aDWorkingShiftNight = value;
                    NotifyChanged("ADWorkingShiftNight");
                }
            }
        }
        public String ADWorkingShiftDayOffWeek
        {
            get { return _aDWorkingShiftDayOffWeek; }
            set
            {
                if (value != this._aDWorkingShiftDayOffWeek)
                {
                    _aDWorkingShiftDayOffWeek = value;
                    NotifyChanged("ADWorkingShiftDayOffWeek");
                }
            }
        }
        public int FK_HRTimeSheetParamID
        {
            get { return _fK_HRTimeSheetParamID; }
            set
            {
                if (value != this._fK_HRTimeSheetParamID)
                {
                    _fK_HRTimeSheetParamID = value;
                    NotifyChanged("FK_HRTimeSheetParamID");
                }
            }
        }
        public decimal ADWorkingShiftWorkingTime
        {
            get { return _aDWorkingShiftWorkingTime; }
            set
            {
                if (value != this._aDWorkingShiftWorkingTime)
                {
                    _aDWorkingShiftWorkingTime = value;
                    NotifyChanged("ADWorkingShiftWorkingTime");
                }
            }
        }
        public bool ADWorkingShiftIsDefault
        {
            get { return _aDWorkingShiftIsDefault; }
            set
            {
                if (value != this._aDWorkingShiftIsDefault)
                {
                    _aDWorkingShiftIsDefault = value;
                    NotifyChanged("ADWorkingShiftIsDefault");
                }
            }
        }
        public DateTime ADWorkingShiftBreakTimeBetweenFrom
        {
            get { return _aDWorkingShiftBreakTimeBetweenFrom; }
            set
            {
                if (value != this._aDWorkingShiftBreakTimeBetweenFrom)
                {
                    _aDWorkingShiftBreakTimeBetweenFrom = value;
                    NotifyChanged("ADWorkingShiftBreakTimeBetweenFrom");
                }
            }
        }
        public DateTime ADWorkingShiftBreakTimeBetweenTo
        {
            get { return _aDWorkingShiftBreakTimeBetweenTo; }
            set
            {
                if (value != this._aDWorkingShiftBreakTimeBetweenTo)
                {
                    _aDWorkingShiftBreakTimeBetweenTo = value;
                    NotifyChanged("ADWorkingShiftBreakTimeBetweenTo");
                }
            }
        }
        public DateTime ADWorkingShiftTimeKeepInFrom
        {
            get { return _aDWorkingShiftTimeKeepInFrom; }
            set
            {
                if (value != this._aDWorkingShiftTimeKeepInFrom)
                {
                    _aDWorkingShiftTimeKeepInFrom = value;
                    NotifyChanged("ADWorkingShiftTimeKeepInFrom");
                }
            }
        }
        public DateTime ADWorkingShiftTimeKeepInTo
        {
            get { return _aDWorkingShiftTimeKeepInTo; }
            set
            {
                if (value != this._aDWorkingShiftTimeKeepInTo)
                {
                    _aDWorkingShiftTimeKeepInTo = value;
                    NotifyChanged("ADWorkingShiftTimeKeepInTo");
                }
            }
        }
        public DateTime ADWorkingShiftTimeKeepOutFrom
        {
            get { return _aDWorkingShiftTimeKeepOutFrom; }
            set
            {
                if (value != this._aDWorkingShiftTimeKeepOutFrom)
                {
                    _aDWorkingShiftTimeKeepOutFrom = value;
                    NotifyChanged("ADWorkingShiftTimeKeepOutFrom");
                }
            }
        }
        public DateTime ADWorkingShiftTimeKeepOutTo
        {
            get { return _aDWorkingShiftTimeKeepOutTo; }
            set
            {
                if (value != this._aDWorkingShiftTimeKeepOutTo)
                {
                    _aDWorkingShiftTimeKeepOutTo = value;
                    NotifyChanged("ADWorkingShiftTimeKeepOutTo");
                }
            }
        }
        public int FK_HRTimeSheetParamFactorID
        {
            get { return _fK_HRTimeSheetParamFactorID; }
            set
            {
                if (value != this._fK_HRTimeSheetParamFactorID)
                {
                    _fK_HRTimeSheetParamFactorID = value;
                    NotifyChanged("FK_HRTimeSheetParamFactorID");
                }
            }
        }
        public int FK_ADWorkingShiftGroupID
        {
            get { return _fK_ADWorkingShiftGroupID; }
            set
            {
                if (value != this._fK_ADWorkingShiftGroupID)
                {
                    _fK_ADWorkingShiftGroupID = value;
                    NotifyChanged("FK_ADWorkingShiftGroupID");
                }
            }
        }
        public decimal ADWorkingShiftAllowance
        {
            get { return _aDWorkingShiftAllowance; }
            set
            {
                if (value != this._aDWorkingShiftAllowance)
                {
                    _aDWorkingShiftAllowance = value;
                    NotifyChanged("ADWorkingShiftAllowance");
                }
            }
        }

        #endregion
    }
    #endregion
}