using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using VinaLib;


namespace VinaERP
{
    #region ICReceipts
    //-----------------------------------------------------------
    //Generated By:VinaERP Studio
    //Class:ICReceiptsController
    //Created Date:Tuesday, April 30, 2019
    //-----------------------------------------------------------

    public class ICReceiptsController : BaseBusinessController
    {
        public ICReceiptsController()
        {
            dal = new DALBaseProvider("ICReceipts", typeof(ICReceiptsInfo));
        }
    }
    #endregion
}