using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using VinaLib;
using System.Collections;

namespace VinaERP
{
    #region ICStocks
    //-----------------------------------------------------------
    //Generated By:VinaERP Studio
    //Class:ICStocksController
    //Created Date:Saturday, December 1, 2018
    //-----------------------------------------------------------

    public class ICStocksController : BaseBusinessController
    {
        public ICStocksController()
        {
            dal = new DALBaseProvider("ICStocks", typeof(ICStocksInfo));
        }

        public override IList GetListFromDataSet(DataSet ds)
        {
            List<ICStocksInfo> stockList = new List<ICStocksInfo>();
            if (ds.Tables.Count > 0)
            {
                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    ICStocksInfo objStocksInfo = (ICStocksInfo)GetObjectFromDataRow(row);
                    stockList.Add(objStocksInfo);
                }
            }
            return stockList;
        }

        public List<ICStocksInfo> GetAllStockByStockType(string stockType)
        {
            DataSet ds = dal.GetDataSet("ICStocks_GetAllStockByStockType", stockType);
            return (List<ICStocksInfo>)GetListFromDataSet(ds);
        }

        public DataSet GetStockByStockType(string stockType)
        {
            return dal.GetDataSet("ICStocks_GetAllStockByStockType", stockType);
        }
    }
    #endregion
}