using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using VinaLib;


namespace VinaERP
{
    #region ICVitualTransactions
    //-----------------------------------------------------------
    //Generated By:VinaERP Studio
    //Class:ICVitualTransactionsController
    //Created Date:Sunday, April 28, 2019
    //-----------------------------------------------------------

    public class ICVitualTransactionsController : BaseBusinessController
    {
        public ICVitualTransactionsController()
        {
            dal = new DALBaseProvider("ICVitualTransactions", typeof(ICVitualTransactionsInfo));
        }
    }
    #endregion
}