using System;
using System.Text;
using System.Collections.Generic;
using VinaLib;
namespace VinaERP
{
    #region APSuppliers
    //-----------------------------------------------------------
    //Generated By:VinaERP Studio
    //Class:APSuppliersInfo
    //Created Date:13 Tháng Năm 2019
    //-----------------------------------------------------------

    public class APSuppliersInfo : BusinessObject
    {
        public APSuppliersInfo()
        {
        }
        #region Variables
        protected int _aPSupplierID;
        protected String _aAStatus = DefaultAAStatus;
        protected String _aACreatedUser = String.Empty;
        protected String _aAUpdatedUser = String.Empty;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected int _fK_GECurrencyID;
        protected String _aPSupplierNo = String.Empty;
        protected String _aPSupplierName = String.Empty;
        protected String _aPSupplierDesc = String.Empty;
        protected bool _aPSupplierActiveCheck = true;
        protected String _aPSupplierNoOfOldSys = String.Empty;
        protected byte[] _aPSupplierPicture;
        protected String _aPSupplierTypeCombo = String.Empty;
        protected String _aPSupplierWebsite = String.Empty;
        protected String _aPSupplierContactEmail = String.Empty;
        protected String _aPSupplierContactAddressLine = String.Empty;
        protected String _aPSupplierContactFax = String.Empty;
        protected String _aPSupplierContactPhone = String.Empty;
        protected String _aPSupplierContactCellPhone = String.Empty;
        protected String _aPSupplierPaymentMethodType = String.Empty;
        protected String _aPSupplierTaxNumber = String.Empty;
        protected String _aPSupplierBankName = String.Empty;
        protected String _aPSupplierBankCode = String.Empty;
        protected String _aPSupplierBankAccount = String.Empty;
        protected int _fK_GEPaymentTermID;
        #endregion

        #region Public properties
        public int APSupplierID
        {
            get { return _aPSupplierID; }
            set
            {
                if (value != this._aPSupplierID)
                {
                    _aPSupplierID = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                }
            }
        }
        public int FK_GECurrencyID
        {
            get { return _fK_GECurrencyID; }
            set
            {
                if (value != this._fK_GECurrencyID)
                {
                    _fK_GECurrencyID = value;
                }
            }
        }
        public String APSupplierNo
        {
            get { return _aPSupplierNo; }
            set
            {
                if (value != this._aPSupplierNo)
                {
                    _aPSupplierNo = value;
                }
            }
        }
        public String APSupplierName
        {
            get { return _aPSupplierName; }
            set
            {
                if (value != this._aPSupplierName)
                {
                    _aPSupplierName = value;
                }
            }
        }
        public String APSupplierDesc
        {
            get { return _aPSupplierDesc; }
            set
            {
                if (value != this._aPSupplierDesc)
                {
                    _aPSupplierDesc = value;
                }
            }
        }
        public bool APSupplierActiveCheck
        {
            get { return _aPSupplierActiveCheck; }
            set
            {
                if (value != this._aPSupplierActiveCheck)
                {
                    _aPSupplierActiveCheck = value;
                }
            }
        }
        public String APSupplierNoOfOldSys
        {
            get { return _aPSupplierNoOfOldSys; }
            set
            {
                if (value != this._aPSupplierNoOfOldSys)
                {
                    _aPSupplierNoOfOldSys = value;
                }
            }
        }
        public byte[] APSupplierPicture
        {
            get { return _aPSupplierPicture; }
            set
            {
                if (value != this._aPSupplierPicture)
                {
                    _aPSupplierPicture = value;
                }
            }
        }
        public String APSupplierTypeCombo
        {
            get { return _aPSupplierTypeCombo; }
            set
            {
                if (value != this._aPSupplierTypeCombo)
                {
                    _aPSupplierTypeCombo = value;
                }
            }
        }
        public String APSupplierWebsite
        {
            get { return _aPSupplierWebsite; }
            set
            {
                if (value != this._aPSupplierWebsite)
                {
                    _aPSupplierWebsite = value;
                }
            }
        }
        public String APSupplierContactEmail
        {
            get { return _aPSupplierContactEmail; }
            set
            {
                if (value != this._aPSupplierContactEmail)
                {
                    _aPSupplierContactEmail = value;
                }
            }
        }
        public String APSupplierContactAddressLine
        {
            get { return _aPSupplierContactAddressLine; }
            set
            {
                if (value != this._aPSupplierContactAddressLine)
                {
                    _aPSupplierContactAddressLine = value;
                }
            }
        }
        public String APSupplierContactFax
        {
            get { return _aPSupplierContactFax; }
            set
            {
                if (value != this._aPSupplierContactFax)
                {
                    _aPSupplierContactFax = value;
                }
            }
        }
        public String APSupplierContactPhone
        {
            get { return _aPSupplierContactPhone; }
            set
            {
                if (value != this._aPSupplierContactPhone)
                {
                    _aPSupplierContactPhone = value;
                }
            }
        }
        public String APSupplierContactCellPhone
        {
            get { return _aPSupplierContactCellPhone; }
            set
            {
                if (value != this._aPSupplierContactCellPhone)
                {
                    _aPSupplierContactCellPhone = value;
                }
            }
        }
        public String APSupplierPaymentMethodType
        {
            get { return _aPSupplierPaymentMethodType; }
            set
            {
                if (value != this._aPSupplierPaymentMethodType)
                {
                    _aPSupplierPaymentMethodType = value;
                }
            }
        }
        public String APSupplierTaxNumber
        {
            get { return _aPSupplierTaxNumber; }
            set
            {
                if (value != this._aPSupplierTaxNumber)
                {
                    _aPSupplierTaxNumber = value;
                }
            }
        }
        public String APSupplierBankName
        {
            get { return _aPSupplierBankName; }
            set
            {
                if (value != this._aPSupplierBankName)
                {
                    _aPSupplierBankName = value;
                }
            }
        }
        public String APSupplierBankCode
        {
            get { return _aPSupplierBankCode; }
            set
            {
                if (value != this._aPSupplierBankCode)
                {
                    _aPSupplierBankCode = value;
                }
            }
        }
        public String APSupplierBankAccount
        {
            get { return _aPSupplierBankAccount; }
            set
            {
                if (value != this._aPSupplierBankAccount)
                {
                    _aPSupplierBankAccount = value;
                }
            }
        }
        public int FK_GEPaymentTermID
        {
            get { return _fK_GEPaymentTermID; }
            set
            {
                if (value != this._fK_GEPaymentTermID)
                {
                    _fK_GEPaymentTermID = value;
                }
            }
        }
        #endregion
    }
    #endregion
}