using System;
using System.Text;
using System.Collections.Generic;
using VinaLib;
namespace VinaERP
{
    #region HRArrangementShifts
    //-----------------------------------------------------------
    //Generated By: Vina Studio
    //Class:HRArrangementShiftsInfo
    //Created Date:Tuesday, December 18, 2018
    //-----------------------------------------------------------

    public class HRArrangementShiftsInfo : BusinessObject
    {
        public HRArrangementShiftsInfo()
        {
        }
        #region Variables
        protected int _hRArrangementShiftID;
        protected String _aAStatus = DefaultAAStatus;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected String _aACreatedUser = String.Empty;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected String _aAUpdatedUser = String.Empty;
        protected String _hRArrangementShiftNo = String.Empty;
        protected String _hRArrangementShiftName = String.Empty;
        protected String _hRArrangementShiftDesc = String.Empty;
        protected DateTime _hRArrangementShiftFromDate = DateTime.MaxValue;
        protected DateTime _hRArrangementShiftToDate = DateTime.MaxValue;
        protected String _hRArrangementShiftType = String.Empty;
        protected int _fK_BRBranchID;
        protected int _fK_HREmployeeID;
        #endregion

        #region Public properties
        public int HRArrangementShiftID
        {
            get { return _hRArrangementShiftID; }
            set
            {
                if (value != this._hRArrangementShiftID)
                {
                    _hRArrangementShiftID = value;
                    NotifyChanged("HRArrangementShiftID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                    NotifyChanged("AACreatedDate");
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                    NotifyChanged("AACreatedUser");
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                    NotifyChanged("AAUpdatedDate");
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                    NotifyChanged("AAUpdatedUser");
                }
            }
        }
        public String HRArrangementShiftNo
        {
            get { return _hRArrangementShiftNo; }
            set
            {
                if (value != this._hRArrangementShiftNo)
                {
                    _hRArrangementShiftNo = value;
                    NotifyChanged("HRArrangementShiftNo");
                }
            }
        }
        public String HRArrangementShiftName
        {
            get { return _hRArrangementShiftName; }
            set
            {
                if (value != this._hRArrangementShiftName)
                {
                    _hRArrangementShiftName = value;
                    NotifyChanged("HRArrangementShiftName");
                }
            }
        }
        public String HRArrangementShiftDesc
        {
            get { return _hRArrangementShiftDesc; }
            set
            {
                if (value != this._hRArrangementShiftDesc)
                {
                    _hRArrangementShiftDesc = value;
                    NotifyChanged("HRArrangementShiftDesc");
                }
            }
        }
        public DateTime HRArrangementShiftFromDate
        {
            get { return _hRArrangementShiftFromDate; }
            set
            {
                if (value != this._hRArrangementShiftFromDate)
                {
                    _hRArrangementShiftFromDate = value;
                    NotifyChanged("HRArrangementShiftFromDate");
                }
            }
        }
        public DateTime HRArrangementShiftToDate
        {
            get { return _hRArrangementShiftToDate; }
            set
            {
                if (value != this._hRArrangementShiftToDate)
                {
                    _hRArrangementShiftToDate = value;
                    NotifyChanged("HRArrangementShiftToDate");
                }
            }
        }
        public String HRArrangementShiftType
        {
            get { return _hRArrangementShiftType; }
            set
            {
                if (value != this._hRArrangementShiftType)
                {
                    _hRArrangementShiftType = value;
                    NotifyChanged("HRArrangementShiftType");
                }
            }
        }
        public int FK_BRBranchID
        {
            get { return _fK_BRBranchID; }
            set
            {
                if (value != this._fK_BRBranchID)
                {
                    _fK_BRBranchID = value;
                    NotifyChanged("FK_BRBranchID");
                }
            }
        }
        public int FK_HREmployeeID
        {
            get { return _fK_HREmployeeID; }
            set
            {
                if (value != this._fK_HREmployeeID)
                {
                    _fK_HREmployeeID = value;
                    NotifyChanged("FK_HREmployeeID");
                }
            }
        }
        #endregion
    }
    #endregion
}