using System;
using System.Text;
using System.Collections.Generic;
using VinaLib;
namespace VinaERP
{
    #region HRCalendars
    //-----------------------------------------------------------
    //Generated By: Vina Studio
    //Class:HRCalendarsInfo
    //Created Date:Monday, April 25, 2011
    //-----------------------------------------------------------

    public class HRCalendarsInfo : BusinessObject
    {
        public HRCalendarsInfo()
        {
        }
        #region Variables
        protected int _hRCalendarID;
        protected String _aAStatus = DefaultAAStatus;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected String _aACreatedUser = String.Empty;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected String _aAUpdatedUser = String.Empty;
        protected String _hRCalendarNo = String.Empty;
        protected String _hRCalendarName = String.Empty;
        protected String _hRCalendarDesc = String.Empty;
        protected String _hRCalendarType = String.Empty;
        protected int _hRCalendarYear;
        #endregion

        #region Public properties
        public int HRCalendarID
        {
            get { return _hRCalendarID; }
            set
            {
                if (value != this._hRCalendarID)
                {
                    _hRCalendarID = value;
                    NotifyChanged("HRCalendarID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                    NotifyChanged("AACreatedDate");
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                    NotifyChanged("AACreatedUser");
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                    NotifyChanged("AAUpdatedDate");
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                    NotifyChanged("AAUpdatedUser");
                }
            }
        }
        public String HRCalendarNo
        {
            get { return _hRCalendarNo; }
            set
            {
                if (value != this._hRCalendarNo)
                {
                    _hRCalendarNo = value;
                    NotifyChanged("HRCalendarNo");
                }
            }
        }
        public String HRCalendarName
        {
            get { return _hRCalendarName; }
            set
            {
                if (value != this._hRCalendarName)
                {
                    _hRCalendarName = value;
                    NotifyChanged("HRCalendarName");
                }
            }
        }
        public String HRCalendarDesc
        {
            get { return _hRCalendarDesc; }
            set
            {
                if (value != this._hRCalendarDesc)
                {
                    _hRCalendarDesc = value;
                    NotifyChanged("HRCalendarDesc");
                }
            }
        }
        public String HRCalendarType
        {
            get { return _hRCalendarType; }
            set
            {
                if (value != this._hRCalendarType)
                {
                    _hRCalendarType = value;
                    NotifyChanged("HRCalendarType");
                }
            }
        }
        public int HRCalendarYear
        {
            get { return _hRCalendarYear; }
            set
            {
                if (value != this._hRCalendarYear)
                {
                    _hRCalendarYear = value;
                    NotifyChanged("HRCalendarYear");
                }
            }
        }
        #endregion
    }
    #endregion
}