using System;
using System.Text;
using System.Collections.Generic;
using VinaLib;
namespace VinaERP
{
    #region HRCalendarEntrys
    //-----------------------------------------------------------
    //Generated By: Vina Studio
    //Class:HRCalendarEntrysInfo
    //Created Date:Monday, April 25, 2011
    //-----------------------------------------------------------

    public class HRCalendarEntrysInfo : BusinessObject
    {
        public HRCalendarEntrysInfo()
        {
        }
        #region Variables
        protected int _hRCalendarEntryID;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_HRCalendarID;
        protected DateTime _hRCalendarEntryDate = DateTime.MaxValue;
        protected String _hRCalendarEntryDesc = String.Empty;
        #endregion

        #region Public properties
        public int HRCalendarEntryID
        {
            get { return _hRCalendarEntryID; }
            set
            {
                if (value != this._hRCalendarEntryID)
                {
                    _hRCalendarEntryID = value;
                    NotifyChanged("HRCalendarEntryID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public int FK_HRCalendarID
        {
            get { return _fK_HRCalendarID; }
            set
            {
                if (value != this._fK_HRCalendarID)
                {
                    _fK_HRCalendarID = value;
                    NotifyChanged("FK_HRCalendarID");
                }
            }
        }
        public DateTime HRCalendarEntryDate
        {
            get { return _hRCalendarEntryDate; }
            set
            {
                if (value != this._hRCalendarEntryDate)
                {
                    _hRCalendarEntryDate = value;
                    NotifyChanged("HRCalendarEntryDate");
                }
            }
        }
        public String HRCalendarEntryDesc
        {
            get { return _hRCalendarEntryDesc; }
            set
            {
                if (value != this._hRCalendarEntryDesc)
                {
                    _hRCalendarEntryDesc = value;
                    NotifyChanged("HRCalendarEntryDesc");
                }
            }
        }
        #endregion
    }
    #endregion
}