using System;
using System.Text;
using System.Collections.Generic;
using VinaLib;
namespace VinaERP
{
    #region HRDepartments
    //-----------------------------------------------------------
    //Generated By: Vina Studio
    //Class:HRDepartmentsInfo
    //Created Date:Monday, April 09, 2012
    //-----------------------------------------------------------

    public class HRDepartmentsInfo : BusinessObject
    {
        public HRDepartmentsInfo()
        {
        }
        #region Variables
        protected int _hRDepartmentID;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected String _aACreatedUser = String.Empty;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected String _aAUpdatedUser = String.Empty;
        protected String _aAStatus = DefaultAAStatus;
        protected String _hRDepartmentNo = String.Empty;
        protected String _hRDepartmentName = String.Empty;
        protected String _hRDepartmentDesc = String.Empty;
        protected int _fK_BRBranchID;
        protected decimal _hRDepartmentTotalEmployee;
        protected int _hRDepartmentMen;
        protected int _hRDepartmentWomen;
        protected decimal _hRDepartmentMenBoundary;
        protected decimal _hRDepartmentWoMenBoundary;
        protected decimal _hRDepartmentBoundary;
        protected bool _hRDepartmentIsBatch = true;
        #endregion

        #region Public properties
        public int HRDepartmentID
        {
            get { return _hRDepartmentID; }
            set
            {
                if (value != this._hRDepartmentID)
                {
                    _hRDepartmentID = value;
                    NotifyChanged("HRDepartmentID");
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                    NotifyChanged("AACreatedDate");
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                    NotifyChanged("AACreatedUser");
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                    NotifyChanged("AAUpdatedDate");
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                    NotifyChanged("AAUpdatedUser");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public String HRDepartmentNo
        {
            get { return _hRDepartmentNo; }
            set
            {
                if (value != this._hRDepartmentNo)
                {
                    _hRDepartmentNo = value;
                    NotifyChanged("HRDepartmentNo");
                }
            }
        }
        public String HRDepartmentName
        {
            get { return _hRDepartmentName; }
            set
            {
                if (value != this._hRDepartmentName)
                {
                    _hRDepartmentName = value;
                    NotifyChanged("HRDepartmentName");
                }
            }
        }
        public String HRDepartmentDesc
        {
            get { return _hRDepartmentDesc; }
            set
            {
                if (value != this._hRDepartmentDesc)
                {
                    _hRDepartmentDesc = value;
                    NotifyChanged("HRDepartmentDesc");
                }
            }
        }
        public int FK_BRBranchID
        {
            get { return _fK_BRBranchID; }
            set
            {
                if (value != this._fK_BRBranchID)
                {
                    _fK_BRBranchID = value;
                    NotifyChanged("FK_BRBranchID");
                }
            }
        }
        public decimal HRDepartmentTotalEmployee
        {
            get { return _hRDepartmentTotalEmployee; }
            set
            {
                if (value != this._hRDepartmentTotalEmployee)
                {
                    _hRDepartmentTotalEmployee = value;
                    NotifyChanged("HRDepartmentTotalEmployee");
                }
            }
        }
        public bool HRDepartmentIsBatch
        {
            get { return _hRDepartmentIsBatch; }
            set
            {
                if (value != this._hRDepartmentIsBatch)
                {
                    _hRDepartmentIsBatch = value;
                    NotifyChanged("HRDepartmentIsBatch");
                }
            }
        }
        public int HRDepartmentMen
        {
            get { return _hRDepartmentMen; }
            set
            {
                if (value != this._hRDepartmentMen)
                {
                    _hRDepartmentMen = value;
                    NotifyChanged("HRDepartmentMen");
                }
            }
        }
        public int HRDepartmentWomen
        {
            get { return _hRDepartmentWomen; }
            set
            {
                if (value != this._hRDepartmentWomen)
                {
                    _hRDepartmentWomen = value;
                    NotifyChanged("HRDepartmentWomen");
                }
            }
        }
        public decimal HRDepartmentMenBoundary
        {
            get { return _hRDepartmentMenBoundary; }
            set
            {
                if (value != this._hRDepartmentMenBoundary)
                {
                    _hRDepartmentMenBoundary = value;
                    NotifyChanged("HRDepartmentMenBoundary");
                }
            }
        }
        public decimal HRDepartmentWoMenBoundary
        {
            get { return _hRDepartmentWoMenBoundary; }
            set
            {
                if (value != this._hRDepartmentWoMenBoundary)
                {
                    _hRDepartmentWoMenBoundary = value;
                    NotifyChanged("HRDepartmentWoMenBoundary");
                }
            }
        }
        public decimal HRDepartmentBoundary
        {
            get { return _hRDepartmentBoundary; }
            set
            {
                if (value != this._hRDepartmentBoundary)
                {
                    _hRDepartmentBoundary = value;
                    NotifyChanged("HRDepartmentBoundary");
                }
            }
        }
        #endregion
    }
    #endregion
}