using System;
using System.Text;
using System.Collections.Generic;
using VinaLib;
namespace VinaERP
{
    #region HREmployeePayrollDetails
    //-----------------------------------------------------------
    //Generated By: Vina Studio
    //Class:HREmployeePayrollDetailsInfo
    //Created Date:17 Tháng Chín 2015
    //-----------------------------------------------------------

    public class HREmployeePayrollDetailsInfo : BusinessObject
    {
        public HREmployeePayrollDetailsInfo()
        {
            IsOT = false;
            IsOverTimeSheet = false;
        }
        #region Variables
        protected int _hREmployeePayrollDetailID;
        protected String _aAStatus = DefaultAAStatus;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected String _aACreatedUser = String.Empty;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected String _aAUpdatedUser = String.Empty;
        protected int _fK_HREmployeePayrollID;
        protected int _fK_HRTimeSheetParamID;
        protected String _hREmployeeTimeSheetOTDetailName = String.Empty;
        protected decimal _hREmployeeTimeSheetOTDetailFactor;
        protected decimal _hREmployeePayrollHours;
        protected decimal _hREmployeePayrollBasicSalary;
        protected decimal _hREmployeePayrollSalaryFactor;
        protected bool _isOT = true;
        protected bool _isNight = true;
        protected bool _isOverTimeSheet = true;
        protected decimal _hREmployeePayrollDetailPrecentAmount;
        protected decimal _hREmployeePayrollHourFactor;
        protected decimal _hREmployeePayrollDetailPrecentExceed;
        protected decimal _hREmployeePayrollDetailAllowanceWorkingShift;

        #endregion

        #region Public properties
        public int HREmployeePayrollDetailID
        {
            get { return _hREmployeePayrollDetailID; }
            set
            {
                if (value != this._hREmployeePayrollDetailID)
                {
                    _hREmployeePayrollDetailID = value;
                    NotifyChanged("HREmployeePayrollDetailID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                    NotifyChanged("AACreatedDate");
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                    NotifyChanged("AACreatedUser");
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                    NotifyChanged("AAUpdatedDate");
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                    NotifyChanged("AAUpdatedUser");
                }
            }
        }
        public int FK_HREmployeePayrollID
        {
            get { return _fK_HREmployeePayrollID; }
            set
            {
                if (value != this._fK_HREmployeePayrollID)
                {
                    _fK_HREmployeePayrollID = value;
                    NotifyChanged("FK_HREmployeePayrollID");
                }
            }
        }
        public int FK_HRTimeSheetParamID
        {
            get { return _fK_HRTimeSheetParamID; }
            set
            {
                if (value != this._fK_HRTimeSheetParamID)
                {
                    _fK_HRTimeSheetParamID = value;
                    NotifyChanged("FK_HRTimeSheetParamID");
                }
            }
        }
        public String HREmployeeTimeSheetOTDetailName
        {
            get { return _hREmployeeTimeSheetOTDetailName; }
            set
            {
                if (value != this._hREmployeeTimeSheetOTDetailName)
                {
                    _hREmployeeTimeSheetOTDetailName = value;
                    NotifyChanged("HREmployeeTimeSheetOTDetailName");
                }
            }
        }
        public decimal HREmployeeTimeSheetOTDetailFactor
        {
            get { return _hREmployeeTimeSheetOTDetailFactor; }
            set
            {
                if (value != this._hREmployeeTimeSheetOTDetailFactor)
                {
                    _hREmployeeTimeSheetOTDetailFactor = value;
                    NotifyChanged("HREmployeeTimeSheetOTDetailFactor");
                }
            }
        }
        public decimal HREmployeePayrollHours
        {
            get { return _hREmployeePayrollHours; }
            set
            {
                if (value != this._hREmployeePayrollHours)
                {
                    _hREmployeePayrollHours = value;
                    NotifyChanged("HREmployeePayrollHours");
                }
            }
        }
        public decimal HREmployeePayrollBasicSalary
        {
            get { return _hREmployeePayrollBasicSalary; }
            set
            {
                if (value != this._hREmployeePayrollBasicSalary)
                {
                    _hREmployeePayrollBasicSalary = value;
                    NotifyChanged("HREmployeePayrollBasicSalary");
                }
            }
        }
        public decimal HREmployeePayrollSalaryFactor
        {
            get { return _hREmployeePayrollSalaryFactor; }
            set
            {
                if (value != this._hREmployeePayrollSalaryFactor)
                {
                    _hREmployeePayrollSalaryFactor = value;
                    NotifyChanged("HREmployeePayrollSalaryFactor");
                }
            }
        }
        public bool IsOT
        {
            get { return _isOT; }
            set
            {
                if (value != this._isOT)
                {
                    _isOT = value;
                    NotifyChanged("IsOT");
                }
            }
        }
        public bool IsNight
        {
            get { return _isNight; }
            set
            {
                if (value != this._isNight)
                {
                    _isNight = value;
                    NotifyChanged("IsNight");
                }
            }
        }
        public bool IsOverTimeSheet
        {
            get { return _isOverTimeSheet; }
            set
            {
                if (value != this._isOverTimeSheet)
                {
                    _isOverTimeSheet = value;
                    NotifyChanged("IsOverTimeSheet");
                }
            }
        }
        public decimal HREmployeePayrollDetailPrecentAmount
        {
            get { return _hREmployeePayrollDetailPrecentAmount; }
            set
            {
                if (value != this._hREmployeePayrollDetailPrecentAmount)
                {
                    _hREmployeePayrollDetailPrecentAmount = value;
                    NotifyChanged("HREmployeePayrollDetailPrecentAmount");
                }
            }
        }
        public decimal HREmployeePayrollHourFactor
        {
            get { return _hREmployeePayrollHourFactor; }
            set
            {
                if (value != this._hREmployeePayrollHourFactor)
                {
                    _hREmployeePayrollHourFactor = value;
                    NotifyChanged("HREmployeePayrollHourFactor");
                }
            }
        }
        public decimal HREmployeePayrollDetailPrecentExceed
        {
            get { return _hREmployeePayrollDetailPrecentExceed; }
            set
            {
                if (value != this._hREmployeePayrollDetailPrecentExceed)
                {
                    _hREmployeePayrollDetailPrecentExceed = value;
                    NotifyChanged("HREmployeePayrollDetailPrecentExceed");
                }
            }
        }
        public decimal HREmployeePayrollDetailAllowanceWorkingShift
        {
            get { return _hREmployeePayrollDetailAllowanceWorkingShift; }
            set
            {
                if (value != this._hREmployeePayrollDetailAllowanceWorkingShift)
                {
                    _hREmployeePayrollDetailAllowanceWorkingShift = value;
                    NotifyChanged("HREmployeePayrollDetailAllowanceWorkingShift");
                }
            }
        }

        #endregion
    }
    #endregion
}