using System;
using System.Text;
using System.Collections.Generic;
using VinaLib;
namespace VinaERP
{
    #region HREmployeeAllowances
    //-----------------------------------------------------------
    //Generated By: Vina Studio
    //Class:HREmployeeAllowancesInfo
    //Created Date:Tuesday, June 14, 2016
    //-----------------------------------------------------------

    public class HREmployeeAllowancesInfo : BusinessObject
    {
        public HREmployeeAllowancesInfo()
        {
        }
        #region Variables
        protected int _hREmployeeAllowanceID;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_HRAllowanceID;
        protected int _fK_HREmployeeID;
        protected String _hREmployeeAllowanceValue = String.Empty;
        protected decimal _hREmployeeAllowanceValueAmount;
        protected decimal _hREmployeeAllowanceAmount;
        protected decimal _hREmployeeAllowanceQualityCriteria;
        protected decimal _hREmployeeAllowanceProductivityCriteria;
        protected decimal _hREmployeeAllowanceManageCriteria;
        protected decimal _hREmployeeAllowanceConfiguredQualityAmount;
        protected decimal _hREmployeeAllowanceConfiguredProductivityAmount;
        protected decimal _hREmployeeAllowanceConfiguredManageAmount;
        protected DateTime _hREmployeeAllowanceDate = DateTime.MaxValue;

        #endregion

        #region Public properties
        public int HREmployeeAllowanceID
        {
            get { return _hREmployeeAllowanceID; }
            set
            {
                if (value != this._hREmployeeAllowanceID)
                {
                    _hREmployeeAllowanceID = value;
                    NotifyChanged("HREmployeeAllowanceID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public int FK_HRAllowanceID
        {
            get { return _fK_HRAllowanceID; }
            set
            {
                if (value != this._fK_HRAllowanceID)
                {
                    _fK_HRAllowanceID = value;
                    NotifyChanged("FK_HRAllowanceID");
                }
            }
        }
        public int FK_HREmployeeID
        {
            get { return _fK_HREmployeeID; }
            set
            {
                if (value != this._fK_HREmployeeID)
                {
                    _fK_HREmployeeID = value;
                    NotifyChanged("FK_HREmployeeID");
                }
            }
        }
        public String HREmployeeAllowanceValue
        {
            get { return _hREmployeeAllowanceValue; }
            set
            {
                if (value != this._hREmployeeAllowanceValue)
                {
                    _hREmployeeAllowanceValue = value;
                    NotifyChanged("HREmployeeAllowanceValue");
                }
            }
        }
        public decimal HREmployeeAllowanceValueAmount
        {
            get { return _hREmployeeAllowanceValueAmount; }
            set
            {
                if (value != this._hREmployeeAllowanceValueAmount)
                {
                    _hREmployeeAllowanceValueAmount = value;
                    NotifyChanged("HREmployeeAllowanceValueAmount");
                }
            }
        }
        public decimal HREmployeeAllowanceAmount
        {
            get { return _hREmployeeAllowanceAmount; }
            set
            {
                if (value != this._hREmployeeAllowanceAmount)
                {
                    _hREmployeeAllowanceAmount = value;
                    NotifyChanged("HREmployeeAllowanceAmount");
                }
            }
        }
        public decimal HREmployeeAllowanceQualityCriteria
        {
            get { return _hREmployeeAllowanceQualityCriteria; }
            set
            {
                if (value != this._hREmployeeAllowanceQualityCriteria)
                {
                    _hREmployeeAllowanceQualityCriteria = value;
                    NotifyChanged("HREmployeeAllowanceQualityCriteria");
                }
            }
        }
        public decimal HREmployeeAllowanceProductivityCriteria
        {
            get { return _hREmployeeAllowanceProductivityCriteria; }
            set
            {
                if (value != this._hREmployeeAllowanceProductivityCriteria)
                {
                    _hREmployeeAllowanceProductivityCriteria = value;
                    NotifyChanged("HREmployeeAllowanceProductivityCriteria");
                }
            }
        }
        public decimal HREmployeeAllowanceManageCriteria
        {
            get { return _hREmployeeAllowanceManageCriteria; }
            set
            {
                if (value != this._hREmployeeAllowanceManageCriteria)
                {
                    _hREmployeeAllowanceManageCriteria = value;
                    NotifyChanged("HREmployeeAllowanceManageCriteria");
                }
            }
        }
        public decimal HREmployeeAllowanceConfiguredQualityAmount
        {
            get { return _hREmployeeAllowanceConfiguredQualityAmount; }
            set
            {
                if (value != this._hREmployeeAllowanceConfiguredQualityAmount)
                {
                    _hREmployeeAllowanceConfiguredQualityAmount = value;
                    NotifyChanged("HREmployeeAllowanceConfiguredQualityAmount");
                }
            }
        }
        public decimal HREmployeeAllowanceConfiguredProductivityAmount
        {
            get { return _hREmployeeAllowanceConfiguredProductivityAmount; }
            set
            {
                if (value != this._hREmployeeAllowanceConfiguredProductivityAmount)
                {
                    _hREmployeeAllowanceConfiguredProductivityAmount = value;
                    NotifyChanged("HREmployeeAllowanceConfiguredProductivityAmount");
                }
            }
        }
        public decimal HREmployeeAllowanceConfiguredManageAmount
        {
            get { return _hREmployeeAllowanceConfiguredManageAmount; }
            set
            {
                if (value != this._hREmployeeAllowanceConfiguredManageAmount)
                {
                    _hREmployeeAllowanceConfiguredManageAmount = value;
                    NotifyChanged("HREmployeeAllowanceConfiguredManageAmount");
                }
            }
        }
        public DateTime HREmployeeAllowanceDate
        {
            get { return _hREmployeeAllowanceDate; }
            set
            {
                if (value != this._hREmployeeAllowanceDate)
                {
                    _hREmployeeAllowanceDate = value;
                    NotifyChanged("HREmployeeAllowanceDate");
                }
            }
        }

        #endregion
        #region Extra properties
        /// <summary>
        /// Get or set employee No
        /// </summary>
        public String HREmployeeNo { get; set; }
        public string HREmployeeCardNumber { get; set; }
        public bool HRAllowanceByWorkDay { get; set; }
        public DateTime HRAllowanceFromDate { get; set; }
        public DateTime HRAllowanceToDate { get; set; }
        public String HRAllowanceType { get; set; }
        #endregion
    }
    #endregion
}