using System;
using System.Text;
using System.Collections.Generic;
using VinaLib;
namespace VinaERP
{
    #region HREmployeeOTs
    //-----------------------------------------------------------
    //Generated By: Vina Studio
    //Class:HREmployeeOTsInfo
    //Created Date:Monday, April 25, 2011
    //-----------------------------------------------------------

    public class HREmployeeOTsInfo : BusinessObject
    {
        public HREmployeeOTsInfo()
        {
        }
        #region Variables
        protected int _hREmployeeOTID;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_HROverTimeID;
        protected int _fK_HREmployeeID;
        protected String _hREmployeeOTDesc = String.Empty;
        protected int _fK_HREmployeeID2;
        protected int _fK_HRDepartmentID;
        protected int _fK_HRDepartmentRoomID;
        protected int _fK_HRDepartmentRoomGroupItemID;
        protected DateTime _hREmployeeOTFromDate = DateTime.MaxValue;
        protected DateTime _hREmployeeOTToDate = DateTime.MaxValue;
        protected DateTime _hREmployeeOTDate = DateTime.MaxValue;
        protected DateTime _hREmployeeOTDateEnd = DateTime.MaxValue;
        protected decimal _hREmployeeOTFactor;
        protected int _fK_ADWorkingShiftID;
        protected int _fK_HRTimeSheetParamID;

        #endregion

        #region Public properties
        public int HREmployeeOTID
        {
            get { return _hREmployeeOTID; }
            set
            {
                if (value != this._hREmployeeOTID)
                {
                    _hREmployeeOTID = value;
                    NotifyChanged("HREmployeeOTID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public int FK_HROverTimeID
        {
            get { return _fK_HROverTimeID; }
            set
            {
                if (value != this._fK_HROverTimeID)
                {
                    _fK_HROverTimeID = value;
                    NotifyChanged("FK_HROverTimeID");
                }
            }
        }
        public int FK_HREmployeeID
        {
            get { return _fK_HREmployeeID; }
            set
            {
                if (value != this._fK_HREmployeeID)
                {
                    _fK_HREmployeeID = value;
                    NotifyChanged("FK_HREmployeeID");
                }
            }
        }
        public String HREmployeeOTDesc
        {
            get { return _hREmployeeOTDesc; }
            set
            {
                if (value != this._hREmployeeOTDesc)
                {
                    _hREmployeeOTDesc = value;
                    NotifyChanged("HREmployeeOTDesc");
                }
            }
        }
        public int FK_HREmployeeID2
        {
            get { return _fK_HREmployeeID2; }
            set
            {
                if (value != this._fK_HREmployeeID2)
                {
                    _fK_HREmployeeID2 = value;
                    NotifyChanged("FK_HREmployeeID2");
                }
            }
        }
        public int FK_HRDepartmentID
        {
            get { return _fK_HRDepartmentID; }
            set
            {
                if (value != this._fK_HRDepartmentID)
                {
                    _fK_HRDepartmentID = value;
                    NotifyChanged("FK_HRDepartmentID");
                }
            }
        }
        public int FK_HRDepartmentRoomID
        {
            get { return _fK_HRDepartmentRoomID; }
            set
            {
                if (value != this._fK_HRDepartmentRoomID)
                {
                    _fK_HRDepartmentRoomID = value;
                    NotifyChanged("FK_HRDepartmentRoomID");
                }
            }
        }
        public int FK_HRDepartmentRoomGroupItemID
        {
            get { return _fK_HRDepartmentRoomGroupItemID; }
            set
            {
                if (value != this._fK_HRDepartmentRoomGroupItemID)
                {
                    _fK_HRDepartmentRoomGroupItemID = value;
                    NotifyChanged("FK_HRDepartmentRoomGroupItemID");
                }
            }
        }
        public DateTime HREmployeeOTFromDate
        {
            get { return _hREmployeeOTFromDate; }
            set
            {
                if (value != this._hREmployeeOTFromDate)
                {
                    _hREmployeeOTFromDate = value;
                    NotifyChanged("HREmployeeOTFromDate");
                }
            }
        }
        public DateTime HREmployeeOTToDate
        {
            get { return _hREmployeeOTToDate; }
            set
            {
                if (value != this._hREmployeeOTToDate)
                {
                    _hREmployeeOTToDate = value;
                    NotifyChanged("HREmployeeOTToDate");
                }
            }
        }
        public DateTime HREmployeeOTDate
        {
            get { return _hREmployeeOTDate; }
            set
            {
                if (value != this._hREmployeeOTDate)
                {
                    _hREmployeeOTDate = value;
                    NotifyChanged("HREmployeeOTDate");
                }
            }
        }
        public DateTime HREmployeeOTDateEnd
        {
            get { return _hREmployeeOTDateEnd; }
            set
            {
                if (value != this._hREmployeeOTDateEnd)
                {
                    _hREmployeeOTDateEnd = value;
                    NotifyChanged("HREmployeeOTDateEnd");
                }
            }
        }
        public decimal HREmployeeOTFactor
        {
            get { return _hREmployeeOTFactor; }
            set
            {
                if (value != this._hREmployeeOTFactor)
                {
                    _hREmployeeOTFactor = value;
                    NotifyChanged("HREmployeeOTFactor");
                }
            }
        }
        public int FK_ADWorkingShiftID
        {
            get { return _fK_ADWorkingShiftID; }
            set
            {
                if (value != this._fK_ADWorkingShiftID)
                {
                    _fK_ADWorkingShiftID = value;
                    NotifyChanged("FK_ADWorkingShiftID");
                }
            }
        }
        public int FK_HRTimeSheetParamID
        {
            get { return _fK_HRTimeSheetParamID; }
            set
            {
                if (value != this._fK_HRTimeSheetParamID)
                {
                    _fK_HRTimeSheetParamID = value;
                    NotifyChanged("FK_HRTimeSheetParamID");
                }
            }
        }

        #endregion


        #region ExtraProperty
        public String HREmployeeName { get; set; }
        public string HREmployeeCardNumber { get; set; }
        public DateTime HROverTimeDateEnd { get; set; }
        public DateTime HROverTimeDate { get; set; }
        public DateTime HROverTimeFromDate { get; set; }
        public DateTime HROverTimeToDate { get; set; }
        public DateTime HRWorkingShiftToTime { get; set; }
        public DateTime HROverTimeFromTimeIn { get; set; }
        public DateTime HROverTimeFromTimeOut { get; set; }
        public DateTime HROverTimeToTimeIn { get; set; }
        public DateTime HROverTimeToTimeOut { get; set; }
        public bool HROverTimeDefaultOT { get; set; }
        public decimal HREmployeeOTPermissionOTDaysOff { get; set; }
        #endregion
    }
    #endregion
}