using System;
using System.Text;
using System.Collections.Generic;
using VinaLib;
namespace VinaERP
{
    #region HREmployeePayRolls
    //-----------------------------------------------------------
    //Generated By: Vina Studio
    //Class:HREmployeePayRollsInfo
    //Created Date:Monday, April 11, 2011
    //-----------------------------------------------------------

    public class HREmployeePayRollsInfo : BusinessObject
    {
        public HREmployeePayRollsInfo()
        {
        }

        #region Variables
        protected int _hREmployeePayRollID;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_HREmployeeID;
        protected int _fK_HRPayRollID;
        protected int _fK_HRDepartmentRoomID;
        protected decimal _hREmployeePayRollUnitPrice;
        protected decimal _hREmployeePayRollWorkingSalary;
        protected decimal _hREmployeePayRollOTSalary;
        protected decimal _hREmployeePayRollLeaveSalary;
        protected decimal _hREmployeePayRollExtraSalary;
        protected decimal _hREmployeePayRollSocialInsAmount;
        protected decimal _hREmployeePayRollHealthInsAmount;
        protected decimal _hREmployeePayRollOutOfWorkInsAmount;
        protected decimal _hREmployeePayRollSyndicateFee;
        protected decimal _hREmployeePayRollIncomeTaxAmount;
        protected decimal _hREmployeePayRollCommission;
        protected decimal _hREmployeePayRollReward;
        protected decimal _hREmployeePayRollDiscipline;
        protected decimal _hREmployeePayRollAdvance;
        protected decimal _hREmployeePayRollTotalSalary;
        protected String _hREmployeePayRollComment = String.Empty;
        protected String _hREmployeeCardNumber = String.Empty;
        protected int _fK_HRDepartmentID;
        protected decimal _hREmployeeDaysPerMonth;
        protected decimal _hREmployeeRealDaysPerMonth;
        protected decimal _hREmployeeHoursOT;
        protected decimal _hREmployeeWorkingSlrAmtFull;
        protected decimal _hREmployeePieceworkSalary;
        protected decimal _hREmployeeOffsetSalary;
        protected decimal _hREmployeeLuongDaTru;
        protected decimal _hREmployeeNoLuyTien;
        protected decimal _hREmployeeSalaryFactor;
        protected int _fK_HRLevelID;
        protected decimal _hREmployeePayRollFuelTotalAmount;
        protected decimal _hREmployeePayRollBusAllowance;
        protected decimal _hREmployeePayRollEffectiveAllowance;
        protected decimal _hREmployeePayRollDiligenceAllowance;
        protected decimal _hREmployeePayRollHeavyToxicAllowance;
        protected decimal _hREmployeePayRollPerennialAllowance;
        protected decimal _hREmployeePayRollOtherAllowance;
        protected decimal _hREmployeePayRollWorkingSlrAmt;
        protected decimal _hREmployeePayRollContractSlrAmt;
        protected decimal _hREmployeePayRollHoursPerDay;
        protected decimal _hREmployeePayRollSalaryFactor;
        protected decimal _hREmployeePayRollDaysPerMonth;

        protected decimal _hREmployeePayrollNghiPhepNam;
        protected decimal _hREmployeePayrollNghiLe;
        protected decimal _hREmployeePayrollNghiCheDo;
        protected decimal _hREmployeePayrollNghiCupDien;
        protected decimal _hREmployeePayrollNghiPhep;
        protected decimal _hREmployeePayrollCtyChoNghi;
        protected decimal _hREmployeePayrollNghiKPhep;
        protected decimal _hREmployeePayrollBHTaiNan;
        protected decimal _hREmployeePayrollPhiTheTu;
        protected decimal _hREmployeePayrollPhiTheATM;
        protected decimal _hREmployeePayrollPhiAo;
        protected decimal _hREmployeePayrollTruKhac;
        protected decimal _hREmployeePayrollTruThueTNCN;
        protected decimal _hREmployeePayrollTongThuNhap;
        protected decimal _hREmployeePayrollTongCacKhoanTru;
        protected decimal _hREmployeePayRollEmployeeLoanMonthlyAmount;
        protected decimal _hREmployeePayRollOthersAllowance;
        protected decimal _hREmployeePayRollResponsibilityAllowance;
        protected decimal _hREmployeePayRollKPIAllowance;
        protected decimal _hREmployeePayRollProgressAllowance;
        protected decimal _hREmployeePayRollAllowance;
        protected decimal _hREmployeePayRollRewardTarget;
        protected decimal _hREmployeePayRollPercentAllowance;
        protected decimal _hREmployeePayRollAmountAllowance;

        protected decimal _hREmployeePayRollNgayNghiHuongLuong;
        protected decimal _hREmployeePayRollNgayNghiKhongLuong;
        protected decimal _hREmployeePayRollDayOT;
        protected decimal _hREmployeePayRollTongNgayCong;
        protected decimal _hREmployeePayRollSoLuongBoc;
        protected decimal _hREmployeePayRollLuongThang;
        protected decimal _hREmployeePayRollAllowanceGasoline;
        protected decimal _hREmployeePayRollAllowanceMotel;
        protected decimal _hREmployeePayRollLate;
        protected decimal _hREmployeePayRollPurchaseOrder;
        protected decimal _hREmployeePayRollAllowanceRise;
        protected decimal _hREmployeeRealNightsPerMonth;
        protected decimal _hREmployeePayRollAllowaceNight;
        protected decimal _hREmployeePayRollAllowanceVehicleMaintenance;
        protected decimal _hREmployeePayRollProbationaryExtraSalary;
        protected decimal _hREmployeePayRollAllowanceWorkSchedule;
        protected decimal _hREmployeePayRollProbationaryRealDaysPerMonth;
        protected decimal _hREmployeePayRollApprenticeRealDaysPerMonth;
        protected decimal _hREmployeePayRollProbationarySalaryAmount;
        protected decimal _hREmployeePayRollApprenticeSalaryAmount;
        protected decimal _hREmployeePayRollSubtractLateAmount;
        protected decimal _hREmployeePayRollSubtractPhoneAmount;
        protected String _hREmployeePayRollWarning = String.Empty;
        protected decimal _hREmployeePayRollProvinceAllowance;

        protected String _fK_HREmployeePayRollKPI = String.Empty;
        protected String _fK_HREmployeePayRollAllowance = String.Empty;
        protected String _fK_HREmployeePayRollDiscipline = String.Empty;
        protected String _fK_HREmployeePayRollPieceWage = String.Empty;
        protected decimal _hREmployeePayRollSocialInsDNAmount;
        protected decimal _hREmployeePayRollHealthInsDNAmount;
        protected decimal _hREmployeePayRollOutOfWorkInsDNAmount;
        protected String _fK_HREmployeePayRollAdvanceRequestItemLoanDetails = String.Empty;
        protected decimal _hREmployeePayRollTaxableIncomeLevel;
        protected decimal _hREmployeePayRollPersonalIncomeTax;
        protected String _hREmployeePayRollNoteOT = String.Empty;
        protected decimal _hREmployeePayRollResponsibilityCommodityAllowance;
        protected decimal _hREmployeeBasicSalary;
        protected decimal _hREmployeePayRollDaysOffAmount;
        protected decimal _hREmployeePayRollTheChan;
        protected decimal _hREmployeePayRollOtherReward;
        protected decimal _hREmployeePayRollBackTheChan;
        protected decimal _hREmployeePayrollNghiLeAmount;

        #endregion

        #region Public properties
        public int HREmployeePayRollID
        {
            get { return _hREmployeePayRollID; }
            set
            {
                if (value != this._hREmployeePayRollID)
                {
                    _hREmployeePayRollID = value;
                    NotifyChanged("HREmployeePayRollID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public int FK_HREmployeeID
        {
            get { return _fK_HREmployeeID; }
            set
            {
                if (value != this._fK_HREmployeeID)
                {
                    _fK_HREmployeeID = value;
                    NotifyChanged("FK_HREmployeeID");
                }
            }
        }
        public int FK_HRPayRollID
        {
            get { return _fK_HRPayRollID; }
            set
            {
                if (value != this._fK_HRPayRollID)
                {
                    _fK_HRPayRollID = value;
                    NotifyChanged("FK_HRPayRollID");
                }
            }
        }
        public int FK_HRDepartmentRoomID
        {
            get { return _fK_HRDepartmentRoomID; }
            set
            {
                if (value != this._fK_HRDepartmentRoomID)
                {
                    _fK_HRDepartmentRoomID = value;
                    NotifyChanged("FK_HRDepartmentRoomID");
                }
            }
        }
        public decimal HREmployeePayRollUnitPrice
        {
            get { return _hREmployeePayRollUnitPrice; }
            set
            {
                if (value != this._hREmployeePayRollUnitPrice)
                {
                    _hREmployeePayRollUnitPrice = value;
                    NotifyChanged("HREmployeePayRollUnitPrice");
                }
            }
        }
        public decimal HREmployeePayRollWorkingSalary
        {
            get { return _hREmployeePayRollWorkingSalary; }
            set
            {
                if (value != this._hREmployeePayRollWorkingSalary)
                {
                    _hREmployeePayRollWorkingSalary = value;
                    NotifyChanged("HREmployeePayRollWorkingSalary");
                }
            }
        }
        public decimal HREmployeePayRollOTSalary
        {
            get { return _hREmployeePayRollOTSalary; }
            set
            {
                if (value != this._hREmployeePayRollOTSalary)
                {
                    _hREmployeePayRollOTSalary = value;
                    NotifyChanged("HREmployeePayRollOTSalary");
                }
            }
        }
        public decimal HREmployeePayRollLeaveSalary
        {
            get { return _hREmployeePayRollLeaveSalary; }
            set
            {
                if (value != this._hREmployeePayRollLeaveSalary)
                {
                    _hREmployeePayRollLeaveSalary = value;
                    NotifyChanged("HREmployeePayRollLeaveSalary");
                }
            }
        }
        public decimal HREmployeePayRollExtraSalary
        {
            get { return _hREmployeePayRollExtraSalary; }
            set
            {
                if (value != this._hREmployeePayRollExtraSalary)
                {
                    _hREmployeePayRollExtraSalary = value;
                    NotifyChanged("HREmployeePayRollExtraSalary");
                }
            }
        }
        public decimal HREmployeePayRollSocialInsAmount
        {
            get { return _hREmployeePayRollSocialInsAmount; }
            set
            {
                if (value != this._hREmployeePayRollSocialInsAmount)
                {
                    _hREmployeePayRollSocialInsAmount = value;
                    NotifyChanged("HREmployeePayRollSocialInsAmount");
                }
            }
        }
        public decimal HREmployeePayRollHealthInsAmount
        {
            get { return _hREmployeePayRollHealthInsAmount; }
            set
            {
                if (value != this._hREmployeePayRollHealthInsAmount)
                {
                    _hREmployeePayRollHealthInsAmount = value;
                    NotifyChanged("HREmployeePayRollHealthInsAmount");
                }
            }
        }
        public decimal HREmployeePayRollOutOfWorkInsAmount
        {
            get { return _hREmployeePayRollOutOfWorkInsAmount; }
            set
            {
                if (value != this._hREmployeePayRollOutOfWorkInsAmount)
                {
                    _hREmployeePayRollOutOfWorkInsAmount = value;
                    NotifyChanged("HREmployeePayRollOutOfWorkInsAmount");
                }
            }
        }
        public decimal HREmployeePayRollSyndicateFee
        {
            get { return _hREmployeePayRollSyndicateFee; }
            set
            {
                if (value != this._hREmployeePayRollSyndicateFee)
                {
                    _hREmployeePayRollSyndicateFee = value;
                    NotifyChanged("HREmployeePayRollSyndicateFee");
                }
            }
        }
        public decimal HREmployeePayRollIncomeTaxAmount
        {
            get { return _hREmployeePayRollIncomeTaxAmount; }
            set
            {
                if (value != this._hREmployeePayRollIncomeTaxAmount)
                {
                    _hREmployeePayRollIncomeTaxAmount = value;
                    NotifyChanged("HREmployeePayRollIncomeTaxAmount");
                }
            }
        }
        public decimal HREmployeePayRollCommission
        {
            get { return _hREmployeePayRollCommission; }
            set
            {
                if (value != this._hREmployeePayRollCommission)
                {
                    _hREmployeePayRollCommission = value;
                    NotifyChanged("HREmployeePayRollCommission");
                }
            }
        }
        public decimal HREmployeePayRollReward
        {
            get { return _hREmployeePayRollReward; }
            set
            {
                if (value != this._hREmployeePayRollReward)
                {
                    _hREmployeePayRollReward = value;
                    NotifyChanged("HREmployeePayRollReward");
                }
            }
        }
        public decimal HREmployeePayRollDiscipline
        {
            get { return _hREmployeePayRollDiscipline; }
            set
            {
                if (value != this._hREmployeePayRollDiscipline)
                {
                    _hREmployeePayRollDiscipline = value;
                    NotifyChanged("HREmployeePayRollDiscipline");
                }
            }
        }
        public decimal HREmployeePayRollAdvance
        {
            get { return _hREmployeePayRollAdvance; }
            set
            {
                if (value != this._hREmployeePayRollAdvance)
                {
                    _hREmployeePayRollAdvance = value;
                    NotifyChanged("HREmployeePayRollAdvance");
                }
            }
        }
        public decimal HREmployeePayRollTotalSalary
        {
            get { return _hREmployeePayRollTotalSalary; }
            set
            {
                if (value != this._hREmployeePayRollTotalSalary)
                {
                    _hREmployeePayRollTotalSalary = value;
                    NotifyChanged("HREmployeePayRollTotalSalary");
                }
            }
        }
        public String HREmployeePayRollComment
        {
            get { return _hREmployeePayRollComment; }
            set
            {
                if (value != this._hREmployeePayRollComment)
                {
                    _hREmployeePayRollComment = value;
                    NotifyChanged("HREmployeePayRollComment");
                }
            }
        }
        public String HREmployeeCardNumber
        {
            get { return _hREmployeeCardNumber; }
            set
            {
                if (value != this._hREmployeeCardNumber)
                {
                    _hREmployeeCardNumber = value;
                    NotifyChanged("HREmployeeCardNumber");
                }
            }
        }
        public int FK_HRDepartmentID
        {
            get { return _fK_HRDepartmentID; }
            set
            {
                if (value != this._fK_HRDepartmentID)
                {
                    _fK_HRDepartmentID = value;
                    NotifyChanged("FK_HRDepartmentID");
                }
            }
        }
        public decimal HREmployeeDaysPerMonth
        {
            get { return _hREmployeeDaysPerMonth; }
            set
            {
                if (value != this._hREmployeeDaysPerMonth)
                {
                    _hREmployeeDaysPerMonth = value;
                    NotifyChanged("HREmployeeDaysPerMonth");
                }
            }
        }
        public decimal HREmployeeRealDaysPerMonth
        {
            get { return _hREmployeeRealDaysPerMonth; }
            set
            {
                if (value != this._hREmployeeRealDaysPerMonth)
                {
                    _hREmployeeRealDaysPerMonth = value;
                    NotifyChanged("HREmployeeRealDaysPerMonth");
                }
            }
        }
        public decimal HREmployeeHoursOT
        {
            get { return _hREmployeeHoursOT; }
            set
            {
                if (value != this._hREmployeeHoursOT)
                {
                    _hREmployeeHoursOT = value;
                    NotifyChanged("HREmployeeHoursOT");
                }
            }
        }
        public decimal HREmployeeWorkingSlrAmtFull
        {
            get { return _hREmployeeWorkingSlrAmtFull; }
            set
            {
                if (value != this._hREmployeeWorkingSlrAmtFull)
                {
                    _hREmployeeWorkingSlrAmtFull = value;
                    NotifyChanged("HREmployeeWorkingSlrAmtFull");
                }
            }
        }
        public decimal HREmployeePieceworkSalary
        {
            get { return _hREmployeePieceworkSalary; }
            set
            {
                if (value != this._hREmployeePieceworkSalary)
                {
                    _hREmployeePieceworkSalary = value;
                    NotifyChanged("HREmployeePieceworkSalary");
                }
            }
        }
        public decimal HREmployeeOffsetSalary
        {
            get { return _hREmployeeOffsetSalary; }
            set
            {
                if (value != this._hREmployeeOffsetSalary)
                {
                    _hREmployeeOffsetSalary = value;
                    NotifyChanged("HREmployeeOffsetSalary");
                }
            }
        }
        public decimal HREmployeeLuongDaTru
        {
            get { return _hREmployeeLuongDaTru; }
            set
            {
                if (value != this._hREmployeeLuongDaTru)
                {
                    _hREmployeeLuongDaTru = value;
                    NotifyChanged("HREmployeeLuongDaTru");
                }
            }
        }
        public decimal HREmployeeNoLuyTien
        {
            get { return _hREmployeeNoLuyTien; }
            set
            {
                if (value != this._hREmployeeNoLuyTien)
                {
                    _hREmployeeNoLuyTien = value;
                    NotifyChanged("HREmployeeNoLuyTien");
                }
            }
        }
        public decimal HREmployeeSalaryFactor
        {
            get { return _hREmployeeSalaryFactor; }
            set
            {
                if (value != this._hREmployeeSalaryFactor)
                {
                    _hREmployeeSalaryFactor = value;
                    NotifyChanged("HREmployeeSalaryFactor");
                }
            }
        }
        public int FK_HRLevelID
        {
            get { return _fK_HRLevelID; }
            set
            {
                if (value != this._fK_HRLevelID)
                {
                    _fK_HRLevelID = value;
                    NotifyChanged("FK_HRLevelID");
                }
            }
        }
        public decimal HREmployeePayRollFuelTotalAmount
        {
            get { return _hREmployeePayRollFuelTotalAmount; }
            set
            {
                if (value != this._hREmployeePayRollFuelTotalAmount)
                {
                    _hREmployeePayRollFuelTotalAmount = value;
                    NotifyChanged("HREmployeePayRollFuelTotalAmount");
                }
            }
        }
        public decimal HREmployeePayRollBusAllowance
        {
            get { return _hREmployeePayRollBusAllowance; }
            set
            {
                if (value != this._hREmployeePayRollBusAllowance)
                {
                    _hREmployeePayRollBusAllowance = value;
                    NotifyChanged("HREmployeePayRollBusAllowance");
                }
            }
        }
        public decimal HREmployeePayRollEffectiveAllowance
        {
            get { return _hREmployeePayRollEffectiveAllowance; }
            set
            {
                if (value != this._hREmployeePayRollEffectiveAllowance)
                {
                    _hREmployeePayRollEffectiveAllowance = value;
                    NotifyChanged("HREmployeePayRollEffectiveAllowance");
                }
            }
        }
        public decimal HREmployeePayRollDiligenceAllowance
        {
            get { return _hREmployeePayRollDiligenceAllowance; }
            set
            {
                if (value != this._hREmployeePayRollDiligenceAllowance)
                {
                    _hREmployeePayRollDiligenceAllowance = value;
                    NotifyChanged("HREmployeePayRollDiligenceAllowance");
                }
            }
        }
        public decimal HREmployeePayRollHeavyToxicAllowance
        {
            get { return _hREmployeePayRollHeavyToxicAllowance; }
            set
            {
                if (value != this._hREmployeePayRollHeavyToxicAllowance)
                {
                    _hREmployeePayRollHeavyToxicAllowance = value;
                    NotifyChanged("HREmployeePayRollHeavyToxicAllowance");
                }
            }
        }
        public decimal HREmployeePayRollPerennialAllowance
        {
            get { return _hREmployeePayRollPerennialAllowance; }
            set
            {
                if (value != this._hREmployeePayRollPerennialAllowance)
                {
                    _hREmployeePayRollPerennialAllowance = value;
                    NotifyChanged("HREmployeePayRollPerennialAllowance");
                }
            }
        }
        public decimal HREmployeePayRollOtherAllowance
        {
            get { return _hREmployeePayRollOtherAllowance; }
            set
            {
                if (value != this._hREmployeePayRollOtherAllowance)
                {
                    _hREmployeePayRollOtherAllowance = value;
                    NotifyChanged("HREmployeePayRollOtherAllowance");
                }
            }
        }
        public decimal HREmployeePayRollWorkingSlrAmt
        {
            get { return _hREmployeePayRollWorkingSlrAmt; }
            set
            {
                if (value != this._hREmployeePayRollWorkingSlrAmt)
                {
                    _hREmployeePayRollWorkingSlrAmt = value;
                    NotifyChanged("HREmployeePayRollWorkingSlrAmt");
                }
            }
        }
        public decimal HREmployeePayRollContractSlrAmt
        {
            get { return _hREmployeePayRollContractSlrAmt; }
            set
            {
                if (value != this._hREmployeePayRollContractSlrAmt)
                {
                    _hREmployeePayRollContractSlrAmt = value;
                    NotifyChanged("HREmployeePayRollContractSlrAmt");
                }
            }
        }
        public decimal HREmployeePayRollHoursPerDay
        {
            get { return _hREmployeePayRollHoursPerDay; }
            set
            {
                if (value != this._hREmployeePayRollHoursPerDay)
                {
                    _hREmployeePayRollHoursPerDay = value;
                    NotifyChanged("HREmployeePayRollHoursPerDay");
                }
            }
        }
        public decimal HREmployeePayRollSalaryFactor
        {
            get { return _hREmployeePayRollSalaryFactor; }
            set
            {
                if (value != this._hREmployeePayRollSalaryFactor)
                {
                    _hREmployeePayRollSalaryFactor = value;
                    NotifyChanged("HREmployeePayRollSalaryFactor");
                }
            }
        }
        public decimal HREmployeePayRollDaysPerMonth
        {
            get { return _hREmployeePayRollDaysPerMonth; }
            set
            {
                if (value != this._hREmployeePayRollDaysPerMonth)
                {
                    _hREmployeePayRollDaysPerMonth = value;
                    NotifyChanged("HREmployeePayRollDaysPerMonth");
                }
            }
        }

        public decimal HREmployeePayrollNghiPhepNam
        {
            get { return _hREmployeePayrollNghiPhepNam; }
            set
            {
                if (value != this._hREmployeePayrollNghiPhepNam)
                {
                    _hREmployeePayrollNghiPhepNam = value;
                    NotifyChanged("HREmployeePayrollNghiPhepNam");
                }
            }
        }
        public decimal HREmployeePayrollNghiLe
        {
            get { return _hREmployeePayrollNghiLe; }
            set
            {
                if (value != this._hREmployeePayrollNghiLe)
                {
                    _hREmployeePayrollNghiLe = value;
                    NotifyChanged("HREmployeePayrollNghiLe");
                }
            }
        }
        public decimal HREmployeePayrollNghiCheDo
        {
            get { return _hREmployeePayrollNghiCheDo; }
            set
            {
                if (value != this._hREmployeePayrollNghiCheDo)
                {
                    _hREmployeePayrollNghiCheDo = value;
                    NotifyChanged("HREmployeePayrollNghiCheDo");
                }
            }
        }
        public decimal HREmployeePayrollNghiCupDien
        {
            get { return _hREmployeePayrollNghiCupDien; }
            set
            {
                if (value != this._hREmployeePayrollNghiCupDien)
                {
                    _hREmployeePayrollNghiCupDien = value;
                    NotifyChanged("HREmployeePayrollNghiCupDien");
                }
            }
        }
        public decimal HREmployeePayrollNghiPhep
        {
            get { return _hREmployeePayrollNghiPhep; }
            set
            {
                if (value != this._hREmployeePayrollNghiPhep)
                {
                    _hREmployeePayrollNghiPhep = value;
                    NotifyChanged("HREmployeePayrollNghiPhep");
                }
            }
        }
        public decimal HREmployeePayrollCtyChoNghi
        {
            get { return _hREmployeePayrollCtyChoNghi; }
            set
            {
                if (value != this._hREmployeePayrollCtyChoNghi)
                {
                    _hREmployeePayrollCtyChoNghi = value;
                    NotifyChanged("HREmployeePayrollCtyChoNghi");
                }
            }
        }
        public decimal HREmployeePayrollNghiKPhep
        {
            get { return _hREmployeePayrollNghiKPhep; }
            set
            {
                if (value != this._hREmployeePayrollNghiKPhep)
                {
                    _hREmployeePayrollNghiKPhep = value;
                    NotifyChanged("HREmployeePayrollNghiKPhep");
                }
            }
        }
        public decimal HREmployeePayrollBHTaiNan
        {
            get { return _hREmployeePayrollBHTaiNan; }
            set
            {
                if (value != this._hREmployeePayrollBHTaiNan)
                {
                    _hREmployeePayrollBHTaiNan = value;
                    NotifyChanged("HREmployeePayrollBHTaiNan");
                }
            }
        }
        public decimal HREmployeePayrollPhiTheTu
        {
            get { return _hREmployeePayrollPhiTheTu; }
            set
            {
                if (value != this._hREmployeePayrollPhiTheTu)
                {
                    _hREmployeePayrollPhiTheTu = value;
                    NotifyChanged("HREmployeePayrollPhiTheTu");
                }
            }
        }
        public decimal HREmployeePayrollPhiTheATM
        {
            get { return _hREmployeePayrollPhiTheATM; }
            set
            {
                if (value != this._hREmployeePayrollPhiTheATM)
                {
                    _hREmployeePayrollPhiTheATM = value;
                    NotifyChanged("HREmployeePayrollPhiTheATM");
                }
            }
        }
        public decimal HREmployeePayrollPhiAo
        {
            get { return _hREmployeePayrollPhiAo; }
            set
            {
                if (value != this._hREmployeePayrollPhiAo)
                {
                    _hREmployeePayrollPhiAo = value;
                    NotifyChanged("HREmployeePayrollPhiAo");
                }
            }
        }
        public decimal HREmployeePayrollTruKhac
        {
            get { return _hREmployeePayrollTruKhac; }
            set
            {
                if (value != this._hREmployeePayrollTruKhac)
                {
                    _hREmployeePayrollTruKhac = value;
                    NotifyChanged("HREmployeePayrollTruKhac");
                }
            }
        }
        public decimal HREmployeePayrollTruThueTNCN
        {
            get { return _hREmployeePayrollTruThueTNCN; }
            set
            {
                if (value != this._hREmployeePayrollTruThueTNCN)
                {
                    _hREmployeePayrollTruThueTNCN = value;
                    NotifyChanged("HREmployeePayrollTruThueTNCN");
                }
            }
        }
        public decimal HREmployeePayrollTongThuNhap
        {
            get { return _hREmployeePayrollTongThuNhap; }
            set
            {
                if (value != this._hREmployeePayrollTongThuNhap)
                {
                    _hREmployeePayrollTongThuNhap = value;
                    NotifyChanged("HREmployeePayrollTongThuNhap");
                }
            }
        }
        public decimal HREmployeePayrollTongCacKhoanTru
        {
            get { return _hREmployeePayrollTongCacKhoanTru; }
            set
            {
                if (value != this._hREmployeePayrollTongCacKhoanTru)
                {
                    _hREmployeePayrollTongCacKhoanTru = value;
                    NotifyChanged("HREmployeePayrollTongCacKhoanTru");
                }
            }
        }
        public decimal HREmployeePayRollEmployeeLoanMonthlyAmount
        {
            get { return _hREmployeePayRollEmployeeLoanMonthlyAmount; }
            set
            {
                if (value != this._hREmployeePayRollEmployeeLoanMonthlyAmount)
                {
                    _hREmployeePayRollEmployeeLoanMonthlyAmount = value;
                    NotifyChanged("HREmployeePayRollEmployeeLoanMonthlyAmount");
                }
            }
        }
        public decimal HREmployeePayRollOthersAllowance
        {
            get { return _hREmployeePayRollOthersAllowance; }
            set
            {
                if (value != this._hREmployeePayRollOthersAllowance)
                {
                    _hREmployeePayRollOthersAllowance = value;
                    NotifyChanged("HREmployeePayRollOthersAllowance");
                }
            }
        }
        public decimal HREmployeePayRollResponsibilityAllowance
        {
            get { return _hREmployeePayRollResponsibilityAllowance; }
            set
            {
                if (value != this._hREmployeePayRollResponsibilityAllowance)
                {
                    _hREmployeePayRollResponsibilityAllowance = value;
                    NotifyChanged("HREmployeePayRollResponsibilityAllowance");
                }
            }
        }
        public decimal HREmployeePayRollKPIAllowance
        {
            get { return _hREmployeePayRollKPIAllowance; }
            set
            {
                if (value != this._hREmployeePayRollKPIAllowance)
                {
                    _hREmployeePayRollKPIAllowance = value;
                    NotifyChanged("HREmployeePayRollKPIAllowance");
                }
            }
        }
        public decimal HREmployeePayRollProgressAllowance
        {
            get { return _hREmployeePayRollProgressAllowance; }
            set
            {
                if (value != this._hREmployeePayRollProgressAllowance)
                {
                    _hREmployeePayRollProgressAllowance = value;
                    NotifyChanged("HREmployeePayRollProgressAllowance");
                }
            }
        }
        public decimal HREmployeePayRollAllowance
        {
            get { return _hREmployeePayRollAllowance; }
            set
            {
                if (value != this._hREmployeePayRollAllowance)
                {
                    _hREmployeePayRollAllowance = value;
                    NotifyChanged("HREmployeePayRollAllowance");
                }
            }
        }
        public decimal HREmployeePayRollRewardTarget
        {
            get { return _hREmployeePayRollRewardTarget; }
            set
            {
                if (value != this._hREmployeePayRollRewardTarget)
                {
                    _hREmployeePayRollRewardTarget = value;
                    NotifyChanged("HREmployeePayRollRewardTarget");
                }
            }
        }
        public decimal HREmployeePayRollPercentAllowance
        {
            get { return _hREmployeePayRollPercentAllowance; }
            set
            {
                if (value != this._hREmployeePayRollPercentAllowance)
                {
                    _hREmployeePayRollPercentAllowance = value;
                    NotifyChanged("HREmployeePayRollPercentAllowance");
                }
            }
        }
        public decimal HREmployeePayRollAmountAllowance
        {
            get { return _hREmployeePayRollAmountAllowance; }
            set
            {
                if (value != this._hREmployeePayRollAmountAllowance)
                {
                    _hREmployeePayRollAmountAllowance = value;
                    NotifyChanged("HREmployeePayRollAmountAllowance");
                }
            }
        }
        public decimal HREmployeePayRollNgayNghiHuongLuong
        {
            get { return _hREmployeePayRollNgayNghiHuongLuong; }
            set
            {
                if (value != this._hREmployeePayRollNgayNghiHuongLuong)
                {
                    _hREmployeePayRollNgayNghiHuongLuong = value;
                    NotifyChanged("HREmployeePayRollNgayNghiHuongLuong");
                }
            }
        }
        public decimal HREmployeePayRollNgayNghiKhongLuong
        {
            get { return _hREmployeePayRollNgayNghiKhongLuong; }
            set
            {
                if (value != this._hREmployeePayRollNgayNghiKhongLuong)
                {
                    _hREmployeePayRollNgayNghiKhongLuong = value;
                    NotifyChanged("HREmployeePayRollNgayNghiKhongLuong");
                }
            }
        }
        public decimal HREmployeePayRollDayOT
        {
            get { return _hREmployeePayRollDayOT; }
            set
            {
                if (value != this._hREmployeePayRollDayOT)
                {
                    _hREmployeePayRollDayOT = value;
                    NotifyChanged("HREmployeePayRollDayOT");
                }
            }
        }
        public decimal HREmployeePayRollTongNgayCong
        {
            get { return _hREmployeePayRollTongNgayCong; }
            set
            {
                if (value != this._hREmployeePayRollTongNgayCong)
                {
                    _hREmployeePayRollTongNgayCong = value;
                    NotifyChanged("HREmployeePayRollTongNgayCong");
                }
            }
        }
        public decimal HREmployeePayRollSoLuongBoc
        {
            get { return _hREmployeePayRollSoLuongBoc; }
            set
            {
                if (value != this._hREmployeePayRollSoLuongBoc)
                {
                    _hREmployeePayRollSoLuongBoc = value;
                    NotifyChanged("HREmployeePayRollSoLuongBoc");
                }
            }
        }
        public decimal HREmployeePayRollLuongThang
        {
            get { return _hREmployeePayRollLuongThang; }
            set
            {
                if (value != this._hREmployeePayRollLuongThang)
                {
                    _hREmployeePayRollLuongThang = value;
                    NotifyChanged("HREmployeePayRollLuongThang");
                }
            }
        }
        public decimal HREmployeePayRollAllowanceGasoline
        {
            get { return _hREmployeePayRollAllowanceGasoline; }
            set
            {
                if (value != this._hREmployeePayRollAllowanceGasoline)
                {
                    _hREmployeePayRollAllowanceGasoline = value;
                    NotifyChanged("HREmployeePayRollAllowanceGasoline");
                }
            }
        }
        public decimal HREmployeePayRollAllowanceMotel
        {
            get { return _hREmployeePayRollAllowanceMotel; }
            set
            {
                if (value != this._hREmployeePayRollAllowanceMotel)
                {
                    _hREmployeePayRollAllowanceMotel = value;
                    NotifyChanged("HREmployeePayRollAllowanceMotel");
                }
            }
        }
        public decimal HREmployeePayRollLate
        {
            get { return _hREmployeePayRollLate; }
            set
            {
                if (value != this._hREmployeePayRollLate)
                {
                    _hREmployeePayRollLate = value;
                    NotifyChanged("HREmployeePayRollLate");
                }
            }
        }
        public decimal HREmployeePayRollPurchaseOrder
        {
            get { return _hREmployeePayRollPurchaseOrder; }
            set
            {
                if (value != this._hREmployeePayRollPurchaseOrder)
                {
                    _hREmployeePayRollPurchaseOrder = value;
                    NotifyChanged("HREmployeePayRollPurchaseOrder");
                }
            }
        }
        public decimal HREmployeePayRollAllowanceRise
        {
            get { return _hREmployeePayRollAllowanceRise; }
            set
            {
                if (value != this._hREmployeePayRollAllowanceRise)
                {
                    _hREmployeePayRollAllowanceRise = value;
                    NotifyChanged("HREmployeePayRollAllowanceRise");
                }
            }
        }
        public decimal HREmployeeRealNightsPerMonth
        {
            get { return _hREmployeeRealNightsPerMonth; }
            set
            {
                if (value != this._hREmployeeRealNightsPerMonth)
                {
                    _hREmployeeRealNightsPerMonth = value;
                    NotifyChanged("HREmployeeRealNightsPerMonth");
                }
            }
        }
        public decimal HREmployeePayRollAllowaceNight
        {
            get { return _hREmployeePayRollAllowaceNight; }
            set
            {
                if (value != this._hREmployeePayRollAllowaceNight)
                {
                    _hREmployeePayRollAllowaceNight = value;
                    NotifyChanged("HREmployeePayRollAllowaceNight");
                }
            }
        }
        public decimal HREmployeePayRollAllowanceVehicleMaintenance
        {
            get { return _hREmployeePayRollAllowanceVehicleMaintenance; }
            set
            {
                if (value != this._hREmployeePayRollAllowanceVehicleMaintenance)
                {
                    _hREmployeePayRollAllowanceVehicleMaintenance = value;
                    NotifyChanged("HREmployeePayRollAllowanceVehicleMaintenance");
                }
            }
        }
        public decimal HREmployeePayRollProbationaryExtraSalary
        {
            get { return _hREmployeePayRollProbationaryExtraSalary; }
            set
            {
                if (value != this._hREmployeePayRollProbationaryExtraSalary)
                {
                    _hREmployeePayRollProbationaryExtraSalary = value;
                    NotifyChanged("HREmployeePayRollProbationaryExtraSalary");
                }
            }
        }
        public decimal HREmployeePayRollAllowanceWorkSchedule
        {
            get { return _hREmployeePayRollAllowanceWorkSchedule; }
            set
            {
                if (value != this._hREmployeePayRollAllowanceWorkSchedule)
                {
                    _hREmployeePayRollAllowanceWorkSchedule = value;
                    NotifyChanged("HREmployeePayRollAllowanceWorkSchedule");
                }
            }
        }
        public decimal HREmployeePayRollProbationaryRealDaysPerMonth
        {
            get { return _hREmployeePayRollProbationaryRealDaysPerMonth; }
            set
            {
                if (value != this._hREmployeePayRollProbationaryRealDaysPerMonth)
                {
                    _hREmployeePayRollProbationaryRealDaysPerMonth = value;
                    NotifyChanged("HREmployeePayRollProbationaryRealDaysPerMonth");
                }
            }
        }
        public decimal HREmployeePayRollApprenticeRealDaysPerMonth
        {
            get { return _hREmployeePayRollApprenticeRealDaysPerMonth; }
            set
            {
                if (value != this._hREmployeePayRollApprenticeRealDaysPerMonth)
                {
                    _hREmployeePayRollApprenticeRealDaysPerMonth = value;
                    NotifyChanged("HREmployeePayRollApprenticeRealDaysPerMonth");
                }
            }
        }
        public decimal HREmployeePayRollProbationarySalaryAmount
        {
            get { return _hREmployeePayRollProbationarySalaryAmount; }
            set
            {
                if (value != this._hREmployeePayRollProbationarySalaryAmount)
                {
                    _hREmployeePayRollProbationarySalaryAmount = value;
                    NotifyChanged("HREmployeePayRollProbationarySalaryAmount");
                }
            }
        }
        public decimal HREmployeePayRollApprenticeSalaryAmount
        {
            get { return _hREmployeePayRollApprenticeSalaryAmount; }
            set
            {
                if (value != this._hREmployeePayRollApprenticeSalaryAmount)
                {
                    _hREmployeePayRollApprenticeSalaryAmount = value;
                    NotifyChanged("HREmployeePayRollApprenticeSalaryAmount");
                }
            }
        }
        public decimal HREmployeePayRollSubtractLateAmount
        {
            get { return _hREmployeePayRollSubtractLateAmount; }
            set
            {
                if (value != this._hREmployeePayRollSubtractLateAmount)
                {
                    _hREmployeePayRollSubtractLateAmount = value;
                    NotifyChanged("HREmployeePayRollSubtractLateAmount");
                }
            }
        }
        public decimal HREmployeePayRollSubtractPhoneAmount
        {
            get { return _hREmployeePayRollSubtractPhoneAmount; }
            set
            {
                if (value != this._hREmployeePayRollSubtractPhoneAmount)
                {
                    _hREmployeePayRollSubtractPhoneAmount = value;
                    NotifyChanged("HREmployeePayRollSubtractPhoneAmount");
                }
            }
        }
        public String HREmployeePayRollWarning
        {
            get { return _hREmployeePayRollWarning; }
            set
            {
                if (value != this._hREmployeePayRollWarning)
                {
                    _hREmployeePayRollWarning = value;
                    NotifyChanged("HREmployeePayRollWarning");
                }
            }
        }
        public decimal HREmployeePayRollProvinceAllowance
        {
            get { return _hREmployeePayRollProvinceAllowance; }
            set
            {
                if (value != this._hREmployeePayRollProvinceAllowance)
                {
                    _hREmployeePayRollProvinceAllowance = value;
                    NotifyChanged("HREmployeePayRollProvinceAllowance");
                }
            }
        }
        public String FK_HREmployeePayRollKPI
        {
            get { return _fK_HREmployeePayRollKPI; }
            set
            {
                if (value != this._fK_HREmployeePayRollKPI)
                {
                    _fK_HREmployeePayRollKPI = value;
                    NotifyChanged("FK_HREmployeePayRollKPI");
                }
            }
        }
        public String FK_HREmployeePayRollAllowance
        {
            get { return _fK_HREmployeePayRollAllowance; }
            set
            {
                if (value != this._fK_HREmployeePayRollAllowance)
                {
                    _fK_HREmployeePayRollAllowance = value;
                    NotifyChanged("FK_HREmployeePayRollAllowance");
                }
            }
        }
        public String FK_HREmployeePayRollDiscipline
        {
            get { return _fK_HREmployeePayRollDiscipline; }
            set
            {
                if (value != this._fK_HREmployeePayRollDiscipline)
                {
                    _fK_HREmployeePayRollDiscipline = value;
                    NotifyChanged("FK_HREmployeePayRollDiscipline");
                }
            }
        }
        public String FK_HREmployeePayRollPieceWage
        {
            get { return _fK_HREmployeePayRollPieceWage; }
            set
            {
                if (value != this._fK_HREmployeePayRollPieceWage)
                {
                    _fK_HREmployeePayRollPieceWage = value;
                    NotifyChanged("FK_HREmployeePayRollPieceWage");
                }
            }
        }
        public decimal HREmployeePayRollSocialInsDNAmount
        {
            get { return _hREmployeePayRollSocialInsDNAmount; }
            set
            {
                if (value != this._hREmployeePayRollSocialInsDNAmount)
                {
                    _hREmployeePayRollSocialInsDNAmount = value;
                    NotifyChanged("HREmployeePayRollSocialInsDNAmount");
                }
            }
        }
        public decimal HREmployeePayRollHealthInsDNAmount
        {
            get { return _hREmployeePayRollHealthInsDNAmount; }
            set
            {
                if (value != this._hREmployeePayRollHealthInsDNAmount)
                {
                    _hREmployeePayRollHealthInsDNAmount = value;
                    NotifyChanged("HREmployeePayRollHealthInsDNAmount");
                }
            }
        }
        public decimal HREmployeePayRollOutOfWorkInsDNAmount
        {
            get { return _hREmployeePayRollOutOfWorkInsDNAmount; }
            set
            {
                if (value != this._hREmployeePayRollOutOfWorkInsDNAmount)
                {
                    _hREmployeePayRollOutOfWorkInsDNAmount = value;
                    NotifyChanged("HREmployeePayRollOutOfWorkInsDNAmount");
                }
            }
        }
        public String FK_HREmployeePayRollAdvanceRequestItemLoanDetails
        {
            get { return _fK_HREmployeePayRollAdvanceRequestItemLoanDetails; }
            set
            {
                if (value != this._fK_HREmployeePayRollAdvanceRequestItemLoanDetails)
                {
                    _fK_HREmployeePayRollAdvanceRequestItemLoanDetails = value;
                    NotifyChanged("FK_HREmployeePayRollAdvanceRequestItemLoanDetails");
                }
            }
        }
        public decimal HREmployeePayRollTaxableIncomeLevel
        {
            get { return _hREmployeePayRollTaxableIncomeLevel; }
            set
            {
                if (value != this._hREmployeePayRollTaxableIncomeLevel)
                {
                    _hREmployeePayRollTaxableIncomeLevel = value;
                    NotifyChanged("HREmployeePayRollTaxableIncomeLevel");
                }
            }
        }
        public decimal HREmployeePayRollPersonalIncomeTax
        {
            get { return _hREmployeePayRollPersonalIncomeTax; }
            set
            {
                if (value != this._hREmployeePayRollPersonalIncomeTax)
                {
                    _hREmployeePayRollPersonalIncomeTax = value;
                    NotifyChanged("HREmployeePayRollPersonalIncomeTax");
                }
            }
        }
        public String HREmployeePayRollNoteOT
        {
            get { return _hREmployeePayRollNoteOT; }
            set
            {
                if (value != this._hREmployeePayRollNoteOT)
                {
                    _hREmployeePayRollNoteOT = value;
                    NotifyChanged("HREmployeePayRollNoteOT");
                }
            }
        }
        public decimal HREmployeePayRollResponsibilityCommodityAllowance
        {
            get { return _hREmployeePayRollResponsibilityCommodityAllowance; }
            set
            {
                if (value != this._hREmployeePayRollResponsibilityCommodityAllowance)
                {
                    _hREmployeePayRollResponsibilityCommodityAllowance = value;
                    NotifyChanged("HREmployeePayRollResponsibilityCommodityAllowance");
                }
            }
        }
        public decimal HREmployeeBasicSalary
        {
            get { return _hREmployeeBasicSalary; }
            set
            {
                if (value != this._hREmployeeBasicSalary)
                {
                    _hREmployeeBasicSalary = value;
                    NotifyChanged("HREmployeeBasicSalary");
                }
            }
        }
        public decimal HREmployeePayRollDaysOffAmount
        {
            get { return _hREmployeePayRollDaysOffAmount; }
            set
            {
                if (value != this._hREmployeePayRollDaysOffAmount)
                {
                    _hREmployeePayRollDaysOffAmount = value;
                    NotifyChanged("HREmployeePayRollDaysOffAmount");
                }
            }
        }
        public decimal HREmployeePayRollTheChan
        {
            get { return _hREmployeePayRollTheChan; }
            set
            {
                if (value != this._hREmployeePayRollTheChan)
                {
                    _hREmployeePayRollTheChan = value;
                    NotifyChanged("HREmployeePayRollTheChan");
                }
            }
        }
        public decimal HREmployeePayRollOtherReward
        {
            get { return _hREmployeePayRollOtherReward; }
            set
            {
                if (value != this._hREmployeePayRollOtherReward)
                {
                    _hREmployeePayRollOtherReward = value;
                    NotifyChanged("HREmployeePayRollOtherReward");
                }
            }
        }
        public decimal HREmployeePayRollBackTheChan
        {
            get { return _hREmployeePayRollBackTheChan; }
            set
            {
                if (value != this._hREmployeePayRollBackTheChan)
                {
                    _hREmployeePayRollBackTheChan = value;
                    NotifyChanged("HREmployeePayRollBackTheChan");
                }
            }
        }
        public decimal HREmployeePayrollNghiLeAmount
        {
            get { return _hREmployeePayrollNghiLeAmount; }
            set
            {
                if (value != this._hREmployeePayrollNghiLeAmount)
                {
                    _hREmployeePayrollNghiLeAmount = value;
                    NotifyChanged("HREmployeePayrollNghiLeAmount");
                }
            }
        }

        #endregion

        #region Extra Property
        public String HREmployeeNo { get; set; }
        public String HREmployeeName { get; set; }
        public String HRDepartmentRoomNo { get; set; }
        public String HRDepartmentRoomName { get; set; }
        public String HRDepartmentName { get; set; }
        public string HRLevelName { get; set; }
        public string HREmployeeStatusCombo { get; set; }
        public string HREmployeeWorkingForm { get; set; }

        public String HREmployeeBranchName { get; set; }
        public String HREmployeeBranchAddress { get; set; }
        public String HREmployeeBranchSDT { get; set; }
        public String HREmployeeCompanyName { get; set; }
        public String HREmployeePayRollDateTitle { get; set; }
        public String HREmployeePayRollDateSign { get; set; }
        public decimal HREmployeePayRollCongLamViec { get; set; }
        public decimal HREmployeeLuongCoBan { get; set; }
        public decimal HREmployeePayRollDonGiaLuongKhoan { get; set; }
        public decimal HREmployeePayRollMucKPI { get; set; }
        public int HREmployeePayRollThamNien { get; set; }

        public String HREmployeeBankAccount1 { get; set; }

        public decimal OTFactory1 { get; set; }
        public decimal OTFactory2 { get; set; }
        public decimal OTFactory3 { get; set; }
        public decimal OTFactory4 { get; set; }
        public decimal OTFactory5 { get; set; }
        public decimal OTFactory6 { get; set; }

        public decimal OTValue1 { get; set; }
        public decimal OTValue2 { get; set; }
        public decimal OTValue3 { get; set; }
        public decimal OTValue4 { get; set; }
        public decimal OTValue5 { get; set; }
        public decimal OTValue6 { get; set; }

        //public String HREmployeeCardNumber { get; set; }

        //public double HREmployeeDaysPerMonth { get; set; }
        //public double HREmployeeRealDaysPerMonth { get; set; }
        //public double HREmployeeHoursOT { get; set; }

        public decimal HREmployeeWorkingSlrAmt { get; set; }

        public decimal HREmployeeContractSlrAmt { get; set; }
        public decimal HREmployeePayRollEffectiveAllowanceFactor { get; set; }
        //[FormatGroup(FormatGroupAttribute.cstFormatGroupPrice)]
        //public double HREmployeeWorkingSlrAmtFull { get; set; }

        //[FormatGroup(FormatGroupAttribute.cstFormatGroupPrice)]
        //public double HREmployeePieceworkSalary { get; set; }

        //[FormatGroup(FormatGroupAttribute.cstFormatGroupPrice)]
        //public double HREmployeeOffsetSalary { get; set; }

        //[FormatGroup(FormatGroupAttribute.cstFormatGroupPrice)]
        //public double HREmployeeLuongDaTru { get; set; }

        //[FormatGroup(FormatGroupAttribute.cstFormatGroupPrice)]
        //public double HREmployeeNoLuyTien { get; set; }

        //public decimal HREmployeeSalaryFactor { get; set; }

        public decimal HREmployeePayRollTotalWorkingSalary { get; set; }

        public decimal HREmployeePayRollIncomeTaxAmt { get; set; }

        public decimal HREmployeePayRollTotalInsAmt { get; set; }

        public decimal HREmployeePayRollTotalDeductedAmt { get; set; }

        public decimal HREmployeeSocialInsPaymentPercent { get; set; }
        public decimal HREmployeeHealthInsPaymentPercent { get; set; }
        public decimal HREmployeeOutOfWorkInsPaymentPercent { get; set; }
        public decimal HREmployeeTaxPaymentPercent { get; set; }

        public decimal HREmployeePayRollTotalAddAmt { get; set; }

        public decimal HREmployeePayRollTotalIncome { get; set; }

        public decimal HREmployeePayRollBussinessSocialInsAmount { get; set; }
        public decimal HREmployeePayRollBussinessHealthInsAmount { get; set; }
        public decimal HREmployeePayRollBussinessOutOfWorkInsAmount { get; set; }

        public decimal HREmployeePayRollBusinessSyndicateFee { get; set; }

        public decimal HREmployeePayRollInsSalary { get; set; }

        public DateTime HRPayRollDate { get; set; }

        public List<HREmployeePayrollDetailsInfo> HREmployeePayrollDetailsList { get; set; }

        public decimal HREmployeePayRollCongChuyenCan { get; set; }
        public int FK_HRDepartmentRoomGroupItemID { get; set; }

        public decimal HREmployeeRealDaysPerMonthBackup { get; set; }

        public decimal HREmployeePayRollTongPhuCap { get; set; }
        public decimal HREmployeePayRollTongTienThuong { get; set; }

        public decimal HREmployeePayRollValidateTienThuongKPI { get; set; }
        public decimal HREmployeePayRollValidateTienThuongResult { get; set; }
        public string HREmployeePayRollValidateComment { get; set; }
        public decimal HREmployeePayRollValidateSoTienThuong { get; set; }
        public DateTime HREmployeePayRollValidateDate { get; set; }
        public decimal HREmployeePayRollValidateSoTienPhat { get; set; }
        public int FK_HREmployeeValidateBranchID { get; set; }
        public decimal HREmployeePayRollValidateSoLuongBoc { get; set; }
        public decimal HREmployeePayRollValidateLuongKhoan { get; set; }

        public int FK_BRBranchID { get; set; }
        public decimal HREmployeePayRollGTTTNCN { get; set; }
        public decimal HREmployeePayRollPersonalIncome { get; set; }
        public decimal DetailAmount { get; set; }

        public decimal HREmployeePayRollTongKhenThuong { get; set; }

        public List<HRTimeSheetEntrysInfo> HRTimeSheetEntrysList { get; set; }
        public decimal HREmployeePayRollTongCongKhac { get; set; }

        public decimal HREmployeePayRollTongGioTangCa { get; set; }
        #endregion
    }
    #endregion
}