using System;
using System.Text;
using System.Collections.Generic;
using VinaLib;
namespace VinaERP
{
    #region HREmployeeWorkSchedules
    //-----------------------------------------------------------
    //Generated By: Vina Studio
    //Class:HREmployeeWorkSchedulesInfo
    //Created Date:Tuesday, June 14, 2016
    //-----------------------------------------------------------

    public class HREmployeeWorkSchedulesInfo : BusinessObject
    {
        public HREmployeeWorkSchedulesInfo()
        {
        }
        #region Variables
        protected int _hREmployeeWorkScheduleID;
        protected String _aAStatus = DefaultAAStatus;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected String _aACreatedUser = String.Empty;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected String _aAUpdatedUser = String.Empty;
        protected String _hREmployeeWorkScheduleNo = String.Empty;
        protected String _hREmployeeWorkScheduleName = String.Empty;
        protected String _hREmployeeWorkScheduleDesc = String.Empty;
        protected DateTime _hREmployeeWorkScheduleDateFrom = DateTime.MaxValue;
        protected DateTime _hREmployeeWorkScheduleDateTo = DateTime.MaxValue;
        protected int _fK_BRBranchID;
        protected String _hREmployeeCardNumber = String.Empty;
        protected String _hREmployeeName = String.Empty;
        protected String _hREmployeeWorkScheduleStatus = DefaultStatus;

        #endregion

        #region Public properties
        public int HREmployeeWorkScheduleID
        {
            get { return _hREmployeeWorkScheduleID; }
            set
            {
                if (value != this._hREmployeeWorkScheduleID)
                {
                    _hREmployeeWorkScheduleID = value;
                    NotifyChanged("HREmployeeWorkScheduleID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                    NotifyChanged("AACreatedDate");
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                    NotifyChanged("AACreatedUser");
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                    NotifyChanged("AAUpdatedDate");
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                    NotifyChanged("AAUpdatedUser");
                }
            }
        }
        public String HREmployeeWorkScheduleNo
        {
            get { return _hREmployeeWorkScheduleNo; }
            set
            {
                if (value != this._hREmployeeWorkScheduleNo)
                {
                    _hREmployeeWorkScheduleNo = value;
                    NotifyChanged("HREmployeeWorkScheduleNo");
                }
            }
        }
        public String HREmployeeWorkScheduleName
        {
            get { return _hREmployeeWorkScheduleName; }
            set
            {
                if (value != this._hREmployeeWorkScheduleName)
                {
                    _hREmployeeWorkScheduleName = value;
                    NotifyChanged("HREmployeeWorkScheduleName");
                }
            }
        }
        public String HREmployeeWorkScheduleDesc
        {
            get { return _hREmployeeWorkScheduleDesc; }
            set
            {
                if (value != this._hREmployeeWorkScheduleDesc)
                {
                    _hREmployeeWorkScheduleDesc = value;
                    NotifyChanged("HREmployeeWorkScheduleDesc");
                }
            }
        }
        public DateTime HREmployeeWorkScheduleDateFrom
        {
            get { return _hREmployeeWorkScheduleDateFrom; }
            set
            {
                if (value != this._hREmployeeWorkScheduleDateFrom)
                {
                    _hREmployeeWorkScheduleDateFrom = value;
                    NotifyChanged("HREmployeeWorkScheduleDateFrom");
                }
            }
        }
        public DateTime HREmployeeWorkScheduleDateTo
        {
            get { return _hREmployeeWorkScheduleDateTo; }
            set
            {
                if (value != this._hREmployeeWorkScheduleDateTo)
                {
                    _hREmployeeWorkScheduleDateTo = value;
                    NotifyChanged("HREmployeeWorkScheduleDateTo");
                }
            }
        }
        public int FK_BRBranchID
        {
            get { return _fK_BRBranchID; }
            set
            {
                if (value != this._fK_BRBranchID)
                {
                    _fK_BRBranchID = value;
                    NotifyChanged("FK_BRBranchID");
                }
            }
        }
        public String HREmployeeCardNumber
        {
            get { return _hREmployeeCardNumber; }
            set
            {
                if (value != this._hREmployeeCardNumber)
                {
                    _hREmployeeCardNumber = value;
                    NotifyChanged("HREmployeeCardNumber");
                }
            }
        }
        public String HREmployeeName
        {
            get { return _hREmployeeName; }
            set
            {
                if (value != this._hREmployeeName)
                {
                    _hREmployeeName = value;
                    NotifyChanged("HREmployeeName");
                }
            }
        }
        public String HREmployeeWorkScheduleStatus
        {
            get { return _hREmployeeWorkScheduleStatus; }
            set
            {
                if (value != this._hREmployeeWorkScheduleStatus)
                {
                    _hREmployeeWorkScheduleStatus = value;
                    NotifyChanged("HREmployeeWorkScheduleStatus");
                }
            }
        }

        #endregion
        #region Extra Properties
        public DateTime HREmployeeWorkScheduleFromDate { get; set; }
        public DateTime HREmployeeWorkScheduleToDate { get; set; }
        public int FK_HREmployeeID { get; set; }
        #endregion
    }
    #endregion
}