using System;
using System.Text;
using System.Collections.Generic;
using VinaLib;
using System.Drawing;

namespace VinaERP
{
    #region HREmployees
    //-----------------------------------------------------------
    //Generated By: Vina Studio
    //Class:HREmployeesInfo
    //Created Date:Thursday, March 18, 2010
    //-----------------------------------------------------------

    public class HREmployeesInfo : BusinessObject
    {
        public HREmployeesInfo()
        {
            HREmployeeDob = DateTime.Now;
            HREmployeeStartWorkingDate = DateTime.Now;
            HREmployeeHealthInsRegisteredDate = DateTime.Now;
            HREmployeeIDCardDate = DateTime.Now;
            HREmployeePassportIssuedDate = DateTime.Now;
            HREmployeePassportIssuedPlace = DateTime.Now;
            HREmployeeEndWorkingDate = DateTime.Now;
            HREmployeeSocialInsRegisteredDate = DateTime.Now;
            HREmployeeHealthInsExpiryDate = DateTime.Now;
            HREmployeeIsBoD = false;
        }

        #region Variables
        protected int _hREmployeeID;
        protected String _aAStatus = DefaultAAStatus;
        protected String _aACreatedUser = String.Empty;
        protected String _aAUpdatedUser = String.Empty;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected bool _isTransferred = true;
        protected DateTime _aATransferredDate = DateTime.MaxValue;
        protected int _fK_HRDepartmentID;
        protected int _fK_HRDepartmentRoomID;
        protected int _fK_HRLevelID;
        protected int _fK_HRTimeSheetScaleID;
        protected int _fK_BRBranchID;
        protected String _hREmployeeNo = String.Empty;
        protected String _hREmployeeName = String.Empty;
        protected String _hREmployeeGenderCombo = String.Empty;
        protected DateTime _hREmployeeDob = DateTime.MaxValue;
        protected String _hREmployeeBirthPlace = String.Empty;
        protected String _hREmployeeTypeCombo = String.Empty;
        protected String _hREmployeeStatusCombo = DefaultStatus;
        protected String _hREmployeeDesc = String.Empty;
        protected byte[] _hREmployeePicture;
        protected String _hREmployeeIDNumber = String.Empty;
        protected String _hREmployeeIDCardPlace = String.Empty;
        protected DateTime _hREmployeeIDCardDate = DateTime.MaxValue;
        protected String _hREmployeeCardNumber = String.Empty;
        protected String _hREmployeePassportNo = String.Empty;
        protected DateTime _hREmployeePassportIssuedDate = DateTime.MaxValue;
        protected DateTime _hREmployeePassportIssuedPlace = DateTime.MaxValue;
        protected String _hREmployeeSlrPmtMthdCombo = String.Empty;
        protected decimal _hREmployeeWorkingSlrAmt;
        protected decimal _hREmployeeContractSlrAmt;
        protected String _hREmployeeReligion = String.Empty;
        protected String _hREmployeeTaxNumber = String.Empty;
        protected bool _hREmployeeActiveCheck = true;
        protected DateTime _hREmployeeStartWorkingDate = DateTime.MaxValue;
        protected DateTime _hREmployeeEndWorkingDate = DateTime.MaxValue;
        protected DateTime _hREmployeeStartWorkingTime = DateTime.MaxValue;
        protected DateTime _hREmployeeEndWorkingTime = DateTime.MaxValue;
        protected String _hREmployeeTel1 = String.Empty;
        protected String _hREmployeeTel2 = String.Empty;
        protected String _hREmployeeTel3 = String.Empty;
        protected String _hREmployeeEmail1 = String.Empty;
        protected String _hREmployeePassword1 = String.Empty;
        protected String _hREmployeeEmail2 = String.Empty;
        protected String _hREmployeeFax = String.Empty;
        protected String _hREmployeeContactAddressStreet = String.Empty;
        protected String _hREmployeeContactAddressLine1 = String.Empty;
        protected String _hREmployeeContactAddressLine2 = String.Empty;
        protected String _hREmployeeContactAddressLine3 = String.Empty;
        protected String _hREmployeeContactAddressCity = String.Empty;
        protected String _hREmployeeContactAddressPostalCode = String.Empty;
        protected String _hREmployeeContactAddressStateProvince = String.Empty;
        protected String _hREmployeeContactAddressZipCode = String.Empty;
        protected String _hREmployeeContactAddressCountry = String.Empty;
        protected String _hREmployeeBankCode = String.Empty;
        protected String _hREmployeeBankName = String.Empty;
        protected String _hREmployeeBankAccount1 = String.Empty;
        protected int _hREmployeeBankAccountCurrency1;
        protected String _hREmployeeBankAccount2 = String.Empty;
        protected int _hREmployeeBankAccountCurrency2;
        protected String _hREmployeeBankAccount3 = String.Empty;
        protected int _hREmployeeBankAccountCurrency3;
        protected String _hREmployeeBankAccount4 = String.Empty;
        protected int _hREmployeeBankAccountCurrency4;
        protected String _hRInsCalculatedSalaryType = String.Empty;
        protected String _hREmployeeSocialInsNo = String.Empty;
        protected DateTime _hREmployeeSocialInsRegisteredDate = DateTime.MaxValue;
        protected DateTime _hREmployeeSocialInsExpiryDate = DateTime.MaxValue;
        protected decimal _hREmployeeSocialInsPaymentPercent;
        protected String _hREmployeeHealthInsNo = String.Empty;
        protected String _hREmployeeHealthInsRegisteredPlace = String.Empty;
        protected DateTime _hREmployeeHealthInsRegisteredDate = DateTime.MaxValue;
        protected DateTime _hREmployeeHealthInsExpiryDate = DateTime.MaxValue;
        protected decimal _hREmployeeHealthInsPaymentPercent;
        protected decimal _hREmployeeOutOfWorkInsPaymentPercent;
        protected decimal _hREmployeeSyndicatePaymentPercent;
        protected decimal _hREmployeeTaxPaymentPercent;
        protected decimal _hREmployeeSalaryFactor;
        protected decimal _hREmployeeExtraSalary1;
        protected decimal _hREmployeeExtraSalary2;
        protected decimal _hREmployeeExtraSalary3;
        protected decimal _hREmployeeExtraSalary4;
        protected String _hRPayRollCalculatedSalaryType = String.Empty;
        protected decimal _hREmployeeHoursPerDay;
        protected decimal _hREmployeeDaysPerMonth;
        protected decimal _hREmployeeWorkingHourlySalary;
        protected decimal _hREmployeeWorkingDailySalary;
        protected decimal _hREmployeeContractHourlySalary;
        protected decimal _hREmployeeContractDailySalary;
        protected int _fK_HREmployeePayrollFormulaID;
        protected int _fK_GENativeStateProvinceID;
        protected String _hREmployeeMaritalStatusCombo = DefaultStatus;
        protected String _hREmployeeEducation = String.Empty;
        protected int _fK_GEIDCardStateProvinceID;
        protected int _fK_GENationalityID;
        protected int _fK_GEReligionID;
        protected int _fK_GEStateProvinceIDBHXH;
        protected decimal _hREmployeeWorkingMonths;
        protected bool _hREmployeeUniform = true;
        protected String _hREmployeeDobString = String.Empty;
        protected int _hREmployeeProbationaryMonth;
        protected DateTime _hREmployeeStopWorkingDate = DateTime.MaxValue;
        protected decimal _hREmployeeLeaveDays;
        protected decimal _hREmployeeSyndicatePaymentAmount;
        protected bool _hREmployeeIsUnionMember = true;
        protected decimal _hREmployeeUnionMemberFee;
        protected int _fK_HRDepartmentRoomGroupItemID;
        protected String _hREmployeeTrainingCourseID = String.Empty;
        protected String _hREmployeeTrainingCourseValue = String.Empty;
        protected int _hREmployeeAnnualLeaveRemain;
        protected String _hREmployeePictureFileName = String.Empty;
        protected int _fK_ACAccountDepositID;
        protected int _fK_ACAccountPurchaseID;
        protected int _fK_ACAccountSaleID;
        protected String _hREmployeeFirstName = String.Empty;
        protected String _hREmployeeLastName = String.Empty;
        protected int _fK_ADPortalUserID;
        protected decimal _hREmployeeAllowanceResponsibility;
        protected decimal _hREmployeeAllowanceKPI;
        protected decimal _hREmployeeAllowanceResponsibility2;
        protected decimal _hREmployeeAllowanceProgress;
        protected String _hREmployeeLocationIssuedRecord = String.Empty;
        protected bool _hREmployeeHasSocialInsurance = true;
        protected DateTime _hREmployeeProbationaryStartDate = DateTime.MaxValue;
        protected DateTime _hREmployeeProbationaryEndDate = DateTime.MaxValue;
        protected decimal _hREmployeeProbationarySalaryAmount;
        protected decimal _hREmployeeProbationaryExtraSalary;
        protected String _hREmployeeProbationaryType = String.Empty;
        protected int _fK_HRConfigRankID;
        protected int _fK_HRConfigScaleID;
        protected int _fK_ADWorkingShiftID;
        protected String _hREmployeePayRollCalculatedWorkType = String.Empty;
        protected DateTime _hREmployeeApprenticeStartDate = DateTime.MaxValue;
        protected DateTime _hREmployeeApprenticeEndDate = DateTime.MaxValue;
        protected decimal _hREmployeeApprenticeSalaryAmount;
        protected decimal _hREmployeeAllowanceVehicleMaintenance;
        protected String _hREmployeeBankNo = String.Empty;
        protected bool _hREmployeePartyMember = false;
        protected int _fK_ACCostCenterID;
        protected String _hREmployeeWorkingForm = String.Empty;
        protected decimal _hREmployeeSocialInsPaymentPercentDN;
        protected decimal _hREmployeeHealthInsPaymentPercentDN;
        protected decimal _hREmployeeOutOfWorkInsPaymentPercentDN;
        protected decimal _hREmployeeAllowanceDiligence;
        protected decimal _hREmployeeAllowanceGasoline;
        protected decimal _hREmployeeAllowanceMotel;
        protected decimal _hREmployeeWorkingSlrAmtDate;
        protected decimal _hREmployeePieceWage;
        protected decimal _hREmployeeSocialInsPaymentAmount;
        protected decimal _hREmployeeHealthInsPaymentAmount;
        protected decimal _hREmployeeOutOfWorkInsPaymentAmount;
        protected decimal _hREmployeeSocialInsPaymentAmountDN;
        protected decimal _hREmployeeHealthInsPaymentAmountDN;
        protected decimal _hREmployeeOutOfWorkInsPaymentAmountDN;
        protected decimal _hREmployeeInsPaymentTotalAmount;
        protected decimal _hREmployeeInsPaymentTotalAmountDN;
        protected String _hREmployeeSocialInsType = String.Empty;
        protected decimal _hREmployeeAllowanceEffective;
        protected decimal _hREmployeeAllowanceOther;
        protected decimal _hREmployeeAllowancePerennial;
        protected bool _hREmployeeIsBoD = true;
        protected int _fK_HRTimeSheetParamID;
        protected DateTime _hREmployeeStartPauseDate = DateTime.MaxValue;
        protected DateTime _hREmployeeEndPauseDate = DateTime.MaxValue;

        #endregion

        #region Public properties
        public int HREmployeeID
        {
            get { return _hREmployeeID; }
            set
            {
                if (value != this._hREmployeeID)
                {
                    _hREmployeeID = value;
                    NotifyChanged("HREmployeeID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                    NotifyChanged("AACreatedUser");
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                    NotifyChanged("AAUpdatedUser");
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                    NotifyChanged("AACreatedDate");
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                    NotifyChanged("AAUpdatedDate");
                }
            }
        }
        public bool IsTransferred
        {
            get { return _isTransferred; }
            set
            {
                if (value != this._isTransferred)
                {
                    _isTransferred = value;
                    NotifyChanged("IsTransferred");
                }
            }
        }
        public DateTime AATransferredDate
        {
            get { return _aATransferredDate; }
            set
            {
                if (value != this._aATransferredDate)
                {
                    _aATransferredDate = value;
                    NotifyChanged("AATransferredDate");
                }
            }
        }
        public int FK_HRDepartmentID
        {
            get { return _fK_HRDepartmentID; }
            set
            {
                if (value != this._fK_HRDepartmentID)
                {
                    _fK_HRDepartmentID = value;
                    NotifyChanged("FK_HRDepartmentID");
                }
            }
        }
        public int FK_HRDepartmentRoomID
        {
            get { return _fK_HRDepartmentRoomID; }
            set
            {
                if (value != this._fK_HRDepartmentRoomID)
                {
                    _fK_HRDepartmentRoomID = value;
                    NotifyChanged("FK_HRDepartmentRoomID");
                }
            }
        }
        public int FK_HRLevelID
        {
            get { return _fK_HRLevelID; }
            set
            {
                if (value != this._fK_HRLevelID)
                {
                    _fK_HRLevelID = value;
                    NotifyChanged("FK_HRLevelID");
                }
            }
        }
        public int FK_HRTimeSheetScaleID
        {
            get { return _fK_HRTimeSheetScaleID; }
            set
            {
                if (value != this._fK_HRTimeSheetScaleID)
                {
                    _fK_HRTimeSheetScaleID = value;
                    NotifyChanged("FK_HRTimeSheetScaleID");
                }
            }
        }
        public int FK_BRBranchID
        {
            get { return _fK_BRBranchID; }
            set
            {
                if (value != this._fK_BRBranchID)
                {
                    _fK_BRBranchID = value;
                    NotifyChanged("FK_BRBranchID");
                }
            }
        }
        public String HREmployeeNo
        {
            get { return _hREmployeeNo; }
            set
            {
                if (value != this._hREmployeeNo)
                {
                    _hREmployeeNo = value;
                    NotifyChanged("HREmployeeNo");
                }
            }
        }
        public String HREmployeeName
        {
            get { return _hREmployeeName; }
            set
            {
                if (value != this._hREmployeeName)
                {
                    _hREmployeeName = value;
                    NotifyChanged("HREmployeeName");
                }
            }
        }
        public String HREmployeeGenderCombo
        {
            get { return _hREmployeeGenderCombo; }
            set
            {
                if (value != this._hREmployeeGenderCombo)
                {
                    _hREmployeeGenderCombo = value;
                    NotifyChanged("HREmployeeGenderCombo");
                }
            }
        }
        public DateTime HREmployeeDob
        {
            get { return _hREmployeeDob; }
            set
            {
                if (value != this._hREmployeeDob)
                {
                    _hREmployeeDob = value;
                    NotifyChanged("HREmployeeDob");
                }
            }
        }
        public String HREmployeeBirthPlace
        {
            get { return _hREmployeeBirthPlace; }
            set
            {
                if (value != this._hREmployeeBirthPlace)
                {
                    _hREmployeeBirthPlace = value;
                    NotifyChanged("HREmployeeBirthPlace");
                }
            }
        }
        public String HREmployeeTypeCombo
        {
            get { return _hREmployeeTypeCombo; }
            set
            {
                if (value != this._hREmployeeTypeCombo)
                {
                    _hREmployeeTypeCombo = value;
                    NotifyChanged("HREmployeeTypeCombo");
                }
            }
        }
        public String HREmployeeStatusCombo
        {
            get { return _hREmployeeStatusCombo; }
            set
            {
                if (value != this._hREmployeeStatusCombo)
                {
                    _hREmployeeStatusCombo = value;
                    NotifyChanged("HREmployeeStatusCombo");
                }
            }
        }
        public String HREmployeeDesc
        {
            get { return _hREmployeeDesc; }
            set
            {
                if (value != this._hREmployeeDesc)
                {
                    _hREmployeeDesc = value;
                    NotifyChanged("HREmployeeDesc");
                }
            }
        }
        public byte[] HREmployeePicture
        {
            get { return _hREmployeePicture; }
            set
            {
                if (value != this._hREmployeePicture)
                {
                    _hREmployeePicture = value;
                    NotifyChanged("HREmployeePicture");
                }
            }
        }
        public String HREmployeeIDNumber
        {
            get { return _hREmployeeIDNumber; }
            set
            {
                if (value != this._hREmployeeIDNumber)
                {
                    _hREmployeeIDNumber = value;
                    NotifyChanged("HREmployeeIDNumber");
                }
            }
        }
        public String HREmployeeIDCardPlace
        {
            get { return _hREmployeeIDCardPlace; }
            set
            {
                if (value != this._hREmployeeIDCardPlace)
                {
                    _hREmployeeIDCardPlace = value;
                    NotifyChanged("HREmployeeIDCardPlace");
                }
            }
        }
        public DateTime HREmployeeIDCardDate
        {
            get { return _hREmployeeIDCardDate; }
            set
            {
                if (value != this._hREmployeeIDCardDate)
                {
                    _hREmployeeIDCardDate = value;
                    NotifyChanged("HREmployeeIDCardDate");
                }
            }
        }
        public String HREmployeeCardNumber
        {
            get { return _hREmployeeCardNumber; }
            set
            {
                if (value != this._hREmployeeCardNumber)
                {
                    _hREmployeeCardNumber = value;
                    NotifyChanged("HREmployeeCardNumber");
                }
            }
        }
        public String HREmployeePassportNo
        {
            get { return _hREmployeePassportNo; }
            set
            {
                if (value != this._hREmployeePassportNo)
                {
                    _hREmployeePassportNo = value;
                    NotifyChanged("HREmployeePassportNo");
                }
            }
        }
        public DateTime HREmployeePassportIssuedDate
        {
            get { return _hREmployeePassportIssuedDate; }
            set
            {
                if (value != this._hREmployeePassportIssuedDate)
                {
                    _hREmployeePassportIssuedDate = value;
                    NotifyChanged("HREmployeePassportIssuedDate");
                }
            }
        }
        public DateTime HREmployeePassportIssuedPlace
        {
            get { return _hREmployeePassportIssuedPlace; }
            set
            {
                if (value != this._hREmployeePassportIssuedPlace)
                {
                    _hREmployeePassportIssuedPlace = value;
                    NotifyChanged("HREmployeePassportIssuedPlace");
                }
            }
        }
        public String HREmployeeSlrPmtMthdCombo
        {
            get { return _hREmployeeSlrPmtMthdCombo; }
            set
            {
                if (value != this._hREmployeeSlrPmtMthdCombo)
                {
                    _hREmployeeSlrPmtMthdCombo = value;
                    NotifyChanged("HREmployeeSlrPmtMthdCombo");
                }
            }
        }
        public decimal HREmployeeWorkingSlrAmt
        {
            get { return _hREmployeeWorkingSlrAmt; }
            set
            {
                if (value != this._hREmployeeWorkingSlrAmt)
                {
                    _hREmployeeWorkingSlrAmt = value;
                    NotifyChanged("HREmployeeWorkingSlrAmt");
                }
            }
        }
        public decimal HREmployeeContractSlrAmt
        {
            get { return _hREmployeeContractSlrAmt; }
            set
            {
                if (value != this._hREmployeeContractSlrAmt)
                {
                    _hREmployeeContractSlrAmt = value;
                    NotifyChanged("HREmployeeContractSlrAmt");
                }
            }
        }
        public String HREmployeeReligion
        {
            get { return _hREmployeeReligion; }
            set
            {
                if (value != this._hREmployeeReligion)
                {
                    _hREmployeeReligion = value;
                    NotifyChanged("HREmployeeReligion");
                }
            }
        }
        public String HREmployeeTaxNumber
        {
            get { return _hREmployeeTaxNumber; }
            set
            {
                if (value != this._hREmployeeTaxNumber)
                {
                    _hREmployeeTaxNumber = value;
                    NotifyChanged("HREmployeeTaxNumber");
                }
            }
        }
        public bool HREmployeeActiveCheck
        {
            get { return _hREmployeeActiveCheck; }
            set
            {
                if (value != this._hREmployeeActiveCheck)
                {
                    _hREmployeeActiveCheck = value;
                    NotifyChanged("HREmployeeActiveCheck");
                }
            }
        }
        public DateTime HREmployeeStartWorkingDate
        {
            get { return _hREmployeeStartWorkingDate; }
            set
            {
                if (value != this._hREmployeeStartWorkingDate)
                {
                    _hREmployeeStartWorkingDate = value;
                    NotifyChanged("HREmployeeStartWorkingDate");
                }
            }
        }
        public DateTime HREmployeeEndWorkingDate
        {
            get { return _hREmployeeEndWorkingDate; }
            set
            {
                if (value != this._hREmployeeEndWorkingDate)
                {
                    _hREmployeeEndWorkingDate = value;
                    NotifyChanged("HREmployeeEndWorkingDate");
                }
            }
        }
        public DateTime HREmployeeStartWorkingTime
        {
            get { return _hREmployeeStartWorkingTime; }
            set
            {
                if (value != this._hREmployeeStartWorkingTime)
                {
                    _hREmployeeStartWorkingTime = value;
                    NotifyChanged("HREmployeeStartWorkingTime");
                }
            }
        }
        public DateTime HREmployeeEndWorkingTime
        {
            get { return _hREmployeeEndWorkingTime; }
            set
            {
                if (value != this._hREmployeeEndWorkingTime)
                {
                    _hREmployeeEndWorkingTime = value;
                    NotifyChanged("HREmployeeEndWorkingTime");
                }
            }
        }
        public String HREmployeeTel1
        {
            get { return _hREmployeeTel1; }
            set
            {
                if (value != this._hREmployeeTel1)
                {
                    _hREmployeeTel1 = value;
                    NotifyChanged("HREmployeeTel1");
                }
            }
        }
        public String HREmployeeTel2
        {
            get { return _hREmployeeTel2; }
            set
            {
                if (value != this._hREmployeeTel2)
                {
                    _hREmployeeTel2 = value;
                    NotifyChanged("HREmployeeTel2");
                }
            }
        }
        public String HREmployeeTel3
        {
            get { return _hREmployeeTel3; }
            set
            {
                if (value != this._hREmployeeTel3)
                {
                    _hREmployeeTel3 = value;
                    NotifyChanged("HREmployeeTel3");
                }
            }
        }
        public String HREmployeeEmail1
        {
            get { return _hREmployeeEmail1; }
            set
            {
                if (value != this._hREmployeeEmail1)
                {
                    _hREmployeeEmail1 = value;
                    NotifyChanged("HREmployeeEmail1");
                }
            }
        }
        public String HREmployeePassword1
        {
            get { return _hREmployeePassword1; }
            set
            {
                if (value != this._hREmployeePassword1)
                {
                    _hREmployeePassword1 = value;
                    NotifyChanged("HREmployeePassword1");
                }
            }
        }
        public String HREmployeeEmail2
        {
            get { return _hREmployeeEmail2; }
            set
            {
                if (value != this._hREmployeeEmail2)
                {
                    _hREmployeeEmail2 = value;
                    NotifyChanged("HREmployeeEmail2");
                }
            }
        }
        public String HREmployeeFax
        {
            get { return _hREmployeeFax; }
            set
            {
                if (value != this._hREmployeeFax)
                {
                    _hREmployeeFax = value;
                    NotifyChanged("HREmployeeFax");
                }
            }
        }
        public String HREmployeeContactAddressStreet
        {
            get { return _hREmployeeContactAddressStreet; }
            set
            {
                if (value != this._hREmployeeContactAddressStreet)
                {
                    _hREmployeeContactAddressStreet = value;
                    NotifyChanged("HREmployeeContactAddressStreet");
                }
            }
        }
        public String HREmployeeContactAddressLine1
        {
            get { return _hREmployeeContactAddressLine1; }
            set
            {
                if (value != this._hREmployeeContactAddressLine1)
                {
                    _hREmployeeContactAddressLine1 = value;
                    NotifyChanged("HREmployeeContactAddressLine1");
                }
            }
        }
        public String HREmployeeContactAddressLine2
        {
            get { return _hREmployeeContactAddressLine2; }
            set
            {
                if (value != this._hREmployeeContactAddressLine2)
                {
                    _hREmployeeContactAddressLine2 = value;
                    NotifyChanged("HREmployeeContactAddressLine2");
                }
            }
        }
        public String HREmployeeContactAddressLine3
        {
            get { return _hREmployeeContactAddressLine3; }
            set
            {
                if (value != this._hREmployeeContactAddressLine3)
                {
                    _hREmployeeContactAddressLine3 = value;
                    NotifyChanged("HREmployeeContactAddressLine3");
                }
            }
        }
        public String HREmployeeContactAddressCity
        {
            get { return _hREmployeeContactAddressCity; }
            set
            {
                if (value != this._hREmployeeContactAddressCity)
                {
                    _hREmployeeContactAddressCity = value;
                    NotifyChanged("HREmployeeContactAddressCity");
                }
            }
        }
        public String HREmployeeContactAddressPostalCode
        {
            get { return _hREmployeeContactAddressPostalCode; }
            set
            {
                if (value != this._hREmployeeContactAddressPostalCode)
                {
                    _hREmployeeContactAddressPostalCode = value;
                    NotifyChanged("HREmployeeContactAddressPostalCode");
                }
            }
        }
        public String HREmployeeContactAddressStateProvince
        {
            get { return _hREmployeeContactAddressStateProvince; }
            set
            {
                if (value != this._hREmployeeContactAddressStateProvince)
                {
                    _hREmployeeContactAddressStateProvince = value;
                    NotifyChanged("HREmployeeContactAddressStateProvince");
                }
            }
        }
        public String HREmployeeContactAddressZipCode
        {
            get { return _hREmployeeContactAddressZipCode; }
            set
            {
                if (value != this._hREmployeeContactAddressZipCode)
                {
                    _hREmployeeContactAddressZipCode = value;
                    NotifyChanged("HREmployeeContactAddressZipCode");
                }
            }
        }
        public String HREmployeeContactAddressCountry
        {
            get { return _hREmployeeContactAddressCountry; }
            set
            {
                if (value != this._hREmployeeContactAddressCountry)
                {
                    _hREmployeeContactAddressCountry = value;
                    NotifyChanged("HREmployeeContactAddressCountry");
                }
            }
        }
        public String HREmployeeBankCode
        {
            get { return _hREmployeeBankCode; }
            set
            {
                if (value != this._hREmployeeBankCode)
                {
                    _hREmployeeBankCode = value;
                    NotifyChanged("HREmployeeBankCode");
                }
            }
        }
        public String HREmployeeBankName
        {
            get { return _hREmployeeBankName; }
            set
            {
                if (value != this._hREmployeeBankName)
                {
                    _hREmployeeBankName = value;
                    NotifyChanged("HREmployeeBankName");
                }
            }
        }
        public String HREmployeeBankAccount1
        {
            get { return _hREmployeeBankAccount1; }
            set
            {
                if (value != this._hREmployeeBankAccount1)
                {
                    _hREmployeeBankAccount1 = value;
                    NotifyChanged("HREmployeeBankAccount1");
                }
            }
        }
        public int HREmployeeBankAccountCurrency1
        {
            get { return _hREmployeeBankAccountCurrency1; }
            set
            {
                if (value != this._hREmployeeBankAccountCurrency1)
                {
                    _hREmployeeBankAccountCurrency1 = value;
                    NotifyChanged("HREmployeeBankAccountCurrency1");
                }
            }
        }
        public String HREmployeeBankAccount2
        {
            get { return _hREmployeeBankAccount2; }
            set
            {
                if (value != this._hREmployeeBankAccount2)
                {
                    _hREmployeeBankAccount2 = value;
                    NotifyChanged("HREmployeeBankAccount2");
                }
            }
        }
        public int HREmployeeBankAccountCurrency2
        {
            get { return _hREmployeeBankAccountCurrency2; }
            set
            {
                if (value != this._hREmployeeBankAccountCurrency2)
                {
                    _hREmployeeBankAccountCurrency2 = value;
                    NotifyChanged("HREmployeeBankAccountCurrency2");
                }
            }
        }
        public String HREmployeeBankAccount3
        {
            get { return _hREmployeeBankAccount3; }
            set
            {
                if (value != this._hREmployeeBankAccount3)
                {
                    _hREmployeeBankAccount3 = value;
                    NotifyChanged("HREmployeeBankAccount3");
                }
            }
        }
        public int HREmployeeBankAccountCurrency3
        {
            get { return _hREmployeeBankAccountCurrency3; }
            set
            {
                if (value != this._hREmployeeBankAccountCurrency3)
                {
                    _hREmployeeBankAccountCurrency3 = value;
                    NotifyChanged("HREmployeeBankAccountCurrency3");
                }
            }
        }
        public String HREmployeeBankAccount4
        {
            get { return _hREmployeeBankAccount4; }
            set
            {
                if (value != this._hREmployeeBankAccount4)
                {
                    _hREmployeeBankAccount4 = value;
                    NotifyChanged("HREmployeeBankAccount4");
                }
            }
        }
        public int HREmployeeBankAccountCurrency4
        {
            get { return _hREmployeeBankAccountCurrency4; }
            set
            {
                if (value != this._hREmployeeBankAccountCurrency4)
                {
                    _hREmployeeBankAccountCurrency4 = value;
                    NotifyChanged("HREmployeeBankAccountCurrency4");
                }
            }
        }
        public String HRInsCalculatedSalaryType
        {
            get { return _hRInsCalculatedSalaryType; }
            set
            {
                if (value != this._hRInsCalculatedSalaryType)
                {
                    _hRInsCalculatedSalaryType = value;
                    NotifyChanged("HRInsCalculatedSalaryType");
                }
            }
        }
        public String HREmployeeSocialInsNo
        {
            get { return _hREmployeeSocialInsNo; }
            set
            {
                if (value != this._hREmployeeSocialInsNo)
                {
                    _hREmployeeSocialInsNo = value;
                    NotifyChanged("HREmployeeSocialInsNo");
                }
            }
        }
        public DateTime HREmployeeSocialInsRegisteredDate
        {
            get { return _hREmployeeSocialInsRegisteredDate; }
            set
            {
                if (value != this._hREmployeeSocialInsRegisteredDate)
                {
                    _hREmployeeSocialInsRegisteredDate = value;
                    NotifyChanged("HREmployeeSocialInsRegisteredDate");
                }
            }
        }
        public DateTime HREmployeeSocialInsExpiryDate
        {
            get { return _hREmployeeSocialInsExpiryDate; }
            set
            {
                if (value != this._hREmployeeSocialInsExpiryDate)
                {
                    _hREmployeeSocialInsExpiryDate = value;
                    NotifyChanged("HREmployeeSocialInsExpiryDate");
                }
            }
        }
        public decimal HREmployeeSocialInsPaymentPercent
        {
            get { return _hREmployeeSocialInsPaymentPercent; }
            set
            {
                if (value != this._hREmployeeSocialInsPaymentPercent)
                {
                    _hREmployeeSocialInsPaymentPercent = value;
                    NotifyChanged("HREmployeeSocialInsPaymentPercent");
                }
            }
        }
        public String HREmployeeHealthInsNo
        {
            get { return _hREmployeeHealthInsNo; }
            set
            {
                if (value != this._hREmployeeHealthInsNo)
                {
                    _hREmployeeHealthInsNo = value;
                    NotifyChanged("HREmployeeHealthInsNo");
                }
            }
        }
        public String HREmployeeHealthInsRegisteredPlace
        {
            get { return _hREmployeeHealthInsRegisteredPlace; }
            set
            {
                if (value != this._hREmployeeHealthInsRegisteredPlace)
                {
                    _hREmployeeHealthInsRegisteredPlace = value;
                    NotifyChanged("HREmployeeHealthInsRegisteredPlace");
                }
            }
        }
        public DateTime HREmployeeHealthInsRegisteredDate
        {
            get { return _hREmployeeHealthInsRegisteredDate; }
            set
            {
                if (value != this._hREmployeeHealthInsRegisteredDate)
                {
                    _hREmployeeHealthInsRegisteredDate = value;
                    NotifyChanged("HREmployeeHealthInsRegisteredDate");
                }
            }
        }
        public DateTime HREmployeeHealthInsExpiryDate
        {
            get { return _hREmployeeHealthInsExpiryDate; }
            set
            {
                if (value != this._hREmployeeHealthInsExpiryDate)
                {
                    _hREmployeeHealthInsExpiryDate = value;
                    NotifyChanged("HREmployeeHealthInsExpiryDate");
                }
            }
        }
        public decimal HREmployeeHealthInsPaymentPercent
        {
            get { return _hREmployeeHealthInsPaymentPercent; }
            set
            {
                if (value != this._hREmployeeHealthInsPaymentPercent)
                {
                    _hREmployeeHealthInsPaymentPercent = value;
                    NotifyChanged("HREmployeeHealthInsPaymentPercent");
                }
            }
        }
        public decimal HREmployeeOutOfWorkInsPaymentPercent
        {
            get { return _hREmployeeOutOfWorkInsPaymentPercent; }
            set
            {
                if (value != this._hREmployeeOutOfWorkInsPaymentPercent)
                {
                    _hREmployeeOutOfWorkInsPaymentPercent = value;
                    NotifyChanged("HREmployeeOutOfWorkInsPaymentPercent");
                }
            }
        }
        public decimal HREmployeeSyndicatePaymentPercent
        {
            get { return _hREmployeeSyndicatePaymentPercent; }
            set
            {
                if (value != this._hREmployeeSyndicatePaymentPercent)
                {
                    _hREmployeeSyndicatePaymentPercent = value;
                    NotifyChanged("HREmployeeSyndicatePaymentPercent");
                }
            }
        }
        public decimal HREmployeeTaxPaymentPercent
        {
            get { return _hREmployeeTaxPaymentPercent; }
            set
            {
                if (value != this._hREmployeeTaxPaymentPercent)
                {
                    _hREmployeeTaxPaymentPercent = value;
                    NotifyChanged("HREmployeeTaxPaymentPercent");
                }
            }
        }
        public decimal HREmployeeSalaryFactor
        {
            get { return _hREmployeeSalaryFactor; }
            set
            {
                if (value != this._hREmployeeSalaryFactor)
                {
                    _hREmployeeSalaryFactor = value;
                    NotifyChanged("HREmployeeSalaryFactor");
                }
            }
        }
        public decimal HREmployeeExtraSalary1
        {
            get { return _hREmployeeExtraSalary1; }
            set
            {
                if (value != this._hREmployeeExtraSalary1)
                {
                    _hREmployeeExtraSalary1 = value;
                    NotifyChanged("HREmployeeExtraSalary1");
                }
            }
        }
        public decimal HREmployeeExtraSalary2
        {
            get { return _hREmployeeExtraSalary2; }
            set
            {
                if (value != this._hREmployeeExtraSalary2)
                {
                    _hREmployeeExtraSalary2 = value;
                    NotifyChanged("HREmployeeExtraSalary2");
                }
            }
        }
        public decimal HREmployeeExtraSalary3
        {
            get { return _hREmployeeExtraSalary3; }
            set
            {
                if (value != this._hREmployeeExtraSalary3)
                {
                    _hREmployeeExtraSalary3 = value;
                    NotifyChanged("HREmployeeExtraSalary3");
                }
            }
        }
        public decimal HREmployeeExtraSalary4
        {
            get { return _hREmployeeExtraSalary4; }
            set
            {
                if (value != this._hREmployeeExtraSalary4)
                {
                    _hREmployeeExtraSalary4 = value;
                    NotifyChanged("HREmployeeExtraSalary4");
                }
            }
        }
        public String HRPayRollCalculatedSalaryType
        {
            get { return _hRPayRollCalculatedSalaryType; }
            set
            {
                if (value != this._hRPayRollCalculatedSalaryType)
                {
                    _hRPayRollCalculatedSalaryType = value;
                    NotifyChanged("HRPayRollCalculatedSalaryType");
                }
            }
        }
        public decimal HREmployeeHoursPerDay
        {
            get { return _hREmployeeHoursPerDay; }
            set
            {
                if (value != this._hREmployeeHoursPerDay)
                {
                    _hREmployeeHoursPerDay = value;
                    NotifyChanged("HREmployeeHoursPerDay");
                }
            }
        }
        public decimal HREmployeeDaysPerMonth
        {
            get { return _hREmployeeDaysPerMonth; }
            set
            {
                if (value != this._hREmployeeDaysPerMonth)
                {
                    _hREmployeeDaysPerMonth = value;
                    NotifyChanged("HREmployeeDaysPerMonth");
                }
            }
        }
        public decimal HREmployeeWorkingHourlySalary
        {
            get { return _hREmployeeWorkingHourlySalary; }
            set
            {
                if (value != this._hREmployeeWorkingHourlySalary)
                {
                    _hREmployeeWorkingHourlySalary = value;
                    NotifyChanged("HREmployeeWorkingHourlySalary");
                }
            }
        }
        public decimal HREmployeeWorkingDailySalary
        {
            get { return _hREmployeeWorkingDailySalary; }
            set
            {
                if (value != this._hREmployeeWorkingDailySalary)
                {
                    _hREmployeeWorkingDailySalary = value;
                    NotifyChanged("HREmployeeWorkingDailySalary");
                }
            }
        }
        public decimal HREmployeeContractHourlySalary
        {
            get { return _hREmployeeContractHourlySalary; }
            set
            {
                if (value != this._hREmployeeContractHourlySalary)
                {
                    _hREmployeeContractHourlySalary = value;
                    NotifyChanged("HREmployeeContractHourlySalary");
                }
            }
        }
        public decimal HREmployeeContractDailySalary
        {
            get { return _hREmployeeContractDailySalary; }
            set
            {
                if (value != this._hREmployeeContractDailySalary)
                {
                    _hREmployeeContractDailySalary = value;
                    NotifyChanged("HREmployeeContractDailySalary");
                }
            }
        }

        public int FK_HREmployeePayrollFormulaID
        {
            get { return _fK_HREmployeePayrollFormulaID; }
            set
            {
                if (value != this._fK_HREmployeePayrollFormulaID)
                {
                    _fK_HREmployeePayrollFormulaID = value;
                    NotifyChanged("FK_HREmployeePayrollFormulaID");
                }
            }
        }
        public int FK_GENativeStateProvinceID
        {
            get { return _fK_GENativeStateProvinceID; }
            set
            {
                if (value != this._fK_GENativeStateProvinceID)
                {
                    _fK_GENativeStateProvinceID = value;
                    NotifyChanged("FK_GENativeStateProvinceID");
                }
            }
        }
        public String HREmployeeMaritalStatusCombo
        {
            get { return _hREmployeeMaritalStatusCombo; }
            set
            {
                if (value != this._hREmployeeMaritalStatusCombo)
                {
                    _hREmployeeMaritalStatusCombo = value;
                    NotifyChanged("HREmployeeMaritalStatusCombo");
                }
            }
        }
        public String HREmployeeEducation
        {
            get { return _hREmployeeEducation; }
            set
            {
                if (value != this._hREmployeeEducation)
                {
                    _hREmployeeEducation = value;
                    NotifyChanged("HREmployeeEducation");
                }
            }
        }
        public int FK_GEIDCardStateProvinceID
        {
            get { return _fK_GEIDCardStateProvinceID; }
            set
            {
                if (value != this._fK_GEIDCardStateProvinceID)
                {
                    _fK_GEIDCardStateProvinceID = value;
                    NotifyChanged("FK_GEIDCardStateProvinceID");
                }
            }
        }
        public int FK_GENationalityID
        {
            get { return _fK_GENationalityID; }
            set
            {
                if (value != this._fK_GENationalityID)
                {
                    _fK_GENationalityID = value;
                    NotifyChanged("FK_GENationalityID");
                }
            }
        }
        public int FK_GEReligionID
        {
            get { return _fK_GEReligionID; }
            set
            {
                if (value != this._fK_GEReligionID)
                {
                    _fK_GEReligionID = value;
                    NotifyChanged("FK_GEReligionID");
                }
            }
        }
        public int FK_GEStateProvinceIDBHXH
        {
            get { return _fK_GEStateProvinceIDBHXH; }
            set
            {
                if (value != this._fK_GEStateProvinceIDBHXH)
                {
                    _fK_GEStateProvinceIDBHXH = value;
                    NotifyChanged("FK_GEStateProvinceIDBHXH");
                }
            }
        }
        public decimal HREmployeeWorkingMonths
        {
            get { return _hREmployeeWorkingMonths; }
            set
            {
                if (value != this._hREmployeeWorkingMonths)
                {
                    _hREmployeeWorkingMonths = value;
                    NotifyChanged("HREmployeeWorkingMonths");
                }
            }
        }
        public bool HREmployeeUniform
        {
            get { return _hREmployeeUniform; }
            set
            {
                if (value != this._hREmployeeUniform)
                {
                    _hREmployeeUniform = value;
                    NotifyChanged("HREmployeeUniform");
                }
            }
        }
        public String HREmployeeDobString
        {
            get { return _hREmployeeDobString; }
            set
            {
                if (value != this._hREmployeeDobString)
                {
                    _hREmployeeDobString = value;
                    NotifyChanged("HREmployeeDobString");
                }
            }
        }
        public int HREmployeeProbationaryMonth
        {
            get { return _hREmployeeProbationaryMonth; }
            set
            {
                if (value != this._hREmployeeProbationaryMonth)
                {
                    _hREmployeeProbationaryMonth = value;
                    NotifyChanged("HREmployeeProbationaryMonth");
                }
            }
        }
        public DateTime HREmployeeStopWorkingDate
        {
            get { return _hREmployeeStopWorkingDate; }
            set
            {
                if (value != this._hREmployeeStopWorkingDate)
                {
                    _hREmployeeStopWorkingDate = value;
                    NotifyChanged("HREmployeeStopWorkingDate");
                }
            }
        }
        public decimal HREmployeeLeaveDays
        {
            get { return _hREmployeeLeaveDays; }
            set
            {
                if (value != this._hREmployeeLeaveDays)
                {
                    _hREmployeeLeaveDays = value;
                    NotifyChanged("HREmployeeLeaveDays");
                }
            }
        }
        public decimal HREmployeeSyndicatePaymentAmount
        {
            get { return _hREmployeeSyndicatePaymentAmount; }
            set
            {
                if (value != this._hREmployeeSyndicatePaymentAmount)
                {
                    _hREmployeeSyndicatePaymentAmount = value;
                    NotifyChanged("HREmployeeSyndicatePaymentAmount");
                }
            }
        }
        public bool HREmployeeIsUnionMember
        {
            get { return _hREmployeeIsUnionMember; }
            set
            {
                if (value != this._hREmployeeIsUnionMember)
                {
                    _hREmployeeIsUnionMember = value;
                    NotifyChanged("HREmployeeIsUnionMember");
                }
            }
        }
        public decimal HREmployeeUnionMemberFee
        {
            get { return _hREmployeeUnionMemberFee; }
            set
            {
                if (value != this._hREmployeeUnionMemberFee)
                {
                    _hREmployeeUnionMemberFee = value;
                    NotifyChanged("HREmployeeUnionMemberFee");
                }
            }
        }
        public int FK_HRDepartmentRoomGroupItemID
        {
            get { return _fK_HRDepartmentRoomGroupItemID; }
            set
            {
                if (value != this._fK_HRDepartmentRoomGroupItemID)
                {
                    _fK_HRDepartmentRoomGroupItemID = value;
                    NotifyChanged("FK_HRDepartmentRoomGroupItemID");
                }
            }
        }
        public String HREmployeeTrainingCourseID
        {
            get { return _hREmployeeTrainingCourseID; }
            set
            {
                if (value != this._hREmployeeTrainingCourseID)
                {
                    _hREmployeeTrainingCourseID = value;
                    NotifyChanged("HREmployeeTrainingCourseID");
                }
            }
        }
        public String HREmployeeTrainingCourseValue
        {
            get { return _hREmployeeTrainingCourseValue; }
            set
            {
                if (value != this._hREmployeeTrainingCourseValue)
                {
                    _hREmployeeTrainingCourseValue = value;
                    NotifyChanged("HREmployeeTrainingCourseValue");
                }
            }
        }
        public int HREmployeeAnnualLeaveRemain
        {
            get { return _hREmployeeAnnualLeaveRemain; }
            set
            {
                if (value != this._hREmployeeAnnualLeaveRemain)
                {
                    _hREmployeeAnnualLeaveRemain = value;
                    NotifyChanged("HREmployeeAnnualLeaveRemain");
                }
            }
        }
        public String HREmployeePictureFileName
        {
            get { return _hREmployeePictureFileName; }
            set
            {
                if (value != this._hREmployeePictureFileName)
                {
                    _hREmployeePictureFileName = value;
                    NotifyChanged("HREmployeePictureFileName");
                }
            }
        }
        public int FK_ACAccountDepositID
        {
            get { return _fK_ACAccountDepositID; }
            set
            {
                if (value != this._fK_ACAccountDepositID)
                {
                    _fK_ACAccountDepositID = value;
                    NotifyChanged("FK_ACAccountDepositID");
                }
            }
        }
        public int FK_ACAccountPurchaseID
        {
            get { return _fK_ACAccountPurchaseID; }
            set
            {
                if (value != this._fK_ACAccountPurchaseID)
                {
                    _fK_ACAccountPurchaseID = value;
                    NotifyChanged("FK_ACAccountPurchaseID");
                }
            }
        }
        public int FK_ACAccountSaleID
        {
            get { return _fK_ACAccountSaleID; }
            set
            {
                if (value != this._fK_ACAccountSaleID)
                {
                    _fK_ACAccountSaleID = value;
                    NotifyChanged("FK_ACAccountSaleID");
                }
            }
        }
        public String HREmployeeFirstName
        {
            get { return _hREmployeeFirstName; }
            set
            {
                if (value != this._hREmployeeFirstName)
                {
                    _hREmployeeFirstName = value;
                    NotifyChanged("HREmployeeFirstName");
                }
            }
        }
        public String HREmployeeLastName
        {
            get { return _hREmployeeLastName; }
            set
            {
                if (value != this._hREmployeeLastName)
                {
                    _hREmployeeLastName = value;
                    NotifyChanged("HREmployeeLastName");
                }
            }
        }
        public int FK_ADPortalUserID
        {
            get { return _fK_ADPortalUserID; }
            set
            {
                if (value != this._fK_ADPortalUserID)
                {
                    _fK_ADPortalUserID = value;
                    NotifyChanged("FK_ADPortalUserID");
                }
            }
        }
        public decimal HREmployeeAllowanceResponsibility
        {
            get { return _hREmployeeAllowanceResponsibility; }
            set
            {
                if (value != this._hREmployeeAllowanceResponsibility)
                {
                    _hREmployeeAllowanceResponsibility = value;
                    NotifyChanged("HREmployeeAllowanceResponsibility");
                }
            }
        }
        public decimal HREmployeeAllowanceKPI
        {
            get { return _hREmployeeAllowanceKPI; }
            set
            {
                if (value != this._hREmployeeAllowanceKPI)
                {
                    _hREmployeeAllowanceKPI = value;
                    NotifyChanged("HREmployeeAllowanceKPI");
                }
            }
        }
        public decimal HREmployeeAllowanceResponsibility2
        {
            get { return _hREmployeeAllowanceResponsibility2; }
            set
            {
                if (value != this._hREmployeeAllowanceResponsibility2)
                {
                    _hREmployeeAllowanceResponsibility2 = value;
                    NotifyChanged("HREmployeeAllowanceResponsibility2");
                }
            }
        }
        public decimal HREmployeeAllowanceProgress
        {
            get { return _hREmployeeAllowanceProgress; }
            set
            {
                if (value != this._hREmployeeAllowanceProgress)
                {
                    _hREmployeeAllowanceProgress = value;
                    NotifyChanged("HREmployeeAllowanceProgress");
                }
            }
        }
        public String HREmployeeLocationIssuedRecord
        {
            get { return _hREmployeeLocationIssuedRecord; }
            set
            {
                if (value != this._hREmployeeLocationIssuedRecord)
                {
                    _hREmployeeLocationIssuedRecord = value;
                    NotifyChanged("HREmployeeLocationIssuedRecord");
                }
            }
        }
        public bool HREmployeeHasSocialInsurance
        {
            get { return _hREmployeeHasSocialInsurance; }
            set
            {
                if (value != this._hREmployeeHasSocialInsurance)
                {
                    _hREmployeeHasSocialInsurance = value;
                    NotifyChanged("HREmployeeHasSocialInsurance");
                }
            }
        }
        public DateTime HREmployeeProbationaryStartDate
        {
            get { return _hREmployeeProbationaryStartDate; }
            set
            {
                if (value != this._hREmployeeProbationaryStartDate)
                {
                    _hREmployeeProbationaryStartDate = value;
                    NotifyChanged("HREmployeeProbationaryStartDate");
                }
            }
        }
        public DateTime HREmployeeProbationaryEndDate
        {
            get { return _hREmployeeProbationaryEndDate; }
            set
            {
                if (value != this._hREmployeeProbationaryEndDate)
                {
                    _hREmployeeProbationaryEndDate = value;
                    NotifyChanged("HREmployeeProbationaryEndDate");
                }
            }
        }
        public decimal HREmployeeProbationarySalaryAmount
        {
            get { return _hREmployeeProbationarySalaryAmount; }
            set
            {
                if (value != this._hREmployeeProbationarySalaryAmount)
                {
                    _hREmployeeProbationarySalaryAmount = value;
                    NotifyChanged("HREmployeeProbationarySalaryAmount");
                }
            }
        }
        public decimal HREmployeeProbationaryExtraSalary
        {
            get { return _hREmployeeProbationaryExtraSalary; }
            set
            {
                if (value != this._hREmployeeProbationaryExtraSalary)
                {
                    _hREmployeeProbationaryExtraSalary = value;
                    NotifyChanged("HREmployeeProbationaryExtraSalary");
                }
            }
        }
        public String HREmployeeProbationaryType
        {
            get { return _hREmployeeProbationaryType; }
            set
            {
                if (value != this._hREmployeeProbationaryType)
                {
                    _hREmployeeProbationaryType = value;
                    NotifyChanged("HREmployeeProbationaryType");
                }
            }
        }
        public int FK_HRConfigRankID
        {
            get { return _fK_HRConfigRankID; }
            set
            {
                if (value != this._fK_HRConfigRankID)
                {
                    _fK_HRConfigRankID = value;
                    NotifyChanged("FK_HRConfigRankID");
                }
            }
        }
        public int FK_HRConfigScaleID
        {
            get { return _fK_HRConfigScaleID; }
            set
            {
                if (value != this._fK_HRConfigScaleID)
                {
                    _fK_HRConfigScaleID = value;
                    NotifyChanged("FK_HRConfigScaleID");
                }
            }
        }
        public int FK_ADWorkingShiftID
        {
            get { return _fK_ADWorkingShiftID; }
            set
            {
                if (value != this._fK_ADWorkingShiftID)
                {
                    _fK_ADWorkingShiftID = value;
                    NotifyChanged("FK_ADWorkingShiftID");
                }
            }
        }
        public String HREmployeePayRollCalculatedWorkType
        {
            get { return _hREmployeePayRollCalculatedWorkType; }
            set
            {
                if (value != this._hREmployeePayRollCalculatedWorkType)
                {
                    _hREmployeePayRollCalculatedWorkType = value;
                    NotifyChanged("HREmployeePayRollCalculatedWorkType");
                }
            }
        }
        public DateTime HREmployeeApprenticeStartDate
        {
            get { return _hREmployeeApprenticeStartDate; }
            set
            {
                if (value != this._hREmployeeApprenticeStartDate)
                {
                    _hREmployeeApprenticeStartDate = value;
                    NotifyChanged("HREmployeeApprenticeStartDate");
                }
            }
        }
        public DateTime HREmployeeApprenticeEndDate
        {
            get { return _hREmployeeApprenticeEndDate; }
            set
            {
                if (value != this._hREmployeeApprenticeEndDate)
                {
                    _hREmployeeApprenticeEndDate = value;
                    NotifyChanged("HREmployeeApprenticeEndDate");
                }
            }
        }
        public decimal HREmployeeApprenticeSalaryAmount
        {
            get { return _hREmployeeApprenticeSalaryAmount; }
            set
            {
                if (value != this._hREmployeeApprenticeSalaryAmount)
                {
                    _hREmployeeApprenticeSalaryAmount = value;
                    NotifyChanged("HREmployeeApprenticeSalaryAmount");
                }
            }
        }
        public decimal HREmployeeAllowanceVehicleMaintenance
        {
            get { return _hREmployeeAllowanceVehicleMaintenance; }
            set
            {
                if (value != this._hREmployeeAllowanceVehicleMaintenance)
                {
                    _hREmployeeAllowanceVehicleMaintenance = value;
                    NotifyChanged("HREmployeeAllowanceVehicleMaintenance");
                }
            }
        }
        public String HREmployeeBankNo
        {
            get { return _hREmployeeBankNo; }
            set
            {
                if (value != this._hREmployeeBankNo)
                {
                    _hREmployeeBankNo = value;
                    NotifyChanged("HREmployeeBankNo");
                }
            }
        }
        public bool HREmployeePartyMember
        {
            get { return _hREmployeePartyMember; }
            set
            {
                if (value != this._hREmployeePartyMember)
                {
                    _hREmployeePartyMember = value;
                    NotifyChanged("HREmployeePartyMember");
                }
            }
        }
        public int FK_ACCostCenterID
        {
            get { return _fK_ACCostCenterID; }
            set
            {
                if (value != this._fK_ACCostCenterID)
                {
                    _fK_ACCostCenterID = value;
                    NotifyChanged("FK_ACCostCenterID");
                }
            }
        }
        public String HREmployeeWorkingForm
        {
            get { return _hREmployeeWorkingForm; }
            set
            {
                if (value != this._hREmployeeWorkingForm)
                {
                    _hREmployeeWorkingForm = value;
                    NotifyChanged("HREmployeeWorkingForm");
                }
            }
        }
        public decimal HREmployeeSocialInsPaymentPercentDN
        {
            get { return _hREmployeeSocialInsPaymentPercentDN; }
            set
            {
                if (value != this._hREmployeeSocialInsPaymentPercentDN)
                {
                    _hREmployeeSocialInsPaymentPercentDN = value;
                    NotifyChanged("HREmployeeSocialInsPaymentPercentDN");
                }
            }
        }
        public decimal HREmployeeHealthInsPaymentPercentDN
        {
            get { return _hREmployeeHealthInsPaymentPercentDN; }
            set
            {
                if (value != this._hREmployeeHealthInsPaymentPercentDN)
                {
                    _hREmployeeHealthInsPaymentPercentDN = value;
                    NotifyChanged("HREmployeeHealthInsPaymentPercentDN");
                }
            }
        }
        public decimal HREmployeeOutOfWorkInsPaymentPercentDN
        {
            get { return _hREmployeeOutOfWorkInsPaymentPercentDN; }
            set
            {
                if (value != this._hREmployeeOutOfWorkInsPaymentPercentDN)
                {
                    _hREmployeeOutOfWorkInsPaymentPercentDN = value;
                    NotifyChanged("HREmployeeOutOfWorkInsPaymentPercentDN");
                }
            }
        }
        public decimal HREmployeeAllowanceDiligence
        {
            get { return _hREmployeeAllowanceDiligence; }
            set
            {
                if (value != this._hREmployeeAllowanceDiligence)
                {
                    _hREmployeeAllowanceDiligence = value;
                    NotifyChanged("HREmployeeAllowanceDiligence");
                }
            }
        }
        public decimal HREmployeeAllowanceGasoline
        {
            get { return _hREmployeeAllowanceGasoline; }
            set
            {
                if (value != this._hREmployeeAllowanceGasoline)
                {
                    _hREmployeeAllowanceGasoline = value;
                    NotifyChanged("HREmployeeAllowanceGasoline");
                }
            }
        }
        public decimal HREmployeeAllowanceMotel
        {
            get { return _hREmployeeAllowanceMotel; }
            set
            {
                if (value != this._hREmployeeAllowanceMotel)
                {
                    _hREmployeeAllowanceMotel = value;
                    NotifyChanged("HREmployeeAllowanceMotel");
                }
            }
        }
        public decimal HREmployeeWorkingSlrAmtDate
        {
            get { return _hREmployeeWorkingSlrAmtDate; }
            set
            {
                if (value != this._hREmployeeWorkingSlrAmtDate)
                {
                    _hREmployeeWorkingSlrAmtDate = value;
                    NotifyChanged("HREmployeeWorkingSlrAmtDate");
                }
            }
        }
        public decimal HREmployeePieceWage
        {
            get { return _hREmployeePieceWage; }
            set
            {
                if (value != this._hREmployeePieceWage)
                {
                    _hREmployeePieceWage = value;
                    NotifyChanged("HREmployeePieceWage");
                }
            }
        }
        public decimal HREmployeeSocialInsPaymentAmount
        {
            get { return _hREmployeeSocialInsPaymentAmount; }
            set
            {
                if (value != this._hREmployeeSocialInsPaymentAmount)
                {
                    _hREmployeeSocialInsPaymentAmount = value;
                    NotifyChanged("HREmployeeSocialInsPaymentAmount");
                }
            }
        }
        public decimal HREmployeeHealthInsPaymentAmount
        {
            get { return _hREmployeeHealthInsPaymentAmount; }
            set
            {
                if (value != this._hREmployeeHealthInsPaymentAmount)
                {
                    _hREmployeeHealthInsPaymentAmount = value;
                    NotifyChanged("HREmployeeHealthInsPaymentAmount");
                }
            }
        }
        public decimal HREmployeeOutOfWorkInsPaymentAmount
        {
            get { return _hREmployeeOutOfWorkInsPaymentAmount; }
            set
            {
                if (value != this._hREmployeeOutOfWorkInsPaymentAmount)
                {
                    _hREmployeeOutOfWorkInsPaymentAmount = value;
                    NotifyChanged("HREmployeeOutOfWorkInsPaymentAmount");
                }
            }
        }
        public decimal HREmployeeSocialInsPaymentAmountDN
        {
            get { return _hREmployeeSocialInsPaymentAmountDN; }
            set
            {
                if (value != this._hREmployeeSocialInsPaymentAmountDN)
                {
                    _hREmployeeSocialInsPaymentAmountDN = value;
                    NotifyChanged("HREmployeeSocialInsPaymentAmountDN");
                }
            }
        }
        public decimal HREmployeeHealthInsPaymentAmountDN
        {
            get { return _hREmployeeHealthInsPaymentAmountDN; }
            set
            {
                if (value != this._hREmployeeHealthInsPaymentAmountDN)
                {
                    _hREmployeeHealthInsPaymentAmountDN = value;
                    NotifyChanged("HREmployeeHealthInsPaymentAmountDN");
                }
            }
        }
        public decimal HREmployeeOutOfWorkInsPaymentAmountDN
        {
            get { return _hREmployeeOutOfWorkInsPaymentAmountDN; }
            set
            {
                if (value != this._hREmployeeOutOfWorkInsPaymentAmountDN)
                {
                    _hREmployeeOutOfWorkInsPaymentAmountDN = value;
                    NotifyChanged("HREmployeeOutOfWorkInsPaymentAmountDN");
                }
            }
        }
        public decimal HREmployeeInsPaymentTotalAmount
        {
            get { return _hREmployeeInsPaymentTotalAmount; }
            set
            {
                if (value != this._hREmployeeInsPaymentTotalAmount)
                {
                    _hREmployeeInsPaymentTotalAmount = value;
                    NotifyChanged("HREmployeeInsPaymentTotalAmount");
                }
            }
        }
        public decimal HREmployeeInsPaymentTotalAmountDN
        {
            get { return _hREmployeeInsPaymentTotalAmountDN; }
            set
            {
                if (value != this._hREmployeeInsPaymentTotalAmountDN)
                {
                    _hREmployeeInsPaymentTotalAmountDN = value;
                    NotifyChanged("HREmployeeInsPaymentTotalAmountDN");
                }
            }
        }
        public String HREmployeeSocialInsType
        {
            get { return _hREmployeeSocialInsType; }
            set
            {
                if (value != this._hREmployeeSocialInsType)
                {
                    _hREmployeeSocialInsType = value;
                    NotifyChanged("HREmployeeSocialInsType");
                }
            }
        }
        public decimal HREmployeeAllowanceEffective
        {
            get { return _hREmployeeAllowanceEffective; }
            set
            {
                if (value != this._hREmployeeAllowanceEffective)
                {
                    _hREmployeeAllowanceEffective = value;
                    NotifyChanged("HREmployeeAllowanceEffective");
                }
            }
        }
        public decimal HREmployeeAllowanceOther
        {
            get { return _hREmployeeAllowanceOther; }
            set
            {
                if (value != this._hREmployeeAllowanceOther)
                {
                    _hREmployeeAllowanceOther = value;
                    NotifyChanged("HREmployeeAllowanceOther");
                }
            }
        }
        public decimal HREmployeeAllowancePerennial
        {
            get { return _hREmployeeAllowancePerennial; }
            set
            {
                if (value != this._hREmployeeAllowancePerennial)
                {
                    _hREmployeeAllowancePerennial = value;
                    NotifyChanged("HREmployeeAllowancePerennial");
                }
            }
        }
        public bool HREmployeeIsBoD
        {
            get { return _hREmployeeIsBoD; }
            set
            {
                if (value != this._hREmployeeIsBoD)
                {
                    _hREmployeeIsBoD = value;
                    NotifyChanged("HREmployeeIsBoD");
                }
            }
        }
        public int FK_HRTimeSheetParamID
        {
            get { return _fK_HRTimeSheetParamID; }
            set
            {
                if (value != this._fK_HRTimeSheetParamID)
                {
                    _fK_HRTimeSheetParamID = value;
                    NotifyChanged("FK_HRTimeSheetParamID");
                }
            }
        }
        public DateTime HREmployeeStartPauseDate
        {
            get { return _hREmployeeStartPauseDate; }
            set
            {
                if (value != this._hREmployeeStartPauseDate)
                {
                    _hREmployeeStartPauseDate = value;
                    NotifyChanged("HREmployeeStartPauseDate");
                }
            }
        }
        public DateTime HREmployeeEndPauseDate
        {
            get { return _hREmployeeEndPauseDate; }
            set
            {
                if (value != this._hREmployeeEndPauseDate)
                {
                    _hREmployeeEndPauseDate = value;
                    NotifyChanged("HREmployeeEndPauseDate");
                }
            }
        }

        #endregion
        #region Extra Properties
        public decimal HREmployeeWorkingSlrAmtDateTotal { get; set; }
        public DateTime HREmployeeOTDate { get; set; }
        public DateTime HREmployeeOTDateEnd { get; set; }
        public DateTime HREmployeeOTFromDate { get; set; }
        public DateTime HREmployeeOTToDate { get; set; }

        public string HRDepartmentName { get; set; }
        public string HRDepartmentRoomName { get; set; }
        public string HRDepartmentRoomGroupItemName { get; set; }
        public string HRLevelName { get; set; }
        #endregion
    }
    #endregion
}