using System;
using System.Text;
using System.Collections.Generic;
using VinaLib;
namespace VinaERP
{
    #region HRFormAllowances
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:HRFormAllowancesInfo
    //Created Date:Thursday, November 22, 2018
    //-----------------------------------------------------------

    public class HRFormAllowancesInfo : BusinessObject
    {
        public HRFormAllowancesInfo()
        {
        }
        #region Variables
        protected int _hRFormAllowanceID;
        protected String _aAStatus = DefaultAAStatus;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected String _aACreatedUser = String.Empty;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected String _aAUpdatedUser = String.Empty;
        protected String _hRFormAllowanceNo = String.Empty;
        protected String _hRFormAllowanceName = String.Empty;
        protected String _hRFormAllowanceDesc = String.Empty;
        protected String _hRFormAllowanceType = String.Empty;
        protected String _hRFormAllowanceNameType = String.Empty;

        #endregion

        #region Public properties
        public int HRFormAllowanceID
        {
            get { return _hRFormAllowanceID; }
            set
            {
                if (value != this._hRFormAllowanceID)
                {
                    _hRFormAllowanceID = value;
                    NotifyChanged("HRFormAllowanceID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                    NotifyChanged("AACreatedDate");
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                    NotifyChanged("AACreatedUser");
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                    NotifyChanged("AAUpdatedDate");
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                    NotifyChanged("AAUpdatedUser");
                }
            }
        }
        public String HRFormAllowanceNo
        {
            get { return _hRFormAllowanceNo; }
            set
            {
                if (value != this._hRFormAllowanceNo)
                {
                    _hRFormAllowanceNo = value;
                    NotifyChanged("HRFormAllowanceNo");
                }
            }
        }
        public String HRFormAllowanceName
        {
            get { return _hRFormAllowanceName; }
            set
            {
                if (value != this._hRFormAllowanceName)
                {
                    _hRFormAllowanceName = value;
                    NotifyChanged("HRFormAllowanceName");
                }
            }
        }
        public String HRFormAllowanceDesc
        {
            get { return _hRFormAllowanceDesc; }
            set
            {
                if (value != this._hRFormAllowanceDesc)
                {
                    _hRFormAllowanceDesc = value;
                    NotifyChanged("HRFormAllowanceDesc");
                }
            }
        }
        public String HRFormAllowanceType
        {
            get { return _hRFormAllowanceType; }
            set
            {
                if (value != this._hRFormAllowanceType)
                {
                    _hRFormAllowanceType = value;
                    NotifyChanged("HRFormAllowanceType");
                }
            }
        }
        public String HRFormAllowanceNameType
        {
            get { return _hRFormAllowanceNameType; }
            set
            {
                if (value != this._hRFormAllowanceNameType)
                {
                    _hRFormAllowanceNameType = value;
                    NotifyChanged("HRFormAllowanceNameType");
                }
            }
        }

        #endregion
    }
    #endregion
}