using System;
using System.Text;
using System.Collections.Generic;
using VinaLib;
namespace VinaERP
{
    #region HRLeaveDays
    //-----------------------------------------------------------
    //Generated By: Vina Studio
    //Class:HRLeaveDaysInfo
    //Created Date:Tuesday, May 10, 2011
    //-----------------------------------------------------------

    public class HRLeaveDaysInfo : BusinessObject
    {
        public HRLeaveDaysInfo()
        {
        }


        #region Variables
        protected int _hRLeaveDayID;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_HREmployeeID;
        protected int _fK_HRTimeSheetParamID;
        protected DateTime _hRLeaveDayDate = DateTime.MaxValue;
        protected String _hRLeaveDayReason = String.Empty;
        #endregion

        #region Public properties
        public int HRLeaveDayID
        {
            get { return _hRLeaveDayID; }
            set
            {
                if (value != this._hRLeaveDayID)
                {
                    _hRLeaveDayID = value;
                    NotifyChanged("HRLeaveDayID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public int FK_HREmployeeID
        {
            get { return _fK_HREmployeeID; }
            set
            {
                if (value != this._fK_HREmployeeID)
                {
                    _fK_HREmployeeID = value;
                    NotifyChanged("FK_HREmployeeID");
                }
            }
        }
        public int FK_HRTimeSheetParamID
        {
            get { return _fK_HRTimeSheetParamID; }
            set
            {
                if (value != this._fK_HRTimeSheetParamID)
                {
                    _fK_HRTimeSheetParamID = value;
                    NotifyChanged("FK_HRTimeSheetParamID");
                }
            }
        }
        public DateTime HRLeaveDayDate
        {
            get { return _hRLeaveDayDate; }
            set
            {
                if (value != this._hRLeaveDayDate)
                {
                    _hRLeaveDayDate = value;
                    NotifyChanged("HRLeaveDayDate");
                }
            }
        }
        public String HRLeaveDayReason
        {
            get { return _hRLeaveDayReason; }
            set
            {
                if (value != this._hRLeaveDayReason)
                {
                    _hRLeaveDayReason = value;
                    NotifyChanged("HRLeaveDayReason");
                }
            }
        }
        #endregion

        #region Extra Properties
        public string HREmployeeNo { get; set; }
        public string HREmployeeName { get; set; }
        public string HREmployeeCardNumber { get; set; }
        public string HRLeaveDayDate1 { get; set; }
        public string HRLeaveDayDate2 { get; set; }
        public string HRLeaveDayDate3 { get; set; }
        public string HRLeaveDayDate4 { get; set; }
        public string HRLeaveDayDate5 { get; set; }
        public string HRLeaveDayDate6 { get; set; }
        public string HRLeaveDayDate7 { get; set; }
        public string HRLeaveDayDate8 { get; set; }
        public string HRLeaveDayDate9 { get; set; }
        public string HRLeaveDayDate10 { get; set; }
        public string HRLeaveDayDate11 { get; set; }
        public string HRLeaveDayDate12 { get; set; }
        public string HRLeaveDayDate13 { get; set; }
        public string HRLeaveDayDate14 { get; set; }
        public string HRLeaveDayDate15 { get; set; }
        public string HRLeaveDayDate16 { get; set; }
        public string HRLeaveDayDate17 { get; set; }
        public string HRLeaveDayDate18 { get; set; }
        public string HRLeaveDayDate19 { get; set; }
        public string HRLeaveDayDate20 { get; set; }
        public string HRLeaveDayDate21 { get; set; }
        public string HRLeaveDayDate22 { get; set; }
        public string HRLeaveDayDate23 { get; set; }
        public string HRLeaveDayDate24 { get; set; }
        public string HRLeaveDayDate25 { get; set; }
        public string HRLeaveDayDate26 { get; set; }
        public string HRLeaveDayDate27 { get; set; }
        public string HRLeaveDayDate28 { get; set; }
        public string HRLeaveDayDate29 { get; set; }
        public string HRLeaveDayDate30 { get; set; }
        public string HRLeaveDayDate31 { get; set; }

        public decimal TotalLeaveDays { get; set; }
        public decimal TotalLeaveDaysOfYear { get; set; }
        public DateTime HRLeaveDayToDate { get; set; }
        public DateTime HRLeaveDayFromDate { get; set; }
        public string HRTimeSheetParamName { get; set; }
        public string HRLeaveDayType { get; set; }
        public decimal HRLeaveDayQty { get; set; }
        public string HRTimeSheetParamNo { get; set; }

        //Report
        public decimal HRLeaveMonthJan { get; set; }

        public decimal HRLeaveMonthFeb { get; set; }

        public decimal HRLeaveMonthMar { get; set; }

        public decimal HRLeaveMonthApr { get; set; }

        public decimal HRLeaveMonthMay { get; set; }

        public decimal HRLeaveMonthJun { get; set; }

        public decimal HRLeaveMonthJul { get; set; }

        public decimal HRLeaveMonthAug { get; set; }

        public decimal HRLeaveMonthSep { get; set; }

        public decimal HRLeaveMonthOct { get; set; }

        public decimal HRLeaveMonthNov { get; set; }

        public decimal HRLeaveMonthDec { get; set; }

        public decimal HRLeaveMonthAll { get; set; }

        public decimal HREmployeeAnnualLeaveRemain { get; set; }

        public decimal HRLeaveAddDay { get; set; }

        public DateTime HREmployeeStartWorkingDate { get; set; }

        public DateTime DateTo { get; set; }


        public int HRLeaveYear { get; set; }

        public int HRLeaveLastYear { get; set; }

        public int RowNumber { get; set; }

        public decimal HREmployeeWorkingMonths { get; set; }

        public string HRLeaveMonthYear { get; set; }

        public string HRDepartmentName { get; set; }

        public string HRDepartmentRoomName { get; set; }

        public string HRDepartmentRoomGroupItemName { get; set; }

        public string HRLevelName { get; set; }

        #endregion
    }
    #endregion
}