using System;
using System.Text;
using System.Collections.Generic;
using VinaLib;
namespace VinaERP
{
    #region HROverTimes
    //-----------------------------------------------------------
    //Generated By: Vina Studio
    //Class:HROverTimesInfo
    //Created Date:Monday, April 25, 2011
    //-----------------------------------------------------------

    public class HROverTimesInfo : BusinessObject
    {
        public HROverTimesInfo()
        {
        }
        #region Variables
        protected int _hROverTimeID;
        protected String _aAStatus = DefaultAAStatus;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected String _aACreatedUser = String.Empty;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected String _aAUpdatedUser = String.Empty;
        protected String _hROverTimeNo = String.Empty;
        protected String _hROverTimeName = String.Empty;
        protected String _hROverTimeDesc = String.Empty;
        protected DateTime _hROverTimeFromDate = DateTime.MaxValue;
        protected DateTime _hROverTimeToDate = DateTime.MaxValue;
        protected DateTime _hROverTimeDate = DateTime.MaxValue;
        protected String _hREmployeeCardNumber = String.Empty;
        protected String _hREmployeeName = String.Empty;
        protected bool _hROverTimeHaveMeal = true;
        protected DateTime _hROverTimeDateEnd = DateTime.MaxValue;
        protected int _fK_ADWorkingShiftID;
        protected String _hROverTimeStatus = DefaultStatus;
        protected DateTime _hROverTimeFromTimeIn = DateTime.MaxValue;
        protected DateTime _hROverTimeFromTimeOut = DateTime.MaxValue;
        protected DateTime _hROverTimeToTimeIn = DateTime.MaxValue;
        protected DateTime _hROverTimeToTimeOut = DateTime.MaxValue;
        protected int _fK_HRTimeSheetParamID;
        protected decimal _hROverTimeFactor;

        #endregion

        #region Public properties
        public int HROverTimeID
        {
            get { return _hROverTimeID; }
            set
            {
                if (value != this._hROverTimeID)
                {
                    _hROverTimeID = value;
                    NotifyChanged("HROverTimeID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                    NotifyChanged("AACreatedDate");
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                    NotifyChanged("AACreatedUser");
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                    NotifyChanged("AAUpdatedDate");
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                    NotifyChanged("AAUpdatedUser");
                }
            }
        }
        public String HROverTimeNo
        {
            get { return _hROverTimeNo; }
            set
            {
                if (value != this._hROverTimeNo)
                {
                    _hROverTimeNo = value;
                    NotifyChanged("HROverTimeNo");
                }
            }
        }
        public String HROverTimeName
        {
            get { return _hROverTimeName; }
            set
            {
                if (value != this._hROverTimeName)
                {
                    _hROverTimeName = value;
                    NotifyChanged("HROverTimeName");
                }
            }
        }
        public String HROverTimeDesc
        {
            get { return _hROverTimeDesc; }
            set
            {
                if (value != this._hROverTimeDesc)
                {
                    _hROverTimeDesc = value;
                    NotifyChanged("HROverTimeDesc");
                }
            }
        }
        public DateTime HROverTimeFromDate
        {
            get { return _hROverTimeFromDate; }
            set
            {
                if (value != this._hROverTimeFromDate)
                {
                    _hROverTimeFromDate = value;
                    NotifyChanged("HROverTimeFromDate");
                }
            }
        }
        public DateTime HROverTimeToDate
        {
            get { return _hROverTimeToDate; }
            set
            {
                if (value != this._hROverTimeToDate)
                {
                    _hROverTimeToDate = value;
                    NotifyChanged("HROverTimeToDate");
                }
            }
        }
        public DateTime HROverTimeDate
        {
            get { return _hROverTimeDate; }
            set
            {
                if (value != this._hROverTimeDate)
                {
                    _hROverTimeDate = value;
                    NotifyChanged("HROverTimeDate");
                }
            }
        }
        public String HREmployeeCardNumber
        {
            get { return _hREmployeeCardNumber; }
            set
            {
                if (value != this._hREmployeeCardNumber)
                {
                    _hREmployeeCardNumber = value;
                    NotifyChanged("HREmployeeCardNumber");
                }
            }
        }
        public String HREmployeeName
        {
            get { return _hREmployeeName; }
            set
            {
                if (value != this._hREmployeeName)
                {
                    _hREmployeeName = value;
                    NotifyChanged("HREmployeeName");
                }
            }
        }
        public bool HROverTimeHaveMeal
        {
            get { return _hROverTimeHaveMeal; }
            set
            {
                if (value != this._hROverTimeHaveMeal)
                {
                    _hROverTimeHaveMeal = value;
                    NotifyChanged("HROverTimeHaveMeal");
                }
            }
        }
        public DateTime HROverTimeDateEnd
        {
            get { return _hROverTimeDateEnd; }
            set
            {
                if (value != this._hROverTimeDateEnd)
                {
                    _hROverTimeDateEnd = value;
                    NotifyChanged("HROverTimeDateEnd");
                }
            }
        }
        public int FK_ADWorkingShiftID
        {
            get { return _fK_ADWorkingShiftID; }
            set
            {
                if (value != this._fK_ADWorkingShiftID)
                {
                    _fK_ADWorkingShiftID = value;
                    NotifyChanged("FK_ADWorkingShiftID");
                }
            }
        }
        public String HROverTimeStatus
        {
            get { return _hROverTimeStatus; }
            set
            {
                if (value != this._hROverTimeStatus)
                {
                    _hROverTimeStatus = value;
                    NotifyChanged("HROverTimeStatus");
                }
            }
        }
        public DateTime HROverTimeFromTimeIn
        {
            get { return _hROverTimeFromTimeIn; }
            set
            {
                if (value != this._hROverTimeFromTimeIn)
                {
                    _hROverTimeFromTimeIn = value;
                    NotifyChanged("HROverTimeFromTimeIn");
                }
            }
        }
        public DateTime HROverTimeFromTimeOut
        {
            get { return _hROverTimeFromTimeOut; }
            set
            {
                if (value != this._hROverTimeFromTimeOut)
                {
                    _hROverTimeFromTimeOut = value;
                    NotifyChanged("HROverTimeFromTimeOut");
                }
            }
        }
        public DateTime HROverTimeToTimeIn
        {
            get { return _hROverTimeToTimeIn; }
            set
            {
                if (value != this._hROverTimeToTimeIn)
                {
                    _hROverTimeToTimeIn = value;
                    NotifyChanged("HROverTimeToTimeIn");
                }
            }
        }
        public DateTime HROverTimeToTimeOut
        {
            get { return _hROverTimeToTimeOut; }
            set
            {
                if (value != this._hROverTimeToTimeOut)
                {
                    _hROverTimeToTimeOut = value;
                    NotifyChanged("HROverTimeToTimeOut");
                }
            }
        }
        public int FK_HRTimeSheetParamID
        {
            get { return _fK_HRTimeSheetParamID; }
            set
            {
                if (value != this._fK_HRTimeSheetParamID)
                {
                    _fK_HRTimeSheetParamID = value;
                    NotifyChanged("FK_HRTimeSheetParamID");
                }
            }
        }
        public decimal HROverTimeFactor
        {
            get { return _hROverTimeFactor; }
            set
            {
                if (value != this._hROverTimeFactor)
                {
                    _hROverTimeFactor = value;
                    NotifyChanged("HROverTimeFactor");
                }
            }
        }

        #endregion
        #region Extra Properties
        public int FK_HREmployeeID { get; set; }
        public DateTime HREmployeeRealOutTime { get; set; }

        public string HREmployeeNo { get; set; }
        public string HRDepartmentRoomName { get; set; }
        public string HRDepartmentRoomGroupItemName { get; set; }
        public string HRDepartmentRoomDesc { get; set; }
        public string HRDepartmentRoomGroupItemDesc { get; set; }
        public int rowNumber { get; set; }
        public int OverTime18h25 { get; set; }
        public int OverTime20h { get; set; }
        public int OverTime22h { get; set; }
        public int OverTime0h { get; set; }
        public int OverTime6h { get; set; }
        public int haveMeal { get; set; }
        #endregion
    }
    #endregion
}