using System;
using System.Text;
using System.Collections.Generic;
using VinaLib;
namespace VinaERP
{
    #region HRTimeKeepers
    //-----------------------------------------------------------
    //Generated By: Vina Studio
    //Class:HRTimeKeepersInfo
    //Created Date:Tuesday, June 14, 2016
    //-----------------------------------------------------------

    public class HRTimeKeepersInfo : BusinessObject
    {
        public HRTimeKeepersInfo()
        {
        }
        #region Extra Constructor
        public HRTimeKeepersInfo(string data, DateTime dateIn, DateTime dateOut, int inOutMode, int machineNumber)
        {
            HRTimeKeeperEmployeeCardNo = data;
            HRTimeKeeperDate = dateIn;
            HRTimeKeeperTimeIn = dateIn;
            HRTimeKeeperTimeOut = dateOut;
            FK_HRMachineTimeKeeperID = machineNumber;
            HRTimeKeeperTimeInOutMode = inOutMode;
            EmployeeName = "";
            ThName = "";
            HRTimeKeeperTimeInOutModeName = "";
        }
        #endregion

        #region Variables
        protected int _hRTimeKeeperID;
        protected String _aAStatus = DefaultAAStatus;
        protected String _aACreatedUser = String.Empty;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected String _aAUpdatedUser = String.Empty;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected String _hRTimeKeeperNo = String.Empty;
        protected String _hRTimeKeeperEmployeeNo = String.Empty;
        protected String _hRTimeKeeperEmployeeCardNo = String.Empty;
        protected DateTime _hRTimeKeeperDate = DateTime.MaxValue;
        protected String _hRTimeKeeperSymbol = String.Empty;
        protected DateTime _hRTimeKeeperTimeIn = DateTime.MaxValue;
        protected DateTime _hRTimeKeeperTimeOut = DateTime.MaxValue;
        protected int _fK_HRMachineTimeKeeperID;
        protected int _hRTimeKeeperTimeInOutMode;
        protected String _hRMachineTimeKeeperType = String.Empty;
        protected DateTime _hRTimeKeeperDateCheck = DateTime.MaxValue;
        #endregion

        #region Public properties
        public int HRTimeKeeperID
        {
            get { return _hRTimeKeeperID; }
            set
            {
                if (value != this._hRTimeKeeperID)
                {
                    _hRTimeKeeperID = value;
                    NotifyChanged("HRTimeKeeperID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                    NotifyChanged("AACreatedUser");
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                    NotifyChanged("AACreatedDate");
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                    NotifyChanged("AAUpdatedUser");
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                    NotifyChanged("AAUpdatedDate");
                }
            }
        }
        public String HRTimeKeeperNo
        {
            get { return _hRTimeKeeperNo; }
            set
            {
                if (value != this._hRTimeKeeperNo)
                {
                    _hRTimeKeeperNo = value;
                    NotifyChanged("HRTimeKeeperNo");
                }
            }
        }
        public String HRTimeKeeperEmployeeNo
        {
            get { return _hRTimeKeeperEmployeeNo; }
            set
            {
                if (value != this._hRTimeKeeperEmployeeNo)
                {
                    _hRTimeKeeperEmployeeNo = value;
                    NotifyChanged("HRTimeKeeperEmployeeNo");
                }
            }
        }
        public String HRTimeKeeperEmployeeCardNo
        {
            get { return _hRTimeKeeperEmployeeCardNo; }
            set
            {
                if (value != this._hRTimeKeeperEmployeeCardNo)
                {
                    _hRTimeKeeperEmployeeCardNo = value;
                    NotifyChanged("HRTimeKeeperEmployeeCardNo");
                }
            }
        }
        public DateTime HRTimeKeeperDate
        {
            get { return _hRTimeKeeperDate; }
            set
            {
                if (value != this._hRTimeKeeperDate)
                {
                    _hRTimeKeeperDate = value;
                    NotifyChanged("HRTimeKeeperDate");
                }
            }
        }
        public String HRTimeKeeperSymbol
        {
            get { return _hRTimeKeeperSymbol; }
            set
            {
                if (value != this._hRTimeKeeperSymbol)
                {
                    _hRTimeKeeperSymbol = value;
                    NotifyChanged("HRTimeKeeperSymbol");
                }
            }
        }
        public DateTime HRTimeKeeperTimeIn
        {
            get { return _hRTimeKeeperTimeIn; }
            set
            {
                if (value != this._hRTimeKeeperTimeIn)
                {
                    _hRTimeKeeperTimeIn = value;
                    NotifyChanged("HRTimeKeeperTimeIn");
                }
            }
        }
        public DateTime HRTimeKeeperTimeOut
        {
            get { return _hRTimeKeeperTimeOut; }
            set
            {
                if (value != this._hRTimeKeeperTimeOut)
                {
                    _hRTimeKeeperTimeOut = value;
                    NotifyChanged("HRTimeKeeperTimeOut");
                }
            }
        }
        public int FK_HRMachineTimeKeeperID
        {
            get { return _fK_HRMachineTimeKeeperID; }
            set
            {
                if (value != this._fK_HRMachineTimeKeeperID)
                {
                    _fK_HRMachineTimeKeeperID = value;
                    NotifyChanged("FK_HRMachineTimeKeeperID");
                }
            }
        }
        public int HRTimeKeeperTimeInOutMode
        {
            get { return _hRTimeKeeperTimeInOutMode; }
            set
            {
                if (value != this._hRTimeKeeperTimeInOutMode)
                {
                    _hRTimeKeeperTimeInOutMode = value;
                    NotifyChanged("HRTimeKeeperTimeInOutMode");
                }
            }
        }
        public String HRMachineTimeKeeperType
        {
            get { return _hRMachineTimeKeeperType; }
            set
            {
                if (value != this._hRMachineTimeKeeperType)
                {
                    _hRMachineTimeKeeperType = value;
                    NotifyChanged("HRMachineTimeKeeperType");
                }
            }
        }
        public DateTime HRTimeKeeperDateCheck
        {
            get { return _hRTimeKeeperDateCheck; }
            set
            {
                if (value != this._hRTimeKeeperDateCheck)
                {
                    _hRTimeKeeperDateCheck = value;
                    NotifyChanged("HRTimeKeeperDateCheck");
                }
            }
        }
        #endregion

        #region Extra properties
        public string EmployeeName { get; set; }
        public string ThName { get; set; }
        public string HRTimeKeeperTimeInOutModeName { get; set; }
        public int HRTimeKeeperCompleteID { get; set; }
        public string HRDepartmentRoomName { get; set; }
        public string HRDepartmentRoomGroupItemName { get; set; }
        public string HREmployeePayrollFormulaName { get; set; }
        public DateTime HRTimeKeeperQuickImportDate { get; set; }
        #endregion
    }
    #endregion
}