using System;
using System.Text;
using System.Collections.Generic;
using VinaLib;
namespace VinaERP
{
    #region HRTimeKeeperCompletes
    //-----------------------------------------------------------
    //Generated By: Vina Studio
    //Class:HRTimeKeeperCompletesInfo
    //Created Date:Tuesday, June 14, 2016
    //-----------------------------------------------------------

    public class HRTimeKeeperCompletesInfo : BusinessObject
    {
        public HRTimeKeeperCompletesInfo()
        {
        }
        #region Variables
        protected int _hRTimeKeeperCompleteID;
        protected String _aAStatus = DefaultAAStatus;
        protected String _aACreatedUser = String.Empty;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected String _aAUpdatedUser = String.Empty;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected String _hRTimeKeeperCompletesEmployeeCardNo = String.Empty;
        protected DateTime _hRTimeKeeperCompleteDate = DateTime.MaxValue;
        protected DateTime _hRTimeKeeperCompleteTimeCheck = DateTime.MaxValue;
        protected int _fK_HRMachineTimeKeeperID;
        protected int _hRTimeKeeperCompleteInOutMode;
        protected String _hRTimeKeeperCompleteComment = String.Empty;
        protected int _fK_HRDepartmentID;
        protected int _fK_HRLevelID;
        protected DateTime _hRTimeKeeperCompleteDateCheck = DateTime.MaxValue;
        protected int _fK_HRTimeKeeperID;
        protected int _fK_ADWorkingShiftID;
        protected int _fK_HROverTimeID;

        #endregion

        #region Public properties
        public int HRTimeKeeperCompleteID
        {
            get { return _hRTimeKeeperCompleteID; }
            set
            {
                if (value != this._hRTimeKeeperCompleteID)
                {
                    _hRTimeKeeperCompleteID = value;
                    NotifyChanged("HRTimeKeeperCompleteID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                    NotifyChanged("AACreatedUser");
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                    NotifyChanged("AACreatedDate");
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                    NotifyChanged("AAUpdatedUser");
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                    NotifyChanged("AAUpdatedDate");
                }
            }
        }
        public String HRTimeKeeperCompletesEmployeeCardNo
        {
            get { return _hRTimeKeeperCompletesEmployeeCardNo; }
            set
            {
                if (value != this._hRTimeKeeperCompletesEmployeeCardNo)
                {
                    _hRTimeKeeperCompletesEmployeeCardNo = value;
                    NotifyChanged("HRTimeKeeperCompletesEmployeeCardNo");
                }
            }
        }
        public DateTime HRTimeKeeperCompleteDate
        {
            get { return _hRTimeKeeperCompleteDate; }
            set
            {
                if (value != this._hRTimeKeeperCompleteDate)
                {
                    _hRTimeKeeperCompleteDate = value;
                    NotifyChanged("HRTimeKeeperCompleteDate");
                }
            }
        }
        public DateTime HRTimeKeeperCompleteTimeCheck
        {
            get { return _hRTimeKeeperCompleteTimeCheck; }
            set
            {
                if (value != this._hRTimeKeeperCompleteTimeCheck)
                {
                    _hRTimeKeeperCompleteTimeCheck = value;
                    NotifyChanged("HRTimeKeeperCompleteTimeCheck");
                }
            }
        }
        public int FK_HRMachineTimeKeeperID
        {
            get { return _fK_HRMachineTimeKeeperID; }
            set
            {
                if (value != this._fK_HRMachineTimeKeeperID)
                {
                    _fK_HRMachineTimeKeeperID = value;
                    NotifyChanged("FK_HRMachineTimeKeeperID");
                }
            }
        }
        public int HRTimeKeeperCompleteInOutMode
        {
            get { return _hRTimeKeeperCompleteInOutMode; }
            set
            {
                if (value != this._hRTimeKeeperCompleteInOutMode)
                {
                    _hRTimeKeeperCompleteInOutMode = value;
                    NotifyChanged("HRTimeKeeperCompleteInOutMode");
                }
            }
        }
        public String HRTimeKeeperCompleteComment
        {
            get { return _hRTimeKeeperCompleteComment; }
            set
            {
                if (value != this._hRTimeKeeperCompleteComment)
                {
                    _hRTimeKeeperCompleteComment = value;
                    NotifyChanged("HRTimeKeeperCompleteComment");
                }
            }
        }
        public int FK_HRDepartmentID
        {
            get { return _fK_HRDepartmentID; }
            set
            {
                if (value != this._fK_HRDepartmentID)
                {
                    _fK_HRDepartmentID = value;
                    NotifyChanged("FK_HRDepartmentID");
                }
            }
        }
        public int FK_HRLevelID
        {
            get { return _fK_HRLevelID; }
            set
            {
                if (value != this._fK_HRLevelID)
                {
                    _fK_HRLevelID = value;
                    NotifyChanged("FK_HRLevelID");
                }
            }
        }
        public DateTime HRTimeKeeperCompleteDateCheck
        {
            get { return _hRTimeKeeperCompleteDateCheck; }
            set
            {
                if (value != this._hRTimeKeeperCompleteDateCheck)
                {
                    _hRTimeKeeperCompleteDateCheck = value;
                    NotifyChanged("HRTimeKeeperCompleteDateCheck");
                }
            }
        }
        public int FK_HRTimeKeeperID
        {
            get { return _fK_HRTimeKeeperID; }
            set
            {
                if (value != this._fK_HRTimeKeeperID)
                {
                    _fK_HRTimeKeeperID = value;
                    NotifyChanged("FK_HRTimeKeeperID");
                }
            }
        }
        public int FK_ADWorkingShiftID
        {
            get { return _fK_ADWorkingShiftID; }
            set
            {
                if (value != this._fK_ADWorkingShiftID)
                {
                    _fK_ADWorkingShiftID = value;
                    NotifyChanged("FK_ADWorkingShiftID");
                }
            }
        }
        public int FK_HROverTimeID
        {
            get { return _fK_HROverTimeID; }
            set
            {
                if (value != this._fK_HROverTimeID)
                {
                    _fK_HROverTimeID = value;
                    NotifyChanged("FK_HROverTimeID");
                }
            }
        }

        #endregion

        #region Extra properties
        public string EmployeeName { get; set; }
        public string EmployeeNo { get; set; }
        public string DepartmentName { get; set; }
        public string Thu { get; set; }
        public int STT { get; set; }
        public int RowColor { get; set; }
        public string ThName { get; set; }
        public string HRTimeKeeperCompleteInOutModeName { get; set; }
        public string HRTimeKeeperCompleteMachineName { get; set; }
        public DateTime HRTimeKeeperCompleteTimeCheckOut { get; set; }
        public DateTime DateFrom { get; set; }
        public string DateCheckFrom { get; set; }
        public DateTime DateTo { get; set; }
        public DateTime ScheduleTimeIn { get; set; }
        public DateTime ScheduleTimeOut { get; set; }
        public string SameDateTime { get; set; }
        public string NotInOverTime { get; set; }
        public string OverTimeAbsence { get; set; }
        public DateTime RegisterOverTimeAbsence { get; set; }
        public string HRDepartmentRoomName { get; set; }
        public string HRDepartmentRoomGroupItemName { get; set; }
        public string HREmployeePayrollFormulaName { get; set; }
        public string NotInWorkingShift { get; set; }
        public string LateForWork { get; set; }
        public string GoEarly { get; set; }
        #endregion
    }
    #endregion
}