using System;
using System.Text;
using System.Collections.Generic;
using VinaLib;
namespace VinaERP
{
    #region HRTimeSheets
    //-----------------------------------------------------------
    //Generated By: Vina Studio
    //Class:HRTimeSheetsInfo
    //Created Date:Tuesday, March 29, 2011
    //-----------------------------------------------------------

    public class HRTimeSheetsInfo : BusinessObject
    {
        public HRTimeSheetsInfo()
        {
            EmployeeTimeSheets = new List<HREmployeeTimeSheetsInfo>();
            IsTransferred = false;
        }

        #region Variables
        protected int _hRTimeSheetID;
        protected String _aAStatus = DefaultAAStatus;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected String _aACreatedUser = String.Empty;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected String _aAUpdatedUser = String.Empty;
        protected bool _isTransferred = true;
        protected DateTime _aATransferredDate = DateTime.MaxValue;
        protected int _fK_HREmployeeID;
        protected int _fK_BRBranchID;
        protected String _hRTimeSheetNo = String.Empty;
        protected String _hRTimeSheetName = String.Empty;
        protected String _hRTimeSheetDesc = String.Empty;
        protected DateTime _hRTimeSheetDate = DateTime.MaxValue;
        protected String _hRTimeSheetStatus = DefaultStatus;
        protected String _hRTimeSheetType = String.Empty;
        protected DateTime _hRTimeSheetFromDate = DateTime.MaxValue;
        protected DateTime _hRTimeSheetToDate = DateTime.MaxValue;
        #endregion

        #region Public properties
        public int HRTimeSheetID
        {
            get { return _hRTimeSheetID; }
            set
            {
                if (value != this._hRTimeSheetID)
                {
                    _hRTimeSheetID = value;
                    NotifyChanged("HRTimeSheetID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                    NotifyChanged("AACreatedDate");
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                    NotifyChanged("AACreatedUser");
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                    NotifyChanged("AAUpdatedDate");
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                    NotifyChanged("AAUpdatedUser");
                }
            }
        }
        public bool IsTransferred
        {
            get { return _isTransferred; }
            set
            {
                if (value != this._isTransferred)
                {
                    _isTransferred = value;
                    NotifyChanged("IsTransferred");
                }
            }
        }
        public DateTime AATransferredDate
        {
            get { return _aATransferredDate; }
            set
            {
                if (value != this._aATransferredDate)
                {
                    _aATransferredDate = value;
                    NotifyChanged("AATransferredDate");
                }
            }
        }
        public int FK_HREmployeeID
        {
            get { return _fK_HREmployeeID; }
            set
            {
                if (value != this._fK_HREmployeeID)
                {
                    _fK_HREmployeeID = value;
                    NotifyChanged("FK_HREmployeeID");
                }
            }
        }
        public int FK_BRBranchID
        {
            get { return _fK_BRBranchID; }
            set
            {
                if (value != this._fK_BRBranchID)
                {
                    _fK_BRBranchID = value;
                    NotifyChanged("FK_BRBranchID");
                }
            }
        }
        public String HRTimeSheetNo
        {
            get { return _hRTimeSheetNo; }
            set
            {
                if (value != this._hRTimeSheetNo)
                {
                    _hRTimeSheetNo = value;
                    NotifyChanged("HRTimeSheetNo");
                }
            }
        }
        public String HRTimeSheetName
        {
            get { return _hRTimeSheetName; }
            set
            {
                if (value != this._hRTimeSheetName)
                {
                    _hRTimeSheetName = value;
                    NotifyChanged("HRTimeSheetName");
                }
            }
        }
        public String HRTimeSheetDesc
        {
            get { return _hRTimeSheetDesc; }
            set
            {
                if (value != this._hRTimeSheetDesc)
                {
                    _hRTimeSheetDesc = value;
                    NotifyChanged("HRTimeSheetDesc");
                }
            }
        }
        public DateTime HRTimeSheetDate
        {
            get { return _hRTimeSheetDate; }
            set
            {
                if (value != this._hRTimeSheetDate)
                {
                    _hRTimeSheetDate = value;
                    NotifyChanged("HRTimeSheetDate");
                }
            }
        }
        public String HRTimeSheetStatus
        {
            get { return _hRTimeSheetStatus; }
            set
            {
                if (value != this._hRTimeSheetStatus)
                {
                    _hRTimeSheetStatus = value;
                    NotifyChanged("HRTimeSheetStatus");
                }
            }
        }
        public String HRTimeSheetType
        {
            get { return _hRTimeSheetType; }
            set
            {
                if (value != this._hRTimeSheetType)
                {
                    _hRTimeSheetType = value;
                    NotifyChanged("HRTimeSheetType");
                }
            }
        }
        public DateTime HRTimeSheetFromDate
        {
            get { return _hRTimeSheetFromDate; }
            set
            {
                if (value != this._hRTimeSheetFromDate)
                {
                    _hRTimeSheetFromDate = value;
                    NotifyChanged("HRTimeSheetFromDate");
                }
            }
        }
        public DateTime HRTimeSheetToDate
        {
            get { return _hRTimeSheetToDate; }
            set
            {
                if (value != this._hRTimeSheetToDate)
                {
                    _hRTimeSheetToDate = value;
                    NotifyChanged("HRTimeSheetToDate");
                }
            }
        }
        #endregion


        #region Extra Properties
        public byte[] HRTimeSheetEmployeePicture { get; set; }
        public String HREmployeeCardNumber { get; set; }

        /// <summary>
        /// Gets or sets the time sheets of employees
        /// </summary>
        public List<HREmployeeTimeSheetsInfo> EmployeeTimeSheets { get; set; }

        public DateTime HRTimeSheetDateFrom { get; set; }
        public DateTime HRTimeSheetDateTo { get; set; }
        #endregion
    }
    #endregion
}