using System;
using System.Text;
using System.Collections.Generic;
using VinaLib;
namespace VinaERP
{
    #region HRTimesheetConfigs
    //-----------------------------------------------------------
    //Generated By: Vina Studio
    //Class:HRTimesheetConfigsInfo
    //Created Date:Tuesday, June 14, 2016
    //-----------------------------------------------------------

    public class HRTimesheetConfigsInfo : BusinessObject
    {
        public HRTimesheetConfigsInfo()
        {
        }
        #region Variables
        protected int _hRTimesheetConfigID;
        protected String _aAStatus = DefaultAAStatus;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected String _aACreatedUser = String.Empty;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected String _aAUpdatedUser = String.Empty;
        protected int _fK_HRTimesheetGroupID;
        protected int _hRTimesheetConfigJan;
        protected int _hRTimesheetConfigFeb;
        protected int _hRTimesheetConfigMar;
        protected int _hRTimesheetConfigApr;
        protected int _hRTimesheetConfigMay;
        protected int _hRTimesheetConfigJun;
        protected int _hRTimesheetConfigJul;
        protected int _hRTimesheetConfigAug;
        protected int _hRTimesheetConfigSep;
        protected int _hRTimesheetConfigOct;
        protected int _hRTimesheetConfigNov;
        protected int _hRTimesheetConfigDec;
        protected int _fK_HREmployeePayrollFormulaID;
        protected DateTime _hRTimesheetConfigYear = DateTime.MaxValue;
        #endregion

        #region Public properties
        public int HRTimesheetConfigID
        {
            get { return _hRTimesheetConfigID; }
            set
            {
                if (value != this._hRTimesheetConfigID)
                {
                    _hRTimesheetConfigID = value;
                    NotifyChanged("HRTimesheetConfigID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                    NotifyChanged("AACreatedDate");
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                    NotifyChanged("AACreatedUser");
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                    NotifyChanged("AAUpdatedDate");
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                    NotifyChanged("AAUpdatedUser");
                }
            }
        }
        public int FK_HRTimesheetGroupID
        {
            get { return _fK_HRTimesheetGroupID; }
            set
            {
                if (value != this._fK_HRTimesheetGroupID)
                {
                    _fK_HRTimesheetGroupID = value;
                    NotifyChanged("FK_HRTimesheetGroupID");
                }
            }
        }
        public int HRTimesheetConfigJan
        {
            get { return _hRTimesheetConfigJan; }
            set
            {
                if (value != this._hRTimesheetConfigJan)
                {
                    _hRTimesheetConfigJan = value;
                    NotifyChanged("HRTimesheetConfigJan");
                }
            }
        }
        public int HRTimesheetConfigFeb
        {
            get { return _hRTimesheetConfigFeb; }
            set
            {
                if (value != this._hRTimesheetConfigFeb)
                {
                    _hRTimesheetConfigFeb = value;
                    NotifyChanged("HRTimesheetConfigFeb");
                }
            }
        }
        public int HRTimesheetConfigMar
        {
            get { return _hRTimesheetConfigMar; }
            set
            {
                if (value != this._hRTimesheetConfigMar)
                {
                    _hRTimesheetConfigMar = value;
                    NotifyChanged("HRTimesheetConfigMar");
                }
            }
        }
        public int HRTimesheetConfigApr
        {
            get { return _hRTimesheetConfigApr; }
            set
            {
                if (value != this._hRTimesheetConfigApr)
                {
                    _hRTimesheetConfigApr = value;
                    NotifyChanged("HRTimesheetConfigApr");
                }
            }
        }
        public int HRTimesheetConfigMay
        {
            get { return _hRTimesheetConfigMay; }
            set
            {
                if (value != this._hRTimesheetConfigMay)
                {
                    _hRTimesheetConfigMay = value;
                    NotifyChanged("HRTimesheetConfigMay");
                }
            }
        }
        public int HRTimesheetConfigJun
        {
            get { return _hRTimesheetConfigJun; }
            set
            {
                if (value != this._hRTimesheetConfigJun)
                {
                    _hRTimesheetConfigJun = value;
                    NotifyChanged("HRTimesheetConfigJun");
                }
            }
        }
        public int HRTimesheetConfigJul
        {
            get { return _hRTimesheetConfigJul; }
            set
            {
                if (value != this._hRTimesheetConfigJul)
                {
                    _hRTimesheetConfigJul = value;
                    NotifyChanged("HRTimesheetConfigJul");
                }
            }
        }
        public int HRTimesheetConfigAug
        {
            get { return _hRTimesheetConfigAug; }
            set
            {
                if (value != this._hRTimesheetConfigAug)
                {
                    _hRTimesheetConfigAug = value;
                    NotifyChanged("HRTimesheetConfigAug");
                }
            }
        }
        public int HRTimesheetConfigSep
        {
            get { return _hRTimesheetConfigSep; }
            set
            {
                if (value != this._hRTimesheetConfigSep)
                {
                    _hRTimesheetConfigSep = value;
                    NotifyChanged("HRTimesheetConfigSep");
                }
            }
        }
        public int HRTimesheetConfigOct
        {
            get { return _hRTimesheetConfigOct; }
            set
            {
                if (value != this._hRTimesheetConfigOct)
                {
                    _hRTimesheetConfigOct = value;
                    NotifyChanged("HRTimesheetConfigOct");
                }
            }
        }
        public int HRTimesheetConfigNov
        {
            get { return _hRTimesheetConfigNov; }
            set
            {
                if (value != this._hRTimesheetConfigNov)
                {
                    _hRTimesheetConfigNov = value;
                    NotifyChanged("HRTimesheetConfigNov");
                }
            }
        }
        public int HRTimesheetConfigDec
        {
            get { return _hRTimesheetConfigDec; }
            set
            {
                if (value != this._hRTimesheetConfigDec)
                {
                    _hRTimesheetConfigDec = value;
                    NotifyChanged("HRTimesheetConfigDec");
                }
            }
        }
        public int FK_HREmployeePayrollFormulaID
        {
            get { return _fK_HREmployeePayrollFormulaID; }
            set
            {
                if (value != this._fK_HREmployeePayrollFormulaID)
                {
                    _fK_HREmployeePayrollFormulaID = value;
                    NotifyChanged("FK_HREmployeePayrollFormulaID");
                }
            }
        }
        public DateTime HRTimesheetConfigYear
        {
            get { return _hRTimesheetConfigYear; }
            set
            {
                if (value != this._hRTimesheetConfigYear)
                {
                    _hRTimesheetConfigYear = value;
                    NotifyChanged("HRTimesheetConfigYear");
                }
            }
        }
        #endregion
        public string HRTimesheetGroupName { get; set; }
        public int HRTimesheetGroupID { get; set; }
    }
    #endregion
}