using System;
using System.Text;
using System.Collections.Generic;

namespace VinaLib
{
    #region ADConfigValues
    //-----------------------------------------------------------
    //Generated By:VinaERP Studio
    //Class:ADConfigValuesInfo
    //Created Date:Saturday, November 10, 2018
    //-----------------------------------------------------------

    public class ADConfigValuesInfo : BusinessObject
    {
        public ADConfigValuesInfo()
        {
        }
        #region Variables
        protected int _aDConfigValueID;
        protected String _aAStatus = DefaultAAStatus;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected String _aACreatedUser = String.Empty;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected String _aAUpdatedUser = String.Empty;
        protected String _aDConfigKey = String.Empty;
        protected String _aDConfigKeyGroup = String.Empty;
        protected String _aDConfigKeyValue = String.Empty;
        protected String _aDConfigText = String.Empty;
        protected int _aDConfigKeySortOrder;
        protected bool _aDConfigKeyIsActive = true;
        #endregion

        #region Public properties
        public int ADConfigValueID
        {
            get { return _aDConfigValueID; }
            set
            {
                if (value != this._aDConfigValueID)
                {
                    _aDConfigValueID = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                }
            }
        }
        public String ADConfigKey
        {
            get { return _aDConfigKey; }
            set
            {
                if (value != this._aDConfigKey)
                {
                    _aDConfigKey = value;
                }
            }
        }
        public String ADConfigKeyGroup
        {
            get { return _aDConfigKeyGroup; }
            set
            {
                if (value != this._aDConfigKeyGroup)
                {
                    _aDConfigKeyGroup = value;
                }
            }
        }
        public String ADConfigKeyValue
        {
            get { return _aDConfigKeyValue; }
            set
            {
                if (value != this._aDConfigKeyValue)
                {
                    _aDConfigKeyValue = value;
                }
            }
        }
        public String ADConfigText
        {
            get { return _aDConfigText; }
            set
            {
                if (value != this._aDConfigText)
                {
                    _aDConfigText = value;
                }
            }
        }
        public int ADConfigKeySortOrder
        {
            get { return _aDConfigKeySortOrder; }
            set
            {
                if (value != this._aDConfigKeySortOrder)
                {
                    _aDConfigKeySortOrder = value;
                }
            }
        }
        public bool ADConfigKeyIsActive
        {
            get { return _aDConfigKeyIsActive; }
            set
            {
                if (value != this._aDConfigKeyIsActive)
                {
                    _aDConfigKeyIsActive = value;
                }
            }
        }
        #endregion
    }
    #endregion
}