using System;
using System.Text;
using System.Collections.Generic;
namespace VinaLib
{
    #region ADUserGroups
    //-----------------------------------------------------------
    //Generated By:VinaERP Studio
    //Class:ADUserGroupsInfo
    //Created Date:Thursday, November 15, 2018
    //-----------------------------------------------------------

    public class ADUserGroupsInfo : BusinessObject
    {
        public ADUserGroupsInfo()
        {
        }
        #region Variables
        protected int _aDUserGroupID;
        protected String _aAStatus = DefaultAAStatus;
        protected String _aDUserGroupSkinName = String.Empty;
        protected String _aDUserGroupName = String.Empty;
        protected String _aDUserGroupDesc = String.Empty;
        #endregion

        #region Public properties
        public int ADUserGroupID
        {
            get { return _aDUserGroupID; }
            set
            {
                if (value != this._aDUserGroupID)
                {
                    _aDUserGroupID = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public String ADUserGroupSkinName
        {
            get { return _aDUserGroupSkinName; }
            set
            {
                if (value != this._aDUserGroupSkinName)
                {
                    _aDUserGroupSkinName = value;
                }
            }
        }
        public String ADUserGroupName
        {
            get { return _aDUserGroupName; }
            set
            {
                if (value != this._aDUserGroupName)
                {
                    _aDUserGroupName = value;
                }
            }
        }
        public String ADUserGroupDesc
        {
            get { return _aDUserGroupDesc; }
            set
            {
                if (value != this._aDUserGroupDesc)
                {
                    _aDUserGroupDesc = value;
                }
            }
        }
        #endregion
    }
    #endregion
}