using System;
using System.Text;
using System.Collections.Generic;

namespace VinaLib
{
    #region ADUsers
    //-----------------------------------------------------------
    //Generated By:VinaERP Studio
    //Class:ADUsersInfo
    //Created Date:Monday, December 3, 2018
    //-----------------------------------------------------------

    public class ADUsersInfo : BusinessObject
    {
        public ADUsersInfo()
        {
        }
        #region Variables
        protected int _aDUserID;
        protected String _aAStatus = DefaultAAStatus;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected int _fK_ADUserGroupID;
        protected String _aDUserName = String.Empty;
        protected String _aDPassword = String.Empty;
        protected bool _aDUserActiveCheck = true;
        protected String _aDUserStyle = String.Empty;
        protected String _aDUserStyleSkin = String.Empty;
        protected int _fK_HREmployeeID;
        #endregion

        #region Public properties
        public int ADUserID
        {
            get { return _aDUserID; }
            set
            {
                if (value != this._aDUserID)
                {
                    _aDUserID = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                }
            }
        }
        public int FK_ADUserGroupID
        {
            get { return _fK_ADUserGroupID; }
            set
            {
                if (value != this._fK_ADUserGroupID)
                {
                    _fK_ADUserGroupID = value;
                }
            }
        }
        public String ADUserName
        {
            get { return _aDUserName; }
            set
            {
                if (value != this._aDUserName)
                {
                    _aDUserName = value;
                }
            }
        }
        public String ADPassword
        {
            get { return _aDPassword; }
            set
            {
                if (value != this._aDPassword)
                {
                    _aDPassword = value;
                }
            }
        }
        public bool ADUserActiveCheck
        {
            get { return _aDUserActiveCheck; }
            set
            {
                if (value != this._aDUserActiveCheck)
                {
                    _aDUserActiveCheck = value;
                }
            }
        }
        public String ADUserStyle
        {
            get { return _aDUserStyle; }
            set
            {
                if (value != this._aDUserStyle)
                {
                    _aDUserStyle = value;
                }
            }
        }
        public String ADUserStyleSkin
        {
            get { return _aDUserStyleSkin; }
            set
            {
                if (value != this._aDUserStyleSkin)
                {
                    _aDUserStyleSkin = value;
                }
            }
        }
        public int FK_HREmployeeID
        {
            get { return _fK_HREmployeeID; }
            set
            {
                if (value != this._fK_HREmployeeID)
                {
                    _fK_HREmployeeID = value;
                }
            }
        }
        #endregion
    }
    #endregion
}