using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using VinaLib;
using System.Collections;

namespace VinaERP
{
    #region STColumns
    //-----------------------------------------------------------
    //Generated By:VinaERP Studio
    //Class:STColumnsController
    //Created Date:Sunday, November 11, 2018
    //-----------------------------------------------------------

    public class STColumnsController : BaseBusinessController
    {
        public STColumnsController()
        {
            dal = new DALBaseProvider("STColumns", typeof(STColumnsInfo));
        }

        public override IList GetListFromDataSet(DataSet ds)
        {
            List<STColumnsInfo> columns = new List<STColumnsInfo>();
            if (ds.Tables.Count > 0)
            {
                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    STColumnsInfo objColumnsInfo = (STColumnsInfo)GetObjectFromDataRow(row);
                    columns.Add(objColumnsInfo);
                }
            }
            return columns;
        }

        public void DeleteByScreenIDAndControlName(int screenID, string controlName)
        {
            DataSet ds = this.GetDataSet(string.Format("DELETE FROM STColumns WHERE FK_STScreenID = {0} AND STColumnControlName = '{1}'", (object)screenID, (object)controlName));

            return;
        }

        public List<STColumnsInfo> GetColumnsByScreenIDAndControlName(int screenID, string controlName)
        {
            DataSet ds = this.GetDataSet(string.Format("SELECT * FROM STColumns WHERE FK_STScreenID = {0} AND STColumnControlName = '{1}' ORDER BY STColumnVisibleIndex", (object)screenID, (object)controlName));

            return (List<STColumnsInfo>)GetListFromDataSet(ds);
        }
    }
    #endregion
}