using System;
using System.Text;
using System.Collections.Generic;
using VinaLib;
namespace VinaERP
{
    #region ARCustomerPayments
    //-----------------------------------------------------------
    //Generated By:VinaERP Studio
    //Class:ARCustomerPaymentsInfo
    //Created Date:Friday, May 31, 2019
    //-----------------------------------------------------------

    public class ARCustomerPaymentsInfo : BusinessObject
    {
        public ARCustomerPaymentsInfo()
        {
        }
        #region Variables
        protected int _aRCustomerPaymentID;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected String _aACreatedUser = String.Empty;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected String _aAUpdatedUser = String.Empty;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_ARCustomerID;
        protected int _fK_GECurrencyID;
        protected int _fK_HREmployeeID;
        protected String _aRCustomerPaymentNo = String.Empty;
        protected String _aRCustomerPaymentName = String.Empty;
        protected String _aRCustomerPaymentDesc = String.Empty;
        protected DateTime _aRCustomerPaymentDate = DateTime.MaxValue;
        protected String _aRCustomerPaymentType = String.Empty;
        protected String _aRCustomerPaymentStatus = DefaultStatus;
        protected String _aRCustomerPaymentPaymentMethodType = String.Empty;
        protected decimal _aRCustomerPaymentExchangeRate;
        protected decimal _aRCustomerPaymentTotalAmount;
        protected decimal _aRCustomerPaymentExchangeAmount;
        protected String _aRCustomerPaymentSenderName = String.Empty;
        #endregion

        #region Public properties
        public int ARCustomerPaymentID
        {
            get { return _aRCustomerPaymentID; }
            set
            {
                if (value != this._aRCustomerPaymentID)
                {
                    _aRCustomerPaymentID = value;
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public int FK_ARCustomerID
        {
            get { return _fK_ARCustomerID; }
            set
            {
                if (value != this._fK_ARCustomerID)
                {
                    _fK_ARCustomerID = value;
                }
            }
        }
        public int FK_GECurrencyID
        {
            get { return _fK_GECurrencyID; }
            set
            {
                if (value != this._fK_GECurrencyID)
                {
                    _fK_GECurrencyID = value;
                }
            }
        }
        public int FK_HREmployeeID
        {
            get { return _fK_HREmployeeID; }
            set
            {
                if (value != this._fK_HREmployeeID)
                {
                    _fK_HREmployeeID = value;
                }
            }
        }
        public String ARCustomerPaymentNo
        {
            get { return _aRCustomerPaymentNo; }
            set
            {
                if (value != this._aRCustomerPaymentNo)
                {
                    _aRCustomerPaymentNo = value;
                }
            }
        }
        public String ARCustomerPaymentName
        {
            get { return _aRCustomerPaymentName; }
            set
            {
                if (value != this._aRCustomerPaymentName)
                {
                    _aRCustomerPaymentName = value;
                }
            }
        }
        public String ARCustomerPaymentDesc
        {
            get { return _aRCustomerPaymentDesc; }
            set
            {
                if (value != this._aRCustomerPaymentDesc)
                {
                    _aRCustomerPaymentDesc = value;
                }
            }
        }
        public DateTime ARCustomerPaymentDate
        {
            get { return _aRCustomerPaymentDate; }
            set
            {
                if (value != this._aRCustomerPaymentDate)
                {
                    _aRCustomerPaymentDate = value;
                }
            }
        }
        public String ARCustomerPaymentType
        {
            get { return _aRCustomerPaymentType; }
            set
            {
                if (value != this._aRCustomerPaymentType)
                {
                    _aRCustomerPaymentType = value;
                }
            }
        }
        public String ARCustomerPaymentStatus
        {
            get { return _aRCustomerPaymentStatus; }
            set
            {
                if (value != this._aRCustomerPaymentStatus)
                {
                    _aRCustomerPaymentStatus = value;
                }
            }
        }
        public String ARCustomerPaymentPaymentMethodType
        {
            get { return _aRCustomerPaymentPaymentMethodType; }
            set
            {
                if (value != this._aRCustomerPaymentPaymentMethodType)
                {
                    _aRCustomerPaymentPaymentMethodType = value;
                }
            }
        }
        public decimal ARCustomerPaymentExchangeRate
        {
            get { return _aRCustomerPaymentExchangeRate; }
            set
            {
                if (value != this._aRCustomerPaymentExchangeRate)
                {
                    _aRCustomerPaymentExchangeRate = value;
                }
            }
        }
        public decimal ARCustomerPaymentTotalAmount
        {
            get { return _aRCustomerPaymentTotalAmount; }
            set
            {
                if (value != this._aRCustomerPaymentTotalAmount)
                {
                    _aRCustomerPaymentTotalAmount = value;
                }
            }
        }
        public decimal ARCustomerPaymentExchangeAmount
        {
            get { return _aRCustomerPaymentExchangeAmount; }
            set
            {
                if (value != this._aRCustomerPaymentExchangeAmount)
                {
                    _aRCustomerPaymentExchangeAmount = value;
                }
            }
        }
        public String ARCustomerPaymentSenderName
        {
            get { return _aRCustomerPaymentSenderName; }
            set
            {
                if (value != this._aRCustomerPaymentSenderName)
                {
                    _aRCustomerPaymentSenderName = value;
                }
            }
        }
        #endregion
    }
    #endregion
}