using System;
using System.Text;
using System.Collections.Generic;
using VinaLib;
namespace VinaERP
{
    #region ARCustomerPaymentDetails
    //-----------------------------------------------------------
    //Generated By:VinaERP Studio
    //Class:ARCustomerPaymentDetailsInfo
    //Created Date:Sunday, June 2, 2019
    //-----------------------------------------------------------

    public class ARCustomerPaymentDetailsInfo : BusinessObject
    {
        public ARCustomerPaymentDetailsInfo()
        {
        }
        #region Variables
        protected int _aRCustomerPaymentDetailID;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_ARCustomerPaymentID;
        protected String _aRCustomerPaymentDetailPaymentMethodType = String.Empty;
        protected decimal _aRCustomerPaymentDetailAmount;
        protected String _aRCustomerPaymentDetailInfo = String.Empty;
        #endregion

        #region Public properties
        public int ARCustomerPaymentDetailID
        {
            get { return _aRCustomerPaymentDetailID; }
            set
            {
                if (value != this._aRCustomerPaymentDetailID)
                {
                    _aRCustomerPaymentDetailID = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public int FK_ARCustomerPaymentID
        {
            get { return _fK_ARCustomerPaymentID; }
            set
            {
                if (value != this._fK_ARCustomerPaymentID)
                {
                    _fK_ARCustomerPaymentID = value;
                }
            }
        }
        public String ARCustomerPaymentDetailPaymentMethodType
        {
            get { return _aRCustomerPaymentDetailPaymentMethodType; }
            set
            {
                if (value != this._aRCustomerPaymentDetailPaymentMethodType)
                {
                    _aRCustomerPaymentDetailPaymentMethodType = value;
                }
            }
        }
        public decimal ARCustomerPaymentDetailAmount
        {
            get { return _aRCustomerPaymentDetailAmount; }
            set
            {
                if (value != this._aRCustomerPaymentDetailAmount)
                {
                    _aRCustomerPaymentDetailAmount = value;
                }
            }
        }
        public String ARCustomerPaymentDetailInfo
        {
            get { return _aRCustomerPaymentDetailInfo; }
            set
            {
                if (value != this._aRCustomerPaymentDetailInfo)
                {
                    _aRCustomerPaymentDetailInfo = value;
                }
            }
        }
        #endregion


        #region Extra Properties
        public string ARCustomerPaymentDetailPaymentMethodDisplayText { get; set; }
        #endregion
    }
    #endregion
}