using System;
using System.Text;
using System.Collections.Generic;
using VinaLib;
namespace VinaERP
{
    #region ARInvoiceItems
    //-----------------------------------------------------------
    //Generated By:VinaERP Studio
    //Class:ARInvoiceItemsInfo
    //Created Date:Thursday, December 6, 2018
    //-----------------------------------------------------------

    public class ARInvoiceItemsInfo : BusinessObject
    {
        public ARInvoiceItemsInfo()
        {
        }
        #region Variables
        protected int _aRInvoiceItemID;
        protected String _aAStatus = DefaultAAStatus;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected String _aACreatedUser = String.Empty;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected String _aAUpdatedUser = String.Empty;
        protected int _fK_ARInvoiceID;
        protected int _fK_ICDepartmentID;
        protected int _fK_ICProductGroupID;
        protected int _fK_ICProductID;
        protected int _fK_ICMeasureUnitID;
        protected String _aRInvoiceItemProductNo = String.Empty;
        protected String _aRInvoiceItemProductName = String.Empty;
        protected String _aRInvoiceItemProductDesc = String.Empty;
        protected String _aRInvoiceItemProductType = String.Empty;
        protected decimal _aRInvoiceItemProductUnitPrice;
        protected decimal _aRInvoiceItemDiscountPercent;
        protected decimal _aRInvoiceItemDiscountAmount;
        protected decimal _aRInvoiceItemTaxPercent;
        protected decimal _aRInvoiceItemTaxAmount;
        protected decimal _aRInvoiceItemTotalAmount;
        protected int _fK_ICShipmentItemID;
        protected decimal _aRInvoiceItemProductQty;
        #endregion

        #region Public properties
        public int ARInvoiceItemID
        {
            get { return _aRInvoiceItemID; }
            set
            {
                if (value != this._aRInvoiceItemID)
                {
                    _aRInvoiceItemID = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                }
            }
        }
        public int FK_ARInvoiceID
        {
            get { return _fK_ARInvoiceID; }
            set
            {
                if (value != this._fK_ARInvoiceID)
                {
                    _fK_ARInvoiceID = value;
                }
            }
        }
        public int FK_ICDepartmentID
        {
            get { return _fK_ICDepartmentID; }
            set
            {
                if (value != this._fK_ICDepartmentID)
                {
                    _fK_ICDepartmentID = value;
                }
            }
        }
        public int FK_ICProductGroupID
        {
            get { return _fK_ICProductGroupID; }
            set
            {
                if (value != this._fK_ICProductGroupID)
                {
                    _fK_ICProductGroupID = value;
                }
            }
        }
        public int FK_ICProductID
        {
            get { return _fK_ICProductID; }
            set
            {
                if (value != this._fK_ICProductID)
                {
                    _fK_ICProductID = value;
                }
            }
        }
        public int FK_ICMeasureUnitID
        {
            get { return _fK_ICMeasureUnitID; }
            set
            {
                if (value != this._fK_ICMeasureUnitID)
                {
                    _fK_ICMeasureUnitID = value;
                }
            }
        }
        public String ARInvoiceItemProductNo
        {
            get { return _aRInvoiceItemProductNo; }
            set
            {
                if (value != this._aRInvoiceItemProductNo)
                {
                    _aRInvoiceItemProductNo = value;
                }
            }
        }
        public String ARInvoiceItemProductName
        {
            get { return _aRInvoiceItemProductName; }
            set
            {
                if (value != this._aRInvoiceItemProductName)
                {
                    _aRInvoiceItemProductName = value;
                }
            }
        }
        public String ARInvoiceItemProductDesc
        {
            get { return _aRInvoiceItemProductDesc; }
            set
            {
                if (value != this._aRInvoiceItemProductDesc)
                {
                    _aRInvoiceItemProductDesc = value;
                }
            }
        }
        public String ARInvoiceItemProductType
        {
            get { return _aRInvoiceItemProductType; }
            set
            {
                if (value != this._aRInvoiceItemProductType)
                {
                    _aRInvoiceItemProductType = value;
                }
            }
        }
        public decimal ARInvoiceItemProductUnitPrice
        {
            get { return _aRInvoiceItemProductUnitPrice; }
            set
            {
                if (value != this._aRInvoiceItemProductUnitPrice)
                {
                    _aRInvoiceItemProductUnitPrice = value;
                }
            }
        }
        public decimal ARInvoiceItemDiscountPercent
        {
            get { return _aRInvoiceItemDiscountPercent; }
            set
            {
                if (value != this._aRInvoiceItemDiscountPercent)
                {
                    _aRInvoiceItemDiscountPercent = value;
                }
            }
        }
        public decimal ARInvoiceItemDiscountAmount
        {
            get { return _aRInvoiceItemDiscountAmount; }
            set
            {
                if (value != this._aRInvoiceItemDiscountAmount)
                {
                    _aRInvoiceItemDiscountAmount = value;
                }
            }
        }
        public decimal ARInvoiceItemTaxPercent
        {
            get { return _aRInvoiceItemTaxPercent; }
            set
            {
                if (value != this._aRInvoiceItemTaxPercent)
                {
                    _aRInvoiceItemTaxPercent = value;
                }
            }
        }
        public decimal ARInvoiceItemTaxAmount
        {
            get { return _aRInvoiceItemTaxAmount; }
            set
            {
                if (value != this._aRInvoiceItemTaxAmount)
                {
                    _aRInvoiceItemTaxAmount = value;
                }
            }
        }
        public decimal ARInvoiceItemTotalAmount
        {
            get { return _aRInvoiceItemTotalAmount; }
            set
            {
                if (value != this._aRInvoiceItemTotalAmount)
                {
                    _aRInvoiceItemTotalAmount = value;
                }
            }
        }
        public int FK_ICShipmentItemID
        {
            get { return _fK_ICShipmentItemID; }
            set
            {
                if (value != this._fK_ICShipmentItemID)
                {
                    _fK_ICShipmentItemID = value;
                }
            }
        }
        public decimal ARInvoiceItemProductQty
        {
            get { return _aRInvoiceItemProductQty; }
            set
            {
                if (value != this._aRInvoiceItemProductQty)
                {
                    _aRInvoiceItemProductQty = value;
                }
            }
        }
        #endregion

        public String ICMeasureUnitName { get; set; }
    }
    #endregion
}