using System;
using System.Text;
using System.Collections.Generic;
using VinaLib;
namespace VinaERP
{
    #region ARSaleOrders
    //-----------------------------------------------------------
    //Generated By:VinaERP Studio
    //Class:ARSaleOrdersInfo
    //Created Date:Monday, December 3, 2018
    //-----------------------------------------------------------

    public class ARSaleOrdersInfo : BusinessObject
    {
        public ARSaleOrdersInfo()
        {
        }
        #region Variables
        protected int _aRSaleOrderID;
        protected String _aAStatus = DefaultAAStatus;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected String _aACreatedUser = String.Empty;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected String _aAUpdatedUser = String.Empty;
        protected int _fK_ARCustomerID;
        protected String _aRSaleOrderNo = String.Empty;
        protected String _aRSaleOrderName = String.Empty;
        protected String _aRSaleOrderDesc = String.Empty;
        protected DateTime _aRSaleOrderDate = DateTime.MaxValue;
        protected DateTime _aRSaleOrderDeliveryDate = DateTime.MaxValue;
        protected decimal _aRSaleOrderDiscountPercent;
        protected decimal _aRSaleOrderDiscountAmount;
        protected decimal _aRSaleOrderTaxPercent;
        protected decimal _aRSaleOrderTaxAmount;
        protected decimal _aRSaleOrderBeforeDiscountAmount;
        protected decimal _aRSaleOrderAfterDiscountAmount;
        protected decimal _aRSaleOrderTotalAmount;
        protected decimal _aRSaleOrderDepositAmount;
        protected decimal _aRSaleOrderBalanceDue;
        protected DateTime _aRSaleOrderPaymentDate = DateTime.MaxValue;
        protected String _aRSaleOrderType = String.Empty;
        protected String _aRSaleOrderStatus = DefaultStatus;
        protected String _aRSaleOrderCustomerName = String.Empty;
        protected String _aRSaleOrderCustomerPhone = String.Empty;
        protected String _aRSaleOrderCustomerTaxCode = String.Empty;
        protected String _aRSaleOrderCustomerAddress = String.Empty;
        protected String _aRSaleOrderCustomerDeliveryName = String.Empty;
        protected String _aRSaleOrderCustomerDeliveryPhone = String.Empty;
        protected String _aRSaleOrderCustomerDeliveryAddress = String.Empty;
        protected String _aRSaleOrderPaymentMethodType = String.Empty;
        protected String _aRSaleOrderPaymentTerm = String.Empty;
        protected int _fK_GECurrencyID;
        protected decimal _aRSaleOrderExchangeRate;
        protected int _fK_GEPaymentTermID;
        protected decimal _aRSaleOrderSubTotalAmount;
        protected int _fK_HREmployeeID;
        protected int _fK_HRSellerEmployeeID;
        protected String _aRSaleOrderComment = String.Empty;
        protected String _aRSaleOrderInternalComment = String.Empty;
        protected int _fK_ARProposalID;
        #endregion

        #region Public properties
        public int ARSaleOrderID
        {
            get { return _aRSaleOrderID; }
            set
            {
                if (value != this._aRSaleOrderID)
                {
                    _aRSaleOrderID = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                }
            }
        }
        public int FK_ARCustomerID
        {
            get { return _fK_ARCustomerID; }
            set
            {
                if (value != this._fK_ARCustomerID)
                {
                    _fK_ARCustomerID = value;
                }
            }
        }
        public String ARSaleOrderNo
        {
            get { return _aRSaleOrderNo; }
            set
            {
                if (value != this._aRSaleOrderNo)
                {
                    _aRSaleOrderNo = value;
                }
            }
        }
        public String ARSaleOrderName
        {
            get { return _aRSaleOrderName; }
            set
            {
                if (value != this._aRSaleOrderName)
                {
                    _aRSaleOrderName = value;
                }
            }
        }
        public String ARSaleOrderDesc
        {
            get { return _aRSaleOrderDesc; }
            set
            {
                if (value != this._aRSaleOrderDesc)
                {
                    _aRSaleOrderDesc = value;
                }
            }
        }
        public DateTime ARSaleOrderDate
        {
            get { return _aRSaleOrderDate; }
            set
            {
                if (value != this._aRSaleOrderDate)
                {
                    _aRSaleOrderDate = value;
                }
            }
        }
        public DateTime ARSaleOrderDeliveryDate
        {
            get { return _aRSaleOrderDeliveryDate; }
            set
            {
                if (value != this._aRSaleOrderDeliveryDate)
                {
                    _aRSaleOrderDeliveryDate = value;
                }
            }
        }
        public decimal ARSaleOrderDiscountPercent
        {
            get { return _aRSaleOrderDiscountPercent; }
            set
            {
                if (value != this._aRSaleOrderDiscountPercent)
                {
                    _aRSaleOrderDiscountPercent = value;
                }
            }
        }
        public decimal ARSaleOrderDiscountAmount
        {
            get { return _aRSaleOrderDiscountAmount; }
            set
            {
                if (value != this._aRSaleOrderDiscountAmount)
                {
                    _aRSaleOrderDiscountAmount = value;
                }
            }
        }
        public decimal ARSaleOrderTaxPercent
        {
            get { return _aRSaleOrderTaxPercent; }
            set
            {
                if (value != this._aRSaleOrderTaxPercent)
                {
                    _aRSaleOrderTaxPercent = value;
                }
            }
        }
        public decimal ARSaleOrderTaxAmount
        {
            get { return _aRSaleOrderTaxAmount; }
            set
            {
                if (value != this._aRSaleOrderTaxAmount)
                {
                    _aRSaleOrderTaxAmount = value;
                }
            }
        }
        public decimal ARSaleOrderBeforeDiscountAmount
        {
            get { return _aRSaleOrderBeforeDiscountAmount; }
            set
            {
                if (value != this._aRSaleOrderBeforeDiscountAmount)
                {
                    _aRSaleOrderBeforeDiscountAmount = value;
                }
            }
        }
        public decimal ARSaleOrderAfterDiscountAmount
        {
            get { return _aRSaleOrderAfterDiscountAmount; }
            set
            {
                if (value != this._aRSaleOrderAfterDiscountAmount)
                {
                    _aRSaleOrderAfterDiscountAmount = value;
                }
            }
        }
        public decimal ARSaleOrderTotalAmount
        {
            get { return _aRSaleOrderTotalAmount; }
            set
            {
                if (value != this._aRSaleOrderTotalAmount)
                {
                    _aRSaleOrderTotalAmount = value;
                }
            }
        }
        public decimal ARSaleOrderDepositAmount
        {
            get { return _aRSaleOrderDepositAmount; }
            set
            {
                if (value != this._aRSaleOrderDepositAmount)
                {
                    _aRSaleOrderDepositAmount = value;
                }
            }
        }
        public decimal ARSaleOrderBalanceDue
        {
            get { return _aRSaleOrderBalanceDue; }
            set
            {
                if (value != this._aRSaleOrderBalanceDue)
                {
                    _aRSaleOrderBalanceDue = value;
                }
            }
        }
        public DateTime ARSaleOrderPaymentDate
        {
            get { return _aRSaleOrderPaymentDate; }
            set
            {
                if (value != this._aRSaleOrderPaymentDate)
                {
                    _aRSaleOrderPaymentDate = value;
                }
            }
        }
        public String ARSaleOrderType
        {
            get { return _aRSaleOrderType; }
            set
            {
                if (value != this._aRSaleOrderType)
                {
                    _aRSaleOrderType = value;
                }
            }
        }
        public String ARSaleOrderStatus
        {
            get { return _aRSaleOrderStatus; }
            set
            {
                if (value != this._aRSaleOrderStatus)
                {
                    _aRSaleOrderStatus = value;
                }
            }
        }
        public String ARSaleOrderCustomerName
        {
            get { return _aRSaleOrderCustomerName; }
            set
            {
                if (value != this._aRSaleOrderCustomerName)
                {
                    _aRSaleOrderCustomerName = value;
                }
            }
        }
        public String ARSaleOrderCustomerPhone
        {
            get { return _aRSaleOrderCustomerPhone; }
            set
            {
                if (value != this._aRSaleOrderCustomerPhone)
                {
                    _aRSaleOrderCustomerPhone = value;
                }
            }
        }
        public String ARSaleOrderCustomerTaxCode
        {
            get { return _aRSaleOrderCustomerTaxCode; }
            set
            {
                if (value != this._aRSaleOrderCustomerTaxCode)
                {
                    _aRSaleOrderCustomerTaxCode = value;
                }
            }
        }
        public String ARSaleOrderCustomerAddress
        {
            get { return _aRSaleOrderCustomerAddress; }
            set
            {
                if (value != this._aRSaleOrderCustomerAddress)
                {
                    _aRSaleOrderCustomerAddress = value;
                }
            }
        }
        public String ARSaleOrderCustomerDeliveryName
        {
            get { return _aRSaleOrderCustomerDeliveryName; }
            set
            {
                if (value != this._aRSaleOrderCustomerDeliveryName)
                {
                    _aRSaleOrderCustomerDeliveryName = value;
                }
            }
        }
        public String ARSaleOrderCustomerDeliveryPhone
        {
            get { return _aRSaleOrderCustomerDeliveryPhone; }
            set
            {
                if (value != this._aRSaleOrderCustomerDeliveryPhone)
                {
                    _aRSaleOrderCustomerDeliveryPhone = value;
                }
            }
        }
        public String ARSaleOrderCustomerDeliveryAddress
        {
            get { return _aRSaleOrderCustomerDeliveryAddress; }
            set
            {
                if (value != this._aRSaleOrderCustomerDeliveryAddress)
                {
                    _aRSaleOrderCustomerDeliveryAddress = value;
                }
            }
        }
        public String ARSaleOrderPaymentMethodType
        {
            get { return _aRSaleOrderPaymentMethodType; }
            set
            {
                if (value != this._aRSaleOrderPaymentMethodType)
                {
                    _aRSaleOrderPaymentMethodType = value;
                }
            }
        }
        public String ARSaleOrderPaymentTerm
        {
            get { return _aRSaleOrderPaymentTerm; }
            set
            {
                if (value != this._aRSaleOrderPaymentTerm)
                {
                    _aRSaleOrderPaymentTerm = value;
                }
            }
        }
        public int FK_GECurrencyID
        {
            get { return _fK_GECurrencyID; }
            set
            {
                if (value != this._fK_GECurrencyID)
                {
                    _fK_GECurrencyID = value;
                }
            }
        }
        public decimal ARSaleOrderExchangeRate
        {
            get { return _aRSaleOrderExchangeRate; }
            set
            {
                if (value != this._aRSaleOrderExchangeRate)
                {
                    _aRSaleOrderExchangeRate = value;
                }
            }
        }
        public int FK_GEPaymentTermID
        {
            get { return _fK_GEPaymentTermID; }
            set
            {
                if (value != this._fK_GEPaymentTermID)
                {
                    _fK_GEPaymentTermID = value;
                }
            }
        }
        public decimal ARSaleOrderSubTotalAmount
        {
            get { return _aRSaleOrderSubTotalAmount; }
            set
            {
                if (value != this._aRSaleOrderSubTotalAmount)
                {
                    _aRSaleOrderSubTotalAmount = value;
                }
            }
        }
        public int FK_HREmployeeID
        {
            get { return _fK_HREmployeeID; }
            set
            {
                if (value != this._fK_HREmployeeID)
                {
                    _fK_HREmployeeID = value;
                }
            }
        }
        public int FK_HRSellerEmployeeID
        {
            get { return _fK_HRSellerEmployeeID; }
            set
            {
                if (value != this._fK_HRSellerEmployeeID)
                {
                    _fK_HRSellerEmployeeID = value;
                }
            }
        }
        public String ARSaleOrderComment
        {
            get { return _aRSaleOrderComment; }
            set
            {
                if (value != this._aRSaleOrderComment)
                {
                    _aRSaleOrderComment = value;
                }
            }
        }
        public String ARSaleOrderInternalComment
        {
            get { return _aRSaleOrderInternalComment; }
            set
            {
                if (value != this._aRSaleOrderInternalComment)
                {
                    _aRSaleOrderInternalComment = value;
                }
            }
        }
        public int FK_ARProposalID
        {
            get { return _fK_ARProposalID; }
            set
            {
                if (value != this._fK_ARProposalID)
                {
                    _fK_ARProposalID = value;
                }
            }
        }
        #endregion

        public byte[] ARSaleOrderEmployeePicture { get; set; }
    }
    #endregion
}