using System;
using System.Text;
using System.Collections.Generic;

namespace VinaLib
{
    #region AAColumnAlias
    //-----------------------------------------------------------
    //Generated By:VinaERP Studio
    //Class:AAColumnAliasInfo
    //Created Date:Saturday, November 10, 2018
    //-----------------------------------------------------------

    public class AAColumnAliasInfo : BusinessObject
    {
        public AAColumnAliasInfo()
        {
        }
        #region Variables
        protected int _aAColumnAliasID;
        protected String _aAStatus = DefaultAAStatus;
        protected String _aAColumnAliasName = String.Empty;
        protected String _aAColumnAliasCaption = String.Empty;
        protected String _aATableName = String.Empty;
        #endregion

        #region Public properties
        public int AAColumnAliasID
        {
            get { return _aAColumnAliasID; }
            set
            {
                if (value != this._aAColumnAliasID)
                {
                    _aAColumnAliasID = value;
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                }
            }
        }
        public String AAColumnAliasName
        {
            get { return _aAColumnAliasName; }
            set
            {
                if (value != this._aAColumnAliasName)
                {
                    _aAColumnAliasName = value;
                }
            }
        }
        public String AAColumnAliasCaption
        {
            get { return _aAColumnAliasCaption; }
            set
            {
                if (value != this._aAColumnAliasCaption)
                {
                    _aAColumnAliasCaption = value;
                }
            }
        }
        public String AATableName
        {
            get { return _aATableName; }
            set
            {
                if (value != this._aATableName)
                {
                    _aATableName = value;
                }
            }
        }
        #endregion
    }
    #endregion
}