using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using VinaLib;
using System.Collections;

namespace VinaERP
{
    #region HRAllowanceConfigs
    //-----------------------------------------------------------
    //Generated By:VinaERP Studio
    //Class:HRAllowanceConfigsController
    //Created Date:Sunday, December 15, 2019
    //-----------------------------------------------------------

    public class HRAllowanceConfigsController : BaseBusinessController
    {
        public HRAllowanceConfigsController()
        {
            dal = new DALBaseProvider("HRAllowanceConfigs", typeof(HRAllowanceConfigsInfo));
        }

        public List<HRAllowanceConfigsInfo> GetAllowanceConfigByFKEmployeePayrollFormula(int employeePayrollFormularID)
        {
            DataSet ds = dal.GetDataSet("HRAllowanceConfigs_GetAllowanceConfigByFKEmployeePayrollFormula", employeePayrollFormularID);
            return (List<HRAllowanceConfigsInfo>)GetListFromDataSet(ds);
        }

        public override IList GetListFromDataSet(DataSet ds)
        {
            List<HRAllowanceConfigsInfo> list = new List<HRAllowanceConfigsInfo>();
            if (ds.Tables.Count > 0)
            {
                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    HRAllowanceConfigsInfo obj = (HRAllowanceConfigsInfo)GetObjectFromDataRow(row);
                    list.Add(obj);
                }
            }
            return list;
        }
    }
    #endregion
}