using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using VinaLib;


namespace VinaERP
{
    #region HRCalendars
    //-----------------------------------------------------------
    //Generated By:VinaERP Studio
    //Class:HRCalendarsController
    //Created Date:Sunday, December 29, 2019
    //-----------------------------------------------------------

    public class HRCalendarsController : BaseBusinessController
    {
        public HRCalendarsController()
        {
            dal = new DALBaseProvider("HRCalendars", typeof(HRCalendarsInfo));
        }
    }
    #endregion
}