using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using VinaLib;
using System.Collections;

namespace VinaERP
{
    #region HRCalendarEntrys
    //-----------------------------------------------------------
    //Generated By:VinaERP Studio
    //Class:HRCalendarEntrysController
    //Created Date:Friday, December 20, 2019
    //-----------------------------------------------------------

    public class HRCalendarEntrysController : BaseBusinessController
    {
        public HRCalendarEntrysController()
        {
            dal = new DALBaseProvider("HRCalendarEntrys", typeof(HRCalendarEntrysInfo));
        }

        public List<HRCalendarEntrysInfo> GetCalendarEntryByDateAndCalenderType(DateTime calenderEntryDate, string calenderType)
        {
            DataSet ds = dal.GetDataSet("HRCalendarEntrys_GetCalendarEntryByDateAndCalenderType", calenderEntryDate, calenderType);
            return (List<HRCalendarEntrysInfo>)GetListFromDataSet(ds);
        }

        public List<HRCalendarEntrysInfo> GetCalendarEntryByDateAndCalenderType(string calenderType, DateTime? dateFrom, DateTime? dateTo)
        {
            DataSet ds = dal.GetDataSet("HRCalendarEntrys_GetCalendarEntryByDateAndCalenderTypeEdit", calenderType, dateFrom, dateTo);
            return (List<HRCalendarEntrysInfo>)GetListFromDataSet(ds);
        }
        public override IList GetListFromDataSet(DataSet ds)
        {
            List<HRCalendarEntrysInfo> list = new List<HRCalendarEntrysInfo>();
            if (ds.Tables.Count > 0)
            {
                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    HRCalendarEntrysInfo obj = (HRCalendarEntrysInfo)GetObjectFromDataRow(row);
                    list.Add(obj);
                }
            }
            return list;
        }
    }
    #endregion
}