using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using VinaLib;


namespace VinaERP
{
    #region HRDepartmentRoomGroupItems
    //-----------------------------------------------------------
    //Generated By:VinaERP Studio
    //Class:HRDepartmentRoomGroupItemsController
    //Created Date:Friday, December 13, 2019
    //-----------------------------------------------------------

    public class HRDepartmentRoomGroupItemsController : BaseBusinessController
    {
        public HRDepartmentRoomGroupItemsController()
        {
            dal = new DALBaseProvider("HRDepartmentRoomGroupItems", typeof(HRDepartmentRoomGroupItemsInfo));
        }
    }
    #endregion
}