using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using VinaLib;


namespace VinaERP
{
    #region HREmployeeRewards
    //-----------------------------------------------------------
    //Generated By:VinaERP Studio
    //Class:HREmployeeRewardsController
    //Created Date:Saturday, December 14, 2019
    //-----------------------------------------------------------

    public class HREmployeeRewardsController : BaseBusinessController
    {
        public HREmployeeRewardsController()
        {
            dal = new DALBaseProvider("HREmployeeRewards", typeof(HREmployeeRewardsInfo));
        }

        public DataSet GetRewardListByRewardID(int rewardID)
        {
            return dal.GetDataSet("HREmployeeRewards_GetRewardListByRewardID", rewardID);
        }

        public HREmployeeRewardsInfo GetEmployeeRewardsInfoByEmployeeIDAndRewardID(int employeeID, int rewardID)
        {
            DataSet ds = dal.GetDataSet("HREmployeeRewards_GetEmployeeRewardsInfoByEmployeeIDAndRewardID", employeeID, rewardID);
            if (ds.Tables.Count > 0)
                return (HREmployeeRewardsInfo)dal.GetSingleObject(ds.Tables[0]);
            return null;
        }
    }
    #endregion
}