using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using VinaLib;


namespace VinaERP
{
    #region HREmployeeDisciplines
    //-----------------------------------------------------------
    //Generated By:VinaERP Studio
    //Class:HREmployeeDisciplinesController
    //Created Date:Saturday, December 14, 2019
    //-----------------------------------------------------------

    public class HREmployeeDisciplinesController : BaseBusinessController
    {
        public HREmployeeDisciplinesController()
        {
            dal = new DALBaseProvider("HREmployeeDisciplines", typeof(HREmployeeDisciplinesInfo));
        }
        public DataSet GetEmployeeDisciplineListByDisciplineID(int disciplineID)
        {
            return dal.GetDataSet("HREmployeeDisciplines_GetEmployeeDisciplineListByDisciplineID", disciplineID);
        }
    }
    #endregion
}