using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using VinaLib;


namespace VinaERP
{
    #region HREmployees
    //-----------------------------------------------------------
    //Generated By:VinaERP Studio
    //Class:HREmployeesController
    //Created Date:Monday, December 3, 2018
    //-----------------------------------------------------------

    public class HREmployeesController : BaseBusinessController
    {
        public HREmployeesController()
        {
            dal = new DALBaseProvider("HREmployees", typeof(HREmployeesInfo));
        }

        public void UpdateInsAllEmployee(decimal result)
        {
            dal.ExecuteStoredProcedure("HREmployees_UpdateInsAllEmployee", result);
        }
    }
    #endregion
}