using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using VinaLib;


namespace VinaERP
{
    #region HREmployeeWorkScheduleItems
    //-----------------------------------------------------------
    //Generated By:VinaERP Studio
    //Class:HREmployeeWorkScheduleItemsController
    //Created Date:Saturday, December 14, 2019
    //-----------------------------------------------------------

    public class HREmployeeWorkScheduleItemsController : BaseBusinessController
    {
        public HREmployeeWorkScheduleItemsController()
        {
            dal = new DALBaseProvider("HREmployeeWorkScheduleItems", typeof(HREmployeeWorkScheduleItemsInfo));
        }
        public DataSet GetAllDataByOverTimeID(int overTimeID)
        {
            return dal.GetDataSet("HREmployeeWorkScheduleItems_GetAllDataByOverTimeID", overTimeID);
        }
    }
    #endregion
}