using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using VinaLib;
using System.Collections;

namespace VinaERP
{
    #region HREmployeeTranfers
    //-----------------------------------------------------------
    //Generated By:VinaERP Studio
    //Class:HREmployeeTranfersController
    //Created Date:Friday, December 20, 2019
    //-----------------------------------------------------------

    public class HREmployeeTranfersController : BaseBusinessController
    {
        public HREmployeeTranfersController()
        {
            dal = new DALBaseProvider("HREmployeeTranfers", typeof(HREmployeeTranfersInfo));
        }

        public HREmployeeTranfersInfo GetEmployeeTranfersByEmployeeIDAndDate(int employeeID, DateTime dateFrom, DateTime dateTo)
        {
            return (HREmployeeTranfersInfo)dal.GetDataObject("HREmployeeTranfers_GetEmployeeTranfersByEmployeeIDAndDate", employeeID, dateFrom, dateTo);
        }

        public List<HREmployeeTranfersInfo> GetEmployeeTranfersByEmployeeIDAndDateTo(int employeeID, DateTime dateFrom)
        {
            return (List<HREmployeeTranfersInfo>)GetListFromDataSet(dal.GetDataSet("HREmployeeTranfers_GetEmployeeTranfersByEmployeeIDAndDateFrom", employeeID, dateFrom));
        }

        public override IList GetListFromDataSet(DataSet ds)
        {
            List<HREmployeeTranfersInfo> list = new List<HREmployeeTranfersInfo>();
            if (ds.Tables.Count > 0)
            {
                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    HREmployeeTranfersInfo obj = (HREmployeeTranfersInfo)GetObjectFromDataRow(row);
                    list.Add(obj);
                }
            }
            return list;
        }
    }
    #endregion
}