using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using VinaLib;


namespace VinaERP
{
    #region HRPayRollConfigs
    //-----------------------------------------------------------
    //Generated By:VinaERP Studio
    //Class:HRPayRollConfigsController
    //Created Date:Friday, December 20, 2019
    //-----------------------------------------------------------

    public class HRPayRollConfigsController : BaseBusinessController
    {
        public HRPayRollConfigsController()
        {
            dal = new DALBaseProvider("HRPayRollConfigs", typeof(HRPayRollConfigsInfo));
        }

        public HRPayRollConfigsInfo GetPayRollConfigByEmployeeID(int userID)
        {
            HRPayRollConfigsInfo objPayRollConfigsInfo = null;
            DataSet ds = dal.GetDataSet("HRPayRollConfigs_GetPayRollConfigByEmployeeID", userID);
            if (ds != null && ds.Tables.Count != 0)
            {
                if (ds.Tables[0].Rows.Count != 0)
                {
                    objPayRollConfigsInfo = (HRPayRollConfigsInfo)GetObjectFromDataRow(ds.Tables[0].Rows[0]);
                }
            }
            return objPayRollConfigsInfo;
        }
    }
    #endregion
}