using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using VinaLib;
using System.Collections;

namespace VinaERP
{
    #region HRTimesheetEmployeeLateConfigs
    //-----------------------------------------------------------
    //Generated By:VinaERP Studio
    //Class:HRTimesheetEmployeeLateConfigsController
    //Created Date:Tuesday, December 10, 2019
    //-----------------------------------------------------------

    public class HRTimesheetEmployeeLateConfigsController : BaseBusinessController
    {
        public HRTimesheetEmployeeLateConfigsController()
        {
            dal = new DALBaseProvider("HRTimesheetEmployeeLateConfigs", typeof(HRTimesheetEmployeeLateConfigsInfo));
        }

        public override IList GetListFromDataSet(DataSet ds)
        {
            List<HRTimesheetEmployeeLateConfigsInfo> list = new List<HRTimesheetEmployeeLateConfigsInfo>();
            if (ds.Tables.Count > 0)
            {
                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    HRTimesheetEmployeeLateConfigsInfo obj = (HRTimesheetEmployeeLateConfigsInfo)GetObjectFromDataRow(row);
                    list.Add(obj);
                }
            }
            return list;
        }

        public List<HRTimesheetEmployeeLateConfigsInfo> GetAllTimesheetEmployeeLateConfigs()
        {
            DataSet ds = dal.GetAllObject();
            return (List<HRTimesheetEmployeeLateConfigsInfo>)GetListFromDataSet(ds);
        }
    }
    #endregion
}