using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using VinaLib;


namespace VinaERP
{
    #region HRTimeKeeperCompletes
    //-----------------------------------------------------------
    //Generated By:VinaERP Studio
    //Class:HRTimeKeeperCompletesController
    //Created Date:Friday, December 20, 2019
    //-----------------------------------------------------------

    public class HRTimeKeeperCompletesController : BaseBusinessController
    {
        public HRTimeKeeperCompletesController()
        {
            dal = new DALBaseProvider("HRTimeKeeperCompletes", typeof(HRTimeKeeperCompletesInfo));
        }

        public List<HRTimeKeeperCompletesInfo> GetTimeKeeperByDate(string employeeCardNo, DateTime? dateFrom, DateTime? dateTo)
        {
            DataSet ds = dal.GetDataSet("HRTimeKeeperCompletes_GetTimeKeeperByDate", employeeCardNo, dateFrom, dateTo);
            List<HRTimeKeeperCompletesInfo> list = new List<HRTimeKeeperCompletesInfo>();
            if (ds.Tables.Count > 0)
            {
                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    HRTimeKeeperCompletesInfo obj = (HRTimeKeeperCompletesInfo)GetObjectFromDataRow(row);
                    list.Add(obj);
                }
            }
            ds.Dispose();
            return list;
        }
    }
    #endregion
}