using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using VinaLib;


namespace VinaERP
{
    #region HRTimesheetEmployeeLates
    //-----------------------------------------------------------
    //Generated By:VinaERP Studio
    //Class:HRTimesheetEmployeeLatesController
    //Created Date:Friday, December 20, 2019
    //-----------------------------------------------------------

    public class HRTimesheetEmployeeLatesController : BaseBusinessController
    {
        public HRTimesheetEmployeeLatesController()
        {
            dal = new DALBaseProvider("HRTimesheetEmployeeLates", typeof(HRTimesheetEmployeeLatesInfo));
        }

        public HRTimesheetEmployeeLatesInfo GetTimesheetEmployee(int employeePayrollFormulaID, int minute, string type)
        {
            DataSet ds = dal.GetDataSet("HRTimesheetEmployeeLates_GetTimesheetEmployee", employeePayrollFormulaID, minute, type);
            if (ds.Tables.Count > 0)
            {
                if (ds.Tables[0].Rows.Count < 1) return null;
                HRTimesheetEmployeeLatesInfo objTimesheetEmployeeLatesInfo = (HRTimesheetEmployeeLatesInfo)GetObjectFromDataRow(ds.Tables[0].Rows[0]);
                return objTimesheetEmployeeLatesInfo;
            }
            return null;
        }

        public HRTimesheetEmployeeLatesInfo GetHRTimesheetEmployeeMaxLate(int employeePayrollFormulaID)
        {
            DataSet ds = dal.GetDataSet("HRTimesheetEmployeeLates_GetHRTimesheetEmployeeMaxLate", employeePayrollFormulaID);
            if (ds.Tables.Count > 0)
            {
                if (ds.Tables[0].Rows.Count < 1) return null;
                HRTimesheetEmployeeLatesInfo objTimesheetEmployeeLatesInfo = (HRTimesheetEmployeeLatesInfo)GetObjectFromDataRow(ds.Tables[0].Rows[0]);
                return objTimesheetEmployeeLatesInfo;
            }
            return null;
        }
    }
    #endregion
}