using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using VinaLib;


namespace VinaERP
{
    #region HRTimeKeeperCompletes
    //-----------------------------------------------------------
    //Generated By:VinaERP Studio
    //Class:HRTimeKeeperCompletesController
    //Created Date:Friday, December 20, 2019
    //-----------------------------------------------------------

    public class HRTimeKeeperCompletesController : BaseBusinessController
    {
        public HRTimeKeeperCompletesController()
        {
            dal = new DALBaseProvider("HRTimeKeeperCompletes", typeof(HRTimeKeeperCompletesInfo));
        }

        public List<HRTimeKeeperCompletesInfo> GetTimeKeeperByDate(string employeeCardNo, DateTime? dateFrom, DateTime? dateTo)
        {
            DataSet ds = dal.GetDataSet("HRTimeKeeperCompletes_GetTimeKeeperByDate", employeeCardNo, dateFrom, dateTo);
            List<HRTimeKeeperCompletesInfo> list = new List<HRTimeKeeperCompletesInfo>();
            if (ds.Tables.Count > 0)
            {
                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    HRTimeKeeperCompletesInfo obj = (HRTimeKeeperCompletesInfo)GetObjectFromDataRow(row);
                    list.Add(obj);
                }
            }
            ds.Dispose();
            return list;
        }

        public List<HRTimeKeeperCompletesInfo> GetDataCompleteByConditions(int? departmentID, int? departmentRoomID, int? departmentRoomGroupItemID, int? employeeID, int? machineId, DateTime? dataFrom, DateTime? dataTo)
        {
            DataSet ds = dal.GetDataSet("HRTimeKeeperCompletes_GetDataCompleteByConditions", departmentID, departmentRoomID, departmentRoomGroupItemID, employeeID, machineId, dataFrom, dataTo);
            List<HRTimeKeeperCompletesInfo> list = new List<HRTimeKeeperCompletesInfo>();
            if (ds.Tables.Count > 0)
            {
                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    HRTimeKeeperCompletesInfo obj = (HRTimeKeeperCompletesInfo)GetObjectFromDataRow(row);
                    list.Add(obj);
                }
            }
            ds.Dispose();
            return list;
        }

        public List<HRTimeKeeperCompletesInfo> GetDataCompleteByConditionDates(int? departmentID, int? departmentRoomID, int? departmentRoomGroupItemID, int? employeeID, int? machineId, DateTime? dataFrom, DateTime? dataTo)
        {
            DataSet ds = dal.GetDataSet("HRTimeKeeperCompletes_GetDataCompleteByConditionDates", departmentID, departmentRoomID, departmentRoomGroupItemID, employeeID, machineId, dataFrom, dataTo);
            List<HRTimeKeeperCompletesInfo> list = new List<HRTimeKeeperCompletesInfo>();
            if (ds.Tables.Count > 0)
            {
                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    HRTimeKeeperCompletesInfo obj = (HRTimeKeeperCompletesInfo)GetObjectFromDataRow(row);
                    list.Add(obj);
                }
            }
            ds.Dispose();
            return list;
        }

        public List<HRTimeKeeperCompletesInfo> GetDataCompleteByConditionLNs(int? departmentID, int? departmentRoomID, int? departmentRoomGroupItemID, int? employeeID, int? machineId, DateTime? dataFrom, DateTime? dataTo)
        {
            DataSet ds = dal.GetDataSet("HRTimeKeeperCompletes_GetDataCompleteByConditionLNs", departmentID, departmentRoomID, departmentRoomGroupItemID, employeeID, machineId, dataFrom, dataTo);
            List<HRTimeKeeperCompletesInfo> list = new List<HRTimeKeeperCompletesInfo>();
            if (ds.Tables.Count > 0)
            {
                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    HRTimeKeeperCompletesInfo obj = (HRTimeKeeperCompletesInfo)GetObjectFromDataRow(row);
                    list.Add(obj);
                }
            }
            ds.Dispose();
            return list;
        }

        public int CheckExistData(int machineID, DateTime dateCheck, string employeeNo)
        {
            return Convert.ToInt32(dal.GetSingleValue("HRTimeKeeperCompletes_CheckExistData", machineID, dateCheck, employeeNo));
        }

        public int DeleteData(int machineID, DateTime dateCheck, string employeeNo)
        {
            return Convert.ToInt32(dal.GetSingleValue("HRTimeKeeperCompletes_DeleteData", machineID, dateCheck, employeeNo));
        }

        public int DeleteAllByDate(string employeeNo, DateTime fromDate, DateTime toDate)
        {
            return Convert.ToInt32(dal.GetSingleValue("HRTimeKeeperCompletes_DeleteAllByDate", employeeNo, fromDate, toDate));
        }
    }
    #endregion
}