using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using VinaLib;


namespace VinaERP
{
    #region HRWorkingShifts
    //-----------------------------------------------------------
    //Generated By:VinaERP Studio
    //Class:HRWorkingShiftsController
    //Created Date:Friday, December 20, 2019
    //-----------------------------------------------------------

    public class HRWorkingShiftsController : BaseBusinessController
    {
        public HRWorkingShiftsController()
        {
            dal = new DALBaseProvider("HRWorkingShifts", typeof(HRWorkingShiftsInfo));
        }

        public HRWorkingShiftsInfo GetDefaultWorkingShiftByPayrollFormulaIDAndWorkingShiftDayOfWeek(int payrollFormulaID, string workingShiftDayOfWeek)
        {
            HRWorkingShiftsInfo obj = (HRWorkingShiftsInfo)dal.GetDataObject("HRWorkingShift_GetDefaultWorkingShiftByPayrollFormulaIDAndWorkingShiftDayOfWeek", payrollFormulaID, workingShiftDayOfWeek);
            return obj;
        }

        public List<HRWorkingShiftsInfo> GetWorkingShiftByPayrollFormulaID(int payrollFormulaID)
        {

            DataSet ds = dal.GetDataSet("HRWorkingShift_GetWorkingShiftByPayrollFormulaID", payrollFormulaID);
            List<HRWorkingShiftsInfo> list = new List<HRWorkingShiftsInfo>();
            if (ds.Tables.Count > 0)
            {
                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    HRWorkingShiftsInfo obj = (HRWorkingShiftsInfo)GetObjectFromDataRow(row);
                    list.Add(obj);
                }
            }
            return list;
        }
    }
    #endregion
}