using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using VinaLib;
using System.Collections;

namespace VinaERP
{
    #region ARInvoiceItems
    //-----------------------------------------------------------
    //Generated By:VinaERP Studio
    //Class:ARInvoiceItemsController
    //Created Date:Saturday, December 1, 2018
    //-----------------------------------------------------------

    public class ARInvoiceItemsController : BaseBusinessController
    {
        public ARInvoiceItemsController()
        {
            dal = new DALBaseProvider("ARInvoiceItems", typeof(ARInvoiceItemsInfo));
        }

        public override IList GetListFromDataSet(DataSet ds)
        {
            List<ARInvoiceItemsInfo> invoiceItemList = new List<ARInvoiceItemsInfo>();
            if (ds.Tables.Count > 0)
            {
                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    ARInvoiceItemsInfo objInvoiceItems = (ARInvoiceItemsInfo)GetObjectFromDataRow(row);
                    invoiceItemList.Add(objInvoiceItems);
                }
            }
            return invoiceItemList;
        }

        public List<ARInvoiceItemsInfo> GetInvoiceItemByInvoiceIDForReport(int invoiceID)
        {
            DataSet ds = dal.GetDataSet("ARInvoiceItems_GetInvoiceItemByInvoiceIDForReport", invoiceID);
            return (List<ARInvoiceItemsInfo>)GetListFromDataSet(ds);
        }
    }
    #endregion
}