using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using VinaLib;
using System.Collections;

namespace VinaERP
{
    #region ARProposals
    //-----------------------------------------------------------
    //Generated By:VinaERP Studio
    //Class:ARProposalsController
    //Created Date:Tuesday, May 21, 2019
    //-----------------------------------------------------------

    public class ARProposalsController : BaseBusinessController
    {
        public ARProposalsController()
        {
            dal = new DALBaseProvider("ARProposals", typeof(ARProposalsInfo));
        }

        public override IList GetListFromDataSet(DataSet ds)
        {
            List<ARProposalsInfo> proposalList = new List<ARProposalsInfo>();
            if (ds.Tables.Count > 0)
            {
                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    ARProposalsInfo objProposalsInfo = (ARProposalsInfo)GetObjectFromDataRow(row);
                    proposalList.Add(objProposalsInfo);
                }
            }
            return proposalList;
        }

        public List<ARProposalsInfo> GetAllProposalForOderring()
        {
            DataSet ds = dal.GetDataSet("ARProposals_GetProposalsForOrdering");
            return (List<ARProposalsInfo>)GetListFromDataSet(ds);
        }
    }
    #endregion
}