using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using VinaLib;


namespace VinaERP
{
    #region ARSaleOrderPaymentTimes
    //-----------------------------------------------------------
    //Generated By:VinaERP Studio
    //Class:ARSaleOrderPaymentTimesController
    //Created Date:Thursday, November 29, 2018
    //-----------------------------------------------------------

    public class ARSaleOrderPaymentTimesController : BaseBusinessController
    {
        public ARSaleOrderPaymentTimesController()
        {
            dal = new DALBaseProvider("ARSaleOrderPaymentTimes", typeof(ARSaleOrderPaymentTimesInfo));
        }
    }
    #endregion
}